<a href="https://colab.research.google.com/github/txellbalada/Reto_IA/blob/main/500Datos_Reales_colomb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Reto IA: Telefonica challenge:
###Objetivo: entrenar un modelo capaz de distinguir entre un áudio real vs uno generado con IA

In [ ]:
import numpy as np
import pandas as pd
import librosa
import os
from scipy import stats
from tqdm import tqdm
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%ls /content/drive/MyDrive/Reto_Telefonica/Dataset_real/Acento_Colombiano_real_FM/

cof_00610_00008989777.wav  cof_01523_00241535803.wav  com_00610_01226934508.wav
cof_00610_00011481761.wav  cof_01523_00263223799.wav  com_00610_01229503605.wav
cof_00610_00026180919.wav  cof_01523_00272438245.wav  com_00610_01236993729.wav
cof_00610_00083325222.wav  cof_01523_00280869759.wav  com_00610_01242095809.wav
cof_00610_00100787111.wav  cof_01523_00286325544.wav  com_00610_01332319294.wav
cof_00610_00106068443.wav  cof_01523_00287301417.wav  com_00610_01345253353.wav
cof_00610_00128829414.wav  cof_01523_00295602931.wav  com_00610_01347530709.wav
cof_00610_00129157870.wav  cof_01523_00300070090.wav  com_00610_01356460222.wav
cof_00610_00131238701.wav  cof_01523_00310910177.wav  com_00610_01357734740.wav
cof_00610_00132949807.wav  cof_01523_00324308563.wav  com_00610_01399950713.wav
cof_00610_00137907909.wav  cof_01523_00330363745.wav  com_00610_01412052726.wav
cof_00610_00143476359.wav  cof_01523_00354041865.wav  com_00610_01427091610.wav
cof_00610_00144757091.wav  cof_01523_00364204205.wav  com_00610_01431511605.wav
cof_00610_00155617852.wav  cof_01523_00368573129.wav  com_00610_01436828203.wav
cof_00610_00158081190.wav  cof_01523_00395423042.wav  com_00610_01439716755.wav
cof_00610_00159513728.wav  cof_01523_00405514326.wav  com_00610_01448106783.wav
cof_00610_00191114113.wav  cof_01523_00419335523.wav  com_00610_01472433204.wav
cof_00610_00207818661.wav  cof_01523_00450174156.wav  com_00610_01485382013.wav
cof_00610_00210133831.wav  cof_01523_00473319817.wav  com_00610_01503834738.wav
cof_00610_00211979024.wav  cof_01523_00491195227.wav  com_00610_01550783796.wav
cof_00610_00215905338.wav  cof_01523_00529809810.wav  com_00610_01574517929.wav
cof_00610_00231725480.wav  cof_01523_00547503265.wav  com_00610_01623387216.wav
cof_00610_00245943195.wav  cof_01523_00549525543.wav  com_00610_01637422178.wav
cof_00610_00249716623.wav  cof_01523_00552427428.wav  com_00610_01638128865.wav
cof_00610_00258798338.wav  cof_01523_00555239207.wav  com_00610_01653012835.wav
cof_00610_00287921418.wav  cof_01523_00604591271.wav  com_00610_01661261400.wav
cof_00610_00300403819.wav  cof_01523_00611778179.wav  com_00610_01674463222.wav
cof_00610_00365026314.wav  cof_01523_00656220672.wav  com_00610_01676103003.wav
cof_00610_00425695236.wav  cof_01523_00673024470.wav  com_00610_01691646053.wav
cof_00610_00444664843.wav  cof_01523_00683660831.wav  com_00610_01706691030.wav
cof_00610_00453007773.wav  cof_01523_00715472611.wav  com_00610_01708458585.wav
cof_00610_00478945971.wav  cof_01523_00727366429.wav  com_00610_01711378856.wav
cof_00610_00509877285.wav  cof_01523_00738701733.wav  com_00610_01722982924.wav
cof_00610_00543400472.wav  cof_01523_00742968789.wav  com_00610_01744944249.wav
cof_00610_00551983037.wav  cof_01523_00760114671.wav  com_00610_01752347442.wav
cof_00610_00558869711.wav  cof_01523_00794097613.wav  com_00610_01752542331.wav
cof_00610_00561353575.wav  cof_01523_00795632842.wav  com_00610_01753570408.wav
cof_00610_00564437297.wav  cof_01523_00796365902.wav  com_00610_01757298897.wav
cof_00610_00565615554.wav  cof_01523_00800980650.wav  com_00610_01774275355.wav
cof_00610_00575817433.wav  cof_01523_00803058134.wav  com_00610_01775757383.wav
cof_00610_00578771534.wav  cof_01523_00813531077.wav  com_00610_01790043462.wav
cof_00610_00581998607.wav  cof_01523_00872061424.wav  com_00610_01801581674.wav
cof_00610_00596208225.wav  cof_01523_00901336745.wav  com_00610_01819201422.wav
cof_00610_00618725454.wav  cof_01523_00910432729.wav  com_00610_01828072638.wav
cof_00610_00648896188.wav  cof_01523_00937961208.wav  com_00610_01854164402.wav
cof_00610_00655967363.wav  cof_01523_00950688215.wav  com_00610_01870400951.wav
cof_00610_00657388450.wav  cof_01523_00953609331.wav  com_00610_01875567670.wav
cof_00610_00683936383.wav  cof_01523_00960018686.wav  com_00610_01889054402.wav
cof_00610_00686388841.wav  cof_01523_00966521868.wav  com_00610_01899213381.wav
cof_00610_00749562938.wav  cof_01523_01007796511.wav  com_00610_01907115357.wav
cof_00610_00756082844.wav  cof_01523_01011132563.wav  com_00610_01914562022.wav
cof_00610_00797573887.wav  cof_01523_01018200339.wav  com_00610_01931248306.wav
cof_00610_00798094083.wav  cof_01523_01029115021.wav  com_00610_01936334927.wav
cof_00610_00814799448.wav  cof_01523_01047300428.wav  com_00610_01941442448.wav
cof_00610_00845653420.wav  cof_01523_01054426342.wav  com_00610_01947011444.wav
cof_00610_00864540466.wav  cof_01523_01064275630.wav  com_00610_01948541751.wav
cof_00610_00913180829.wav  cof_01523_01066959942.wav  com_00610_01954361962.wav
cof_00610_00915357402.wav  cof_01523_01133182583.wav  com_00610_01987193675.wav
cof_00610_00925397497.wav  cof_01523_01157644137.wav  com_00610_02054233665.wav
cof_00610_00933823839.wav  cof_01523_01168718366.wav  com_00610_02063882340.wav
cof_00610_00951906695.wav  cof_01523_01185002519.wav  com_00610_02068255395.wav
cof_00610_00975952674.wav  cof_01523_01192631468.wav  com_00610_02068399170.wav
cof_00610_00987056120.wav  cof_01523_01199131701.wav  com_00610_02106534667.wav
cof_00610_00992162135.wav  cof_01523_01199785560.wav  com_00610_02108585319.wav
cof_00610_01005920270.wav  cof_01523_01213923060.wav  com_00610_02138036045.wav
cof_00610_01034785289.wav  cof_01523_01214594801.wav  com_01523_00006065716.wav
cof_00610_01067172216.wav  cof_01523_01245766736.wav  com_01523_00010884441.wav
cof_00610_01074699717.wav  cof_01523_01247517654.wav  com_01523_00023325432.wav
cof_00610_01103751793.wav  cof_01523_01257141592.wav  com_01523_00023844062.wav
cof_00610_01122218651.wav  cof_01523_01257820936.wav  com_01523_00025978128.wav
cof_00610_01164601276.wav  cof_01523_01258689091.wav  com_01523_00040109759.wav
cof_00610_01177279569.wav  cof_01523_01261517830.wav  com_01523_00045120750.wav
cof_00610_01182042214.wav  cof_01523_01297047509.wav  com_01523_00063393208.wav
cof_00610_01184239327.wav  cof_01523_01318664847.wav  com_01523_00063947279.wav
cof_00610_01208560288.wav  cof_01523_01344889362.wav  com_01523_00091488164.wav
cof_00610_01233565904.wav  cof_01523_01420951365.wav  com_01523_00117364064.wav
cof_00610_01233644280.wav  cof_01523_01421442232.wav  com_01523_00130328425.wav
cof_00610_01237212237.wav  cof_01523_01427683010.wav  com_01523_00139590753.wav
cof_00610_01239420315.wav  cof_01523_01430571518.wav  com_01523_00168344357.wav
cof_00610_01242559354.wav  cof_01523_01441635786.wav  com_01523_00188509935.wav
cof_00610_01307574255.wav  cof_01523_01445950580.wav  com_01523_00188955970.wav
cof_00610_01332160527.wav  cof_01523_01446676618.wav  com_01523_00217869236.wav
cof_00610_01351577649.wav  cof_01523_01463442812.wav  com_01523_00220322993.wav
cof_00610_01352413514.wav  com_00610_00008909944.wav  com_01523_00224898495.wav
cof_00610_01365273195.wav  com_00610_00031576593.wav  com_01523_00227092349.wav
cof_00610_01380840235.wav  com_00610_00033748372.wav  com_01523_00261301491.wav
cof_00610_01398673747.wav  com_00610_00038696950.wav  com_01523_00271864966.wav
cof_00610_01405447042.wav  com_00610_00075952240.wav  com_01523_00313372747.wav
cof_00610_01424711494.wav  com_00610_00084211564.wav  com_01523_00314453562.wav
cof_00610_01482178433.wav  com_00610_00091167688.wav  com_01523_00315309957.wav
cof_00610_01484692642.wav  com_00610_00113450014.wav  com_01523_00322091798.wav
cof_00610_01517257410.wav  com_00610_00116192883.wav  com_01523_00322337364.wav
cof_00610_01518372199.wav  com_00610_00117251706.wav  com_01523_00354247578.wav
cof_00610_01519839020.wav  com_00610_00151605914.wav  com_01523_00377642703.wav
cof_00610_01521699555.wav  com_00610_00188346532.wav  com_01523_00389808905.wav
cof_00610_01522609796.wav  com_00610_00203701336.wav  com_01523_00410298204.wav
cof_00610_01546685593.wav  com_00610_00222418092.wav  com_01523_00418027812.wav
cof_00610_01554940080.wav  com_00610_00235065361.wav  com_01523_00434836794.wav
cof_00610_01570108574.wav  com_00610_00256578637.wav  com_01523_00436288230.wav
cof_00610_01571881249.wav  com_00610_00259350907.wav  com_01523_00461019966.wav
cof_00610_01576373712.wav  com_00610_00269776593.wav  com_01523_00483493677.wav
cof_00610_01582670094.wav  com_00610_00271996006.wav  com_01523_00500128089.wav
cof_00610_01584809148.wav  com_00610_00277968440.wav  com_01523_00503563372.wav
cof_00610_01598240500.wav  com_00610_00286786215.wav  com_01523_00513535788.wav
cof_00610_01606969510.wav  com_00610_00289799881.wav  com_01523_00517650276.wav
cof_00610_01617668800.wav  com_00610_00307450954.wav  com_01523_00526521550.wav
cof_00610_01623396263.wav  com_00610_00355989030.wav  com_01523_00546055786.wav
cof_00610_01645580179.wav  com_00610_00374570514.wav  com_01523_00570931502.wav
cof_00610_01645880972.wav  com_00610_00374777459.wav  com_01523_00579025369.wav
cof_00610_01647927814.wav  com_00610_00384800145.wav  com_01523_00587725549.wav
cof_00610_01648707087.wav  com_00610_00400726428.wav  com_01523_00587907853.wav
cof_00610_01668621239.wav  com_00610_00419273526.wav  com_01523_00599170693.wav
cof_00610_01681854955.wav  com_00610_00428468193.wav  com_01523_00608479921.wav
cof_00610_01682930940.wav  com_00610_00431285037.wav  com_01523_00631006665.wav
cof_00610_01717132249.wav  com_00610_00444288482.wav  com_01523_00631563696.wav
cof_00610_01719338902.wav  com_00610_00447984716.wav  com_01523_00653269687.wav
cof_00610_01723843413.wav  com_00610_00455070357.wav  com_01523_00660716568.wav
cof_00610_01752734013.wav  com_00610_00457873809.wav  com_01523_00673089408.wav
cof_00610_01756388857.wav  com_00610_00475485048.wav  com_01523_00673282088.wav
cof_00610_01768560254.wav  com_00610_00478019235.wav  com_01523_00685957576.wav
cof_00610_01769855518.wav  com_00610_00484202440.wav  com_01523_00700793916.wav
cof_00610_01780031534.wav  com_00610_00486129050.wav  com_01523_00702264333.wav
cof_00610_01803432611.wav  com_00610_00490233140.wav  com_01523_00736757457.wav
cof_00610_01826783460.wav  com_00610_00499134948.wav  com_01523_00756460053.wav
cof_00610_01846322269.wav  com_00610_00510820719.wav  com_01523_00760381987.wav
cof_00610_01860410978.wav  com_00610_00522401521.wav  com_01523_00780716323.wav
cof_00610_01868155543.wav  com_00610_00535719087.wav  com_01523_00796364014.wav
cof_00610_01874786532.wav  com_00610_00540066680.wav  com_01523_00809141739.wav
cof_00610_01883761886.wav  com_00610_00583668414.wav  com_01523_00819269643.wav
cof_00610_01894857059.wav  com_00610_00587260496.wav  com_01523_00822655651.wav
cof_00610_01899727337.wav  com_00610_00611753776.wav  com_01523_00832188467.wav
cof_00610_01936293184.wav  com_00610_00624270481.wav  com_01523_00833172649.wav
cof_00610_01937154120.wav  com_00610_00680822802.wav  com_01523_00854096469.wav
cof_00610_01944219898.wav  com_00610_00684701583.wav  com_01523_00872110638.wav
cof_00610_01944700504.wav  com_00610_00689174621.wav  com_01523_00876109009.wav
cof_00610_01954876898.wav  com_00610_00756110230.wav  com_01523_00882577536.wav
cof_00610_01967418412.wav  com_00610_00757633937.wav  com_01523_00915609895.wav
cof_00610_01968851760.wav  com_00610_00761631502.wav  com_01523_00962087246.wav
cof_00610_02003889010.wav  com_00610_00782053262.wav  com_01523_00984800635.wav
cof_00610_02017713890.wav  com_00610_00802253831.wav  com_01523_00987602132.wav
cof_00610_02033040142.wav  com_00610_00812301792.wav  com_01523_00991304268.wav
cof_00610_02048411062.wav  com_00610_00816855072.wav  com_01523_00993397923.wav
cof_00610_02059838335.wav  com_00610_00831455571.wav  com_01523_01002118841.wav
cof_00610_02073822283.wav  com_00610_00848224353.wav  com_01523_01036636017.wav
cof_00610_02093562767.wav  com_00610_00861650446.wav  com_01523_01041828105.wav
cof_00610_02098390712.wav  com_00610_00868776462.wav  com_01523_01045986801.wav
cof_00610_02102765533.wav  com_00610_00907087676.wav  com_01523_01047048387.wav
cof_00610_02103979940.wav  com_00610_00922028088.wav  com_01523_01066492627.wav
cof_00610_02123351169.wav  com_00610_00933250169.wav  com_01523_01069222122.wav
cof_00610_02127196066.wav  com_00610_00934577510.wav  com_01523_01095752674.wav
cof_01523_00010305704.wav  com_00610_00944980201.wav  com_01523_01105336609.wav
cof_01523_00010635776.wav  com_00610_00965877908.wav  com_01523_01116504080.wav
cof_01523_00017388571.wav  com_00610_00972806335.wav  com_01523_01153781311.wav
cof_01523_00017665659.wav  com_00610_01017273046.wav  com_01523_01168861681.wav
cof_01523_00023703164.wav  com_00610_01037237895.wav  com_01523_01196527605.wav
cof_01523_00060644011.wav  com_00610_01041502986.wav  com_01523_01199769242.wav
cof_01523_00073415337.wav  com_00610_01056955720.wav  com_01523_01219917632.wav
cof_01523_00077386398.wav  com_00610_01067797138.wav  com_01523_01222424639.wav
cof_01523_00095432224.wav  com_00610_01079841693.wav  com_01523_01226427880.wav
cof_01523_00099138940.wav  com_00610_01126869142.wav  com_01523_01236040624.wav
cof_01523_00108474815.wav  com_00610_01133611136.wav  com_01523_01237305140.wav
cof_01523_00115400143.wav  com_00610_01139260148.wav  com_01523_01271172548.wav
cof_01523_00124064108.wav  com_00610_01141323103.wav  com_01523_01282896905.wav
cof_01523_00137472745.wav  com_00610_01144918243.wav  com_01523_01286140247.wav
cof_01523_00159959737.wav  com_00610_01148784017.wav  com_01523_01299556545.wav
cof_01523_00162566952.wav  com_00610_01152760554.wav  com_01523_01351282485.wav
cof_01523_00176362672.wav  com_00610_01156712965.wav

In [ ]:
TIPO_DATASET = "real"
ruta_carpeta = "/content/drive/MyDrive/Reto_Telefonica/Dataset_real/Acento_Colombiano_real_FM/"

In [ ]:
print("Carpeta configurada:")
print(ruta_carpeta)

print("\n¿Existe la carpeta?:", os.path.exists(ruta_carpeta))

if os.path.exists(ruta_carpeta):
    print("\nPrimeros archivos encontrados:")
    print(os.listdir(ruta_carpeta)[:10])

Carpeta configurada:
/content/drive/MyDrive/Reto_Telefonica/Dataset_real/Acento_Colombiano_real_FM/

¿Existe la carpeta?: True

Primeros archivos encontrados:
['cof_00610_00756082844.wav', 'cof_00610_01570108574.wav', 'cof_00610_01122218651.wav', 'cof_00610_00798094083.wav', 'cof_00610_01768560254.wav', 'cof_00610_00551983037.wav', 'cof_00610_01352413514.wav', 'cof_00610_00083325222.wav', 'cof_00610_01967418412.wav', 'cof_00610_00215905338.wav']

In [ ]:
#Cargar audios
archivos = os.listdir(ruta_carpeta)
print(f"Se detectaron {len(archivos)} archivos en la carpeta.\n")

for archivo in archivos:
    if archivo.lower().endswith(".wav"):
        ruta_audio = os.path.join(ruta_carpeta, archivo)

        y, sr = librosa.load(ruta_audio, sr=16000)

        print(f"{archivo} cargado | duración: {len(y)/sr:.2f} segundos")

Se detectaron 500 archivos en la carpeta.

cof_00610_00756082844.wav cargado | duración: 5.38 segundos
cof_00610_01570108574.wav cargado | duración: 5.89 segundos
cof_00610_01122218651.wav cargado | duración: 3.67 segundos
cof_00610_00798094083.wav cargado | duración: 5.97 segundos
cof_00610_01768560254.wav cargado | duración: 3.93 segundos
cof_00610_00551983037.wav cargado | duración: 4.95 segundos
cof_00610_01352413514.wav cargado | duración: 6.40 segundos
cof_00610_00083325222.wav cargado | duración: 5.89 segundos
cof_00610_01967418412.wav cargado | duración: 3.75 segundos
cof_00610_00215905338.wav cargado | duración: 5.29 segundos
cof_00610_01067172216.wav cargado | duración: 5.21 segundos
cof_00610_01803432611.wav cargado | duración: 4.44 segundos
cof_00610_00913180829.wav cargado | duración: 4.01 segundos
cof_00610_00864540466.wav cargado | duración: 5.72 segundos
cof_00610_00648896188.wav cargado | duración: 6.23 segundos
cof_00610_00797573887.wav cargado | duración: 3.84 segundos
cof_00610_00814799448.wav cargado | duración: 4.78 segundos
cof_00610_01584809148.wav cargado | duración: 6.14 segundos
cof_00610_00565615554.wav cargado | duración: 6.14 segundos
cof_00610_00683936383.wav cargado | duración: 5.55 segundos
cof_00610_01405447042.wav cargado | duración: 6.06 segundos
cof_00610_01936293184.wav cargado | duración: 4.78 segundos
cof_00610_00845653420.wav cargado | duración: 7.08 segundos
cof_00610_01723843413.wav cargado | duración: 4.52 segundos
cof_00610_00100787111.wav cargado | duración: 4.44 segundos
cof_00610_01769855518.wav cargado | duración: 6.14 segundos
cof_00610_01522609796.wav cargado | duración: 6.40 segundos
cof_00610_01005920270.wav cargado | duración: 5.46 segundos
cof_00610_00159513728.wav cargado | duración: 4.01 segundos
cof_00610_00543400472.wav cargado | duración: 7.85 segundos
cof_00610_00155617852.wav cargado | duración: 6.49 segundos
cof_00610_00008989777.wav cargado | duración: 5.21 segundos
cof_00610_00987056120.wav cargado | duración: 5.12 segundos
cof_00610_01645580179.wav cargado | duración: 4.78 segundos
cof_00610_00211979024.wav cargado | duración: 5.12 segundos
cof_00610_01598240500.wav cargado | duración: 4.61 segundos
cof_00610_01752734013.wav cargado | duración: 4.35 segundos
cof_00610_00596208225.wav cargado | duración: 5.89 segundos
cof_00610_01484692642.wav cargado | duración: 7.08 segundos
cof_00610_01518372199.wav cargado | duración: 3.84 segundos
cof_00610_01576373712.wav cargado | duración: 5.46 segundos
cof_00610_01968851760.wav cargado | duración: 4.27 segundos
cof_00610_01883761886.wav cargado | duración: 3.50 segundos
cof_00610_01103751793.wav cargado | duración: 4.69 segundos
cof_00610_01546685593.wav cargado | duración: 5.12 segundos
cof_00610_00144757091.wav cargado | duración: 4.52 segundos
cof_00610_00561353575.wav cargado | duración: 6.74 segundos
cof_00610_01719338902.wav cargado | duración: 5.63 segundos
cof_00610_00975952674.wav cargado | duración: 4.52 segundos
cof_00610_01846322269.wav cargado | duración: 8.70 segundos
cof_00610_00137907909.wav cargado | duración: 6.66 segundos
cof_00610_00011481761.wav cargado | duración: 4.86 segundos
cof_00610_00951906695.wav cargado | duración: 4.27 segundos
cof_00610_01860410978.wav cargado | duración: 5.03 segundos
cof_00610_00132949807.wav cargado | duración: 6.74 segundos
cof_00610_00129157870.wav cargado | duración: 4.69 segundos
cof_00610_00287921418.wav cargado | duración: 3.67 segundos
cof_00610_01623396263.wav cargado | duración: 5.21 segundos
cof_00610_00933823839.wav cargado | duración: 8.11 segundos
cof_00610_01237212237.wav cargado | duración: 6.23 segundos
cof_00610_00444664843.wav cargado | duración: 5.38 segundos
cof_00610_00365026314.wav cargado | duración: 5.55 segundos
cof_00610_00210133831.wav cargado | duración: 4.78 segundos
cof_00610_00686388841.wav cargado | duración: 4.61 segundos
cof_00610_00207818661.wav cargado | duración: 4.69 segundos
cof_00610_00564437297.wav cargado | duración: 4.69 segundos
cof_00610_00131238701.wav cargado | duración: 3.84 segundos
cof_00610_01894857059.wav cargado | duración: 4.10 segundos
cof_00610_00558869711.wav cargado | duración: 3.33 segundos
cof_00610_01954876898.wav cargado | duración: 3.50 segundos
cof_00610_01868155543.wav cargado | duración: 3.41 segundos
cof_00610_00581998607.wav cargado | duración: 3.75 segundos
cof_00610_01184239327.wav cargado | duración: 4.01 segundos
cof_00610_01208560288.wav cargado | duración: 3.67 segundos
cof_00610_01242559354.wav cargado | duración: 4.78 segundos
cof_00610_01424711494.wav cargado | duración: 4.61 segundos
cof_00610_01780031534.wav cargado | duración: 5.12 segundos
cof_00610_01177279569.wav cargado | duración: 5.55 segundos
cof_00610_00657388450.wav cargado | duración: 3.67 segundos
cof_00610_00128829414.wav cargado | duración: 7.17 segundos
cof_00610_01239420315.wav cargado | duración: 4.18 segundos
cof_00610_01937154120.wav cargado | duración: 4.44 segundos
cof_00610_00300403819.wav cargado | duración: 4.69 segundos
cof_00610_01571881249.wav cargado | duración: 4.01 segundos
cof_00610_00249716623.wav cargado | duración: 5.38 segundos
cof_00610_01351577649.wav cargado | duración: 3.58 segundos
cof_00610_00749562938.wav cargado | duración: 6.40 segundos
cof_00610_01645880972.wav cargado | duración: 5.80 segundos
cof_00610_01944219898.wav cargado | duración: 4.10 segundos
cof_00610_00258798338.wav cargado | duración: 4.61 segundos
cof_00610_00925397497.wav cargado | duración: 6.14 segundos
cof_00610_00231725480.wav cargado | duración: 3.58 segundos
cof_00610_01944700504.wav cargado | duración: 4.69 segundos
cof_00610_01756388857.wav cargado | duración: 3.67 segundos
cof_00610_01582670094.wav cargado | duración: 6.49 segundos
cof_00610_01074699717.wav cargado | duración: 7.51 segundos
cof_00610_00655967363.wav cargado | duración: 4.52 segundos
cof_00610_00453007773.wav cargado | duración: 4.10 segundos
cof_00610_01648707087.wav cargado | duración: 7.42 segundos
cof_00610_01034785289.wav cargado | duración: 6.74 segundos
cof_00610_01233644280.wav cargado | duración: 4.61 segundos
cof_00610_00425695236.wav cargado | duración: 5.80 segundos
cof_00610_01617668800.wav cargado | duración: 5.03 segundos
cof_00610_00575817433.wav cargado | duración: 4.78 segundos
cof_00610_01517257410.wav cargado | duración: 3.07 segundos
cof_00610_00915357402.wav cargado | duración: 6.83 segundos
cof_00610_00478945971.wav cargado | duración: 3.84 segundos
cof_00610_00191114113.wav cargado | duración: 4.95 segundos
cof_00610_00509877285.wav cargado | duración: 4.44 segundos
cof_00610_00618725454.wav cargado | duración: 3.24 segundos
cof_00610_00106068443.wav cargado | duración: 6.40 segundos
cof_00610_00158081190.wav cargado | duración: 3.84 segundos
cof_00610_00992162135.wav cargado | duración: 5.80 segundos
cof_00610_00245943195.wav cargado | duración: 5.03 segundos
cof_00610_00578771534.wav cargado | duración: 4.61 segundos
cof_00610_01681854955.wav cargado | duración: 4.27 segundos
cof_00610_01398673747.wav cargado | duración: 4.01 segundos
cof_00610_01682930940.wav cargado | duración: 3.84 segundos
cof_00610_01554940080.wav cargado | duración: 5.63 segundos
cof_00610_01482178433.wav cargado | duración: 4.44 segundos
cof_00610_01521699555.wav cargado | duración: 4.44 segundos
cof_00610_01182042214.wav cargado | duración: 4.18 segundos
cof_00610_01606969510.wav cargado | duración: 7.00 segundos
cof_00610_01164601276.wav cargado | duración: 4.10 segundos
cof_00610_01233565904.wav cargado | duración: 3.67 segundos
cof_00610_01519839020.wav cargado | duración: 4.44 segundos
cof_00610_01365273195.wav cargado | duración: 5.29 segundos
cof_00610_01899727337.wav cargado | duración: 3.93 segundos
cof_00610_01668621239.wav cargado | duración: 2.56 segundos
cof_00610_01874786532.wav cargado | duración: 3.75 segundos
cof_00610_01826783460.wav cargado | duración: 2.56 segundos
cof_00610_00026180919.wav cargado | duración: 4.27 segundos
cof_00610_00143476359.wav cargado | duración: 3.67 segundos
cof_00610_01332160527.wav cargado | duración: 4.78 segundos
cof_00610_01307574255.wav cargado | duración: 3.84 segundos
cof_00610_01717132249.wav cargado | duración: 5.97 segundos
cof_00610_01647927814.wav cargado | duración: 6.83 segundos
cof_00610_01380840235.wav cargado | duración: 4.78 segundos
cof_01523_00286325544.wav cargado | duración: 5.89 segundos
cof_01523_00395423042.wav cargado | duración: 4.44 segundos
cof_01523_00742968789.wav cargado | duración: 7.85 segundos
cof_01523_00017665659.wav cargado | duración: 5.21 segundos
cof_01523_00901336745.wav cargado | duración: 7.51 segundos
cof_01523_01054426342.wav cargado | duración: 5.55 segundos
cof_01523_00450174156.wav cargado | duración: 4.18 segundos
cof_01523_00095432224.wav cargado | duración: 4.52 segundos
cof_01523_00796365902.wav cargado | duración: 7.34 segundos
cof_01523_00115400143.wav cargado | duración: 4.52 segundos
cof_01523_01441635786.wav cargado | duración: 5.29 segundos
cof_01523_00017388571.wav cargado | duración: 4.52 segundos
cof_01523_00405514326.wav cargado | duración: 4.44 segundos
cof_01523_01029115021.wav cargado | duración: 6.40 segundos
cof_01523_00960018686.wav cargado | duración: 5.21 segundos
cof_01523_01047300428.wav cargado | duración: 5.29 segundos
cof_01523_00795632842.wav cargado | duración: 4.86 segundos
cof_01523_01064275630.wav cargado | duración: 6.31 segundos
cof_01523_00950688215.wav cargado | duración: 6.74 segundos
cof_01523_01245766736.wav cargado | duración: 5.03 segundos
cof_01523_00529809810.wav cargado | duración: 6.31 segundos
cof_01523_00108474815.wav cargado | duración: 8.53 segundos
cof_00610_02048411062.wav cargado | duración: 4.01 segundos
cof_01523_00272438245.wav cargado | duración: 7.34 segundos
cof_01523_00547503265.wav cargado | duración: 6.06 segundos
cof_01523_00738701733.wav cargado | duración: 5.29 segundos
cof_01523_01199785560.wav cargado | duración: 5.72 segundos
cof_01523_01007796511.wav cargado | duración: 6.14 segundos
cof_01523_00023703164.wav cargado | duración: 4.61 segundos
cof_00610_02103979940.wav cargado | duración: 5.38 segundos
cof_01523_01430571518.wav cargado | duración: 6.14 segundos
cof_01523_00010635776.wav cargado | duración: 4.01 segundos
cof_00610_02073822283.wav cargado | duración: 5.12 segundos
cof_00610_02098390712.wav cargado | duración: 4.95 segundos
cof_01523_00060644011.wav cargado | duración: 6.74 segundos
cof_01523_00364204205.wav cargado | duración: 5.97 segundos
cof_01523_01066959942.wav cargado | duración: 6.31 segundos
cof_01523_00099138940.wav cargado | duración: 6.31 segundos
cof_00610_02093562767.wav cargado | duración: 5.97 segundos
cof_01523_00555239207.wav cargado | duración: 5.03 segundos
cof_01523_01420951365.wav cargado | duración: 8.02 segundos
cof_01523_00324308563.wav cargado | duración: 5.72 segundos
cof_01523_01018200339.wav cargado | duración: 4.69 segundos
cof_01523_01257820936.wav cargado | duración: 7.94 segundos
cof_01523_00295602931.wav cargado | duración: 6.74 segundos
cof_01523_01168718366.wav cargado | duración: 5.89 segundos
cof_01523_00491195227.wav cargado | duración: 5.29 segundos
cof_01523_00683660831.wav cargado | duración: 5.46 segundos
cof_01523_01192631468.wav cargado | duración: 3.58 segundos
cof_01523_00159959737.wav cargado | duración: 5.55 segundos
cof_01523_00937961208.wav cargado | duración: 5.12 segundos
cof_01523_01133182583.wav cargado | duración: 4.35 segundos
cof_01523_01318664847.wav cargado | duración: 5.03 segundos
cof_01523_00287301417.wav cargado | duración: 4.61 segundos
cof_00610_02033040142.wav cargado | duración: 4.95 segundos
cof_01523_00611778179.wav cargado | duración: 3.84 segundos
cof_01523_00473319817.wav cargado | duración: 4.61 segundos
cof_01523_00010305704.wav cargado | duración: 5.12 segundos
cof_01523_01199131701.wav cargado | duración: 6.14 segundos
cof_01523_01214594801.wav cargado | duración: 7.17 segundos
cof_01523_00162566952.wav cargado | duración: 6.83 segundos
cof_01523_01157644137.wav cargado | duración: 6.06 segundos
cof_01523_00760114671.wav cargado | duración: 5.03 segundos
cof_01523_00368573129.wav cargado | duración: 4.86 segundos
cof_01523_01258689091.wav cargado | duración: 6.74 segundos
cof_01523_01427683010.wav cargado | duración: 4.69 segundos
cof_01523_00813531077.wav cargado | duración: 7.51 segundos
cof_01523_00794097613.wav cargado | duración: 6.06 segundos
cof_01523_00673024470.wav cargado | duración: 5.38 segundos
cof_01523_00176362672.wav cargado | duración: 5.55 segundos
cof_00610_02127196066.wav cargado | duración: 4.27 segundos
cof_01523_00803058134.wav cargado | duración: 6.14 segundos
cof_01523_01297047509.wav cargado | duración: 5.80 segundos
cof_01523_01011132563.wav cargado | duración: 5.03 segundos
cof_01523_01421442232.wav cargado | duración: 5.38 segundos
cof_01523_00124064108.wav cargado | duración: 7.42 segundos
cof_00610_02059838335.wav cargado | duración: 4.86 segundos
cof_01523_00727366429.wav cargado | duración: 4.95 segundos
cof_01523_01344889362.wav cargado | duración: 7.59 segundos
cof_01523_00549525543.wav cargado | duración: 7.85 segundos
cof_01523_01463442812.wav cargado | duración: 4.35 segundos
cof_00610_02102765533.wav cargado | duración: 5.38 segundos
cof_01523_01247517654.wav cargado | duración: 5.72 segundos
cof_01523_01185002519.wav cargado | duración: 8.45 segundos
cof_00610_02017713890.wav cargado | duración: 4.27 segundos
cof_01523_00263223799.wav cargado | duración: 7.85 segundos
cof_01523_00073415337.wav cargado | duración: 4.61 segundos
cof_01523_00419335523.wav cargado | duración: 5.12 segundos
cof_01523_00077386398.wav cargado | duración: 6.40 segundos
cof_01523_00241535803.wav cargado | duración: 4.27 segundos
cof_01523_00872061424.wav cargado | duración: 7.85 segundos
cof_00610_02123351169.wav cargado | duración: 4.27 segundos
cof_01523_00310910177.wav cargado | duración: 6.49 segundos
cof_01523_00656220672.wav cargado | duración: 4.27 segundos
cof_01523_00604591271.wav cargado | duración: 4.78 segundos
cof_00610_02003889010.wav cargado | duración: 4.18 segundos
cof_01523_00354041865.wav cargado | duración: 4.78 segundos
cof_01523_01445950580.wav cargado | duración: 6.06 segundos
cof_01523_00280869759.wav cargado | duración: 6.06 segundos
cof_01523_00300070090.wav cargado | duración: 5.80 segundos
cof_01523_00800980650.wav cargado | duración: 4.86 segundos
cof_01523_01257141592.wav cargado | duración: 4.35 segundos
cof_01523_00330363745.wav cargado | duración: 6.14 segundos
cof_01523_00137472745.wav cargado | duración: 7.42 segundos
cof_01523_00715472611.wav cargado | duración: 5.97 segundos
cof_01523_01446676618.wav cargado | duración: 3.93 segundos
cof_01523_00953609331.wav cargado | duración: 4.78 segundos
cof_01523_00552427428.wav cargado | duración: 5.80 segundos
cof_01523_01213923060.wav cargado | duración: 5.21 segundos
cof_01523_01261517830.wav cargado | duración: 6.49 segundos
cof_01523_00910432729.wav cargado | duración: 6.23 segundos
cof_01523_00966521868.wav cargado | duración: 4.86 segundos
com_00610_00535719087.wav cargado | duración: 3.93 segundos
com_00610_00868776462.wav cargado | duración: 3.84 segundos
com_00610_00031576593.wav cargado | duración: 4.95 segundos
com_00610_00490233140.wav cargado | duración: 4.44 segundos
com_00610_00802253831.wav cargado | duración: 5.12 segundos
com_00610_00782053262.wav cargado | duración: 7.00 segundos
com_00610_00444288482.wav cargado | duración: 4.35 segundos
com_00610_00355989030.wav cargado | duración: 4.95 segundos
com_00610_00117251706.wav cargado | duración: 4.86 segundos
com_00610_00447984716.wav cargado | duración: 3.16 segundos
com_00610_00484202440.wav cargado | duración: 4.69 segundos
com_00610_00689174621.wav cargado | duración: 4.01 segundos
com_00610_00419273526.wav cargado | duración: 4.18 segundos
com_00610_00522401521.wav cargado | duración: 5.97 segundos
com_00610_00457873809.wav cargado | duración: 2.90 segundos
com_00610_00831455571.wav cargado | duración: 3.50 segundos
com_00610_00033748372.wav cargado | duración: 4.01 segundos
com_00610_00611753776.wav cargado | duración: 5.55 segundos
com_00610_00374777459.wav cargado | duración: 2.13 segundos
com_00610_00289799881.wav cargado | duración: 3.41 segundos
com_00610_00861650446.wav cargado | duración: 4.35 segundos
com_00610_00583668414.wav cargado | duración: 2.99 segundos
com_00610_00684701583.wav cargado | duración: 6.91 segundos
com_00610_00499134948.wav cargado | duración: 3.67 segundos
com_00610_00075952240.wav cargado | duración: 5.80 segundos
com_00610_00478019235.wav cargado | duración: 3.84 segundos
com_00610_00203701336.wav cargado | duración: 5.55 segundos
com_00610_00277968440.wav cargado | duración: 7.00 segundos
com_00610_00624270481.wav cargado | duración: 8.02 segundos
com_00610_00848224353.wav cargado | duración: 2.13 segundos
com_00610_00091167688.wav cargado | duración: 2.47 segundos
com_00610_00431285037.wav cargado | duración: 4.78 segundos
com_00610_00486129050.wav cargado | duración: 5.03 segundos
com_00610_00400726428.wav cargado | duración: 3.07 segundos
com_00610_00008909944.wav cargado | duración: 5.89 segundos
com_00610_00286786215.wav cargado | duración: 5.89 segundos
com_00610_00259350907.wav cargado | duración: 4.44 segundos
com_00610_00235065361.wav cargado | duración: 6.49 segundos
com_00610_00307450954.wav cargado | duración: 4.27 segundos
com_00610_00428468193.wav cargado | duración: 4.44 segundos
com_00610_00680822802.wav cargado | duración: 5.12 segundos
com_00610_00384800145.wav cargado | duración: 4.35 segundos
com_00610_00038696950.wav cargado | duración: 3.16 segundos
com_00610_00510820719.wav cargado | duración: 3.07 segundos
com_00610_00222418092.wav cargado | duración: 3.58 segundos
com_00610_00256578637.wav cargado | duración: 5.38 segundos
com_00610_00374570514.wav cargado | duración: 5.29 segundos
com_00610_00116192883.wav cargado | duración: 4.18 segundos
com_00610_00271996006.wav cargado | duración: 3.67 segundos
com_00610_00812301792.wav cargado | duración: 5.21 segundos
com_00610_00455070357.wav cargado | duración: 4.01 segundos
com_00610_00475485048.wav cargado | duración: 4.35 segundos
com_00610_00761631502.wav cargado | duración: 5.72 segundos
com_00610_00188346532.wav cargado | duración: 4.35 segundos
com_00610_00151605914.wav cargado | duración: 5.63 segundos
com_00610_00113450014.wav cargado | duración: 6.14 segundos
com_00610_00084211564.wav cargado | duración: 3.07 segundos
com_00610_00540066680.wav cargado | duración: 7.77 segundos
com_00610_00816855072.wav cargado | duración: 4.18 segundos
com_00610_00757633937.wav cargado | duración: 4.78 segundos
com_00610_00269776593.wav cargado | duración: 3.75 segundos
com_00610_00587260496.wav cargado | duración: 4.44 segundos
com_00610_00756110230.wav cargado | duración: 3.75 segundos
com_01523_00377642703.wav cargado | duración: 4.44 segundos
com_00610_01774275355.wav cargado | duración: 4.10 segundos
com_00610_01828072638.wav cargado | duración: 3.84 segundos
com_01523_00354247578.wav cargado | duración: 2.13 segundos
com_00610_01638128865.wav cargado | duración: 3.41 segundos
com_01523_00261301491.wav cargado | duración: 3.07 segundos
com_01523_00434836794.wav cargado | duración: 4.95 segundos
com_00610_00933250169.wav cargado | duración: 7.77 segundos
com_00610_01936334927.wav cargado | duración: 4.18 segundos
com_01523_00483493677.wav cargado | duración: 5.29 segundos
com_00610_01236993729.wav cargado | duración: 4.35 segundos
com_00610_01472433204.wav cargado | duración: 3.58 segundos
com_00610_01653012835.wav cargado | duración: 3.93 segundos
com_00610_01357734740.wav cargado | duración: 8.19 segundos
com_00610_01139260148.wav cargado | duración: 3.75 segundos
com_01523_00006065716.wav cargado | duración: 3.50 segundos
com_00610_01056955720.wav cargado | duración: 6.83 segundos
com_01523_00217869236.wav cargado | duración: 4.27 segundos
com_00610_01752542331.wav cargado | duración: 3.24 segundos

In [ ]:
def extraer_etiquetas(nombre_audio, modo="auto"):
    """
    Extrae etiquetas binarias desde el nombre del audio.

    Devuelve un diccionario con:
    - label: 0 real / 1 sintético
    - genero_f: 1 mujer / 0 hombre
    - nacionalidad: colombiano / chileno / argentino
    - modelo generador: CycleGAN, Diff, StarGAN, TTS-Dif, TTS-StarGAN, TTS
    """

    nombre = nombre_audio.lower()

    etiquetas = {
        # Label principal
        "label": 0,

        # Género (solo una columna)
        "genero_f": 0,

        # Nacionalidad
        "colombiano": 0,
        "chileno": 0,
        "argentino": 0,

        # Modelo generador
        "modelo_cyclegan": 0,
        "modelo_diff": 0,
        "modelo_stargan": 0,
        "modelo_tts_dif": 0,
        "modelo_tts_stargan": 0,
        "modelo_tts": 0
    }

    # -----------------------------
    # 1. Label principal
    # -----------------------------
    if modo == "real":
        etiquetas["label"] = 0
    elif modo == "sintetico":
        etiquetas["label"] = 1
    else:
        etiquetas["label"] = 1 if "-" in nombre_audio else 0

    # -----------------------------
    # 2. Nacionalidad + género
    # -----------------------------
    if "com" in nombre:
        etiquetas["colombiano"] = 1
        etiquetas["genero_f"] = 0

    elif "cof" in nombre:
        etiquetas["colombiano"] = 1
        etiquetas["genero_f"] = 1

    elif "clm" in nombre:
        etiquetas["chileno"] = 1
        etiquetas["genero_f"] = 0

    elif "clf" in nombre:
        etiquetas["chileno"] = 1
        etiquetas["genero_f"] = 1

    elif "arm" in nombre:
        etiquetas["argentino"] = 1
        etiquetas["genero_f"] = 0

    elif "arf" in nombre:
        etiquetas["argentino"] = 1
        etiquetas["genero_f"] = 1

    # -----------------------------
    # 3. Modelo generador
    # -----------------------------
    nombre_original = nombre_audio  # mantener mayúsculas

    if "TTS-StarGAN" in nombre_original:
        etiquetas["modelo_tts_stargan"] = 1
    elif "TTS-Dif" in nombre_original:
        etiquetas["modelo_tts_dif"] = 1
    elif "CycleGAN" in nombre_original:
        etiquetas["modelo_cyclegan"] = 1
    elif "StarGAN" in nombre_original:
        etiquetas["modelo_stargan"] = 1
    elif "Diff" in nombre_original:
        etiquetas["modelo_diff"] = 1
    elif "TTS" in nombre_original:
        etiquetas["modelo_tts"] = 1

    return etiquetas

In [ ]:
def generar_df_etiquetas(ruta_carpeta, tipo_dataset="auto"):
    """
    Genera un DataFrame con múltiples etiquetas:
    - id_audio: identificador secuencial (1, 2, 3, ...)
    - archivo: nombre original del archivo
    - label: real (0) vs sintético (1)
    - genero_f: mujer (1), hombre (0)
    - nacionalidad: colombiano / chileno / argentino
    - modelo generador
    """

    print(f"Explorando carpeta: {ruta_carpeta}")
    datos = []

    contador_id = 1

    for archivo in sorted(os.listdir(ruta_carpeta)):
        if archivo.lower().endswith(".wav"):
            nombre_audio = archivo.replace(".wav", "")

            etiquetas = extraer_etiquetas(nombre_audio, modo=tipo_dataset)

            fila = {
                "id_audio": contador_id,
                "archivo": archivo
            }

            fila.update(etiquetas)
            datos.append(fila)

            contador_id += 1

    df_etiquetas = pd.DataFrame(datos)

    print(f"DataFrame creado con {len(df_etiquetas)} registros.")
    print(f"Número de columnas: {df_etiquetas.shape[1]}")

    return df_etiquetas

In [ ]:
df_labels = generar_df_etiquetas(ruta_carpeta, tipo_dataset=TIPO_DATASET)
df_labels.head()

Explorando carpeta: /content/drive/MyDrive/Reto_Telefonica/Dataset_real/Acento_Colombiano_real_FM/
DataFrame creado con 500 registros.
Número de columnas: 13

,id_audio,archivo,label,genero_f,colombiano,chileno,argentino,modelo_cyclegan,modelo_diff,modelo_stargan,modelo_tts_dif,modelo_tts_stargan,modelo_tts
0,1,cof_00610_00008989777.wav,0,1,1,0,0,0,0,0,0,0,0
1,2,cof_00610_00011481761.wav,0,1,1,0,0,0,0,0,0,0,0
2,3,cof_00610_00026180919.wav,0,1,1,0,0,0,0,0,0,0,0
3,4,cof_00610_00083325222.wav,0,1,1,0,0,0,0,0,0,0,0
4,5,cof_00610_00100787111.wav,0,1,1,0,0,0,0,0,0,0,0

##  Mejor opción para TU problema (detección de voz fake)

Para detectar audio sintético, lo más importante es capturar:

- textura espectral (cómo suena la voz)  
- irregularidades (artefactos de IA)  
- dinámica (energía, variaciones)  

 Por eso, la mejor combinación es:


###  1. MFCC + Delta MFCC (OBLIGATORIO)

Son las más importantes.

Capturan:

- forma del espectro (timbre)  
- cambios en el tiempo  

✔ Detectan muy bien voces sintéticas  


###  2. Features de energía y estructura

- RMS → energía  
- ZCR → ruido/aspereza  

✔ Útiles para detectar artefactos de IA  



###  3. Features espectrales

- Spectral centroid → brillo  
- Bandwidth → dispersión  
- Rolloff → límite de energía  
- Flatness → tonal vs ruido  

✔ Clave para distinguir natural vs artificial  


###  4. Spectral contrast (MUY importante)

Esto muchas veces se subestima, pero:

 captura diferencias entre bandas de frecuencia  

✔ Muy útil para detectar:

- vocoders  
- modelos tipo GAN / TTS  


###  5. Estadísticas (CRÍTICO)

Esto es lo que mucha gente hace mal:

 NO usar los valores frame a frame  
 SÍ usar resumen:

- mean  
- std  
- min  
- max  
- median  
- q1  
- q3  

✔ Esto convierte el audio en una representación robusta  


## Entonces… ¿cuál es la mejor opción?

 EXACTAMENTE la que implementaste en el notebook nuevo:

✔ MFCC (13)  
✔ Delta MFCC  
✔ ZCR  
✔ RMS  
✔ Spectral features  
✔ Spectral contrast  
✔ Estadísticas completas

In [ ]:
def resumir_feature(vector, prefijo, debug=False):
    """
    Resume un vector numérico con estadísticas descriptivas avanzadas.
    """
    vector = np.asarray(vector).astype(float)

    if len(vector) == 0:
        return {}

    resultado = {
        f"{prefijo}_mean": np.mean(vector),
        f"{prefijo}_std": np.std(vector),
        f"{prefijo}_min": np.min(vector),
        f"{prefijo}_max": np.max(vector),
        f"{prefijo}_median": np.median(vector),
        f"{prefijo}_q1": np.quantile(vector, 0.25),
        f"{prefijo}_q3": np.quantile(vector, 0.75),
        f"{prefijo}_skew": stats.skew(vector),
        f"{prefijo}_kurtosis": stats.kurtosis(vector),
        f"{prefijo}_mode": stats.mode(vector, keepdims=True)[0][0],
        f"{prefijo}_iqr": stats.iqr(vector)
    }

    if debug:
        print(f"\n🔍 Feature: {prefijo}")
        print(f"   Total valores generados: {len(resultado)}")
        for k, v in list(resultado.items())[:3]:
            print(f"   {k}: {v:.4f}")

    return resultado

In [ ]:
def extraer_features(ruta_audio, sr_objetivo=16000, n_mfcc=13):
    """
    Extrae features de un audio y devuelve un diccionario.
    """

    y, sr = librosa.load(ruta_audio, sr=sr_objetivo)

    # Recorte de silencios
    y, _ = librosa.effects.trim(y)

    if len(y) < 512:
        return None

    features = {}

    # Meta
    features["duracion_seg"] = len(y) / sr

    # ZCR
    zcr = librosa.feature.zero_crossing_rate(y)[0]
    features.update(resumir_feature(zcr, "zcr"))

    # RMS
    rms = librosa.feature.rms(y=y)[0]
    features.update(resumir_feature(rms, "rms"))

    # RMSE manual
    rmse_manual = np.sqrt(np.mean(y**2))
    features["rmse_manual"] = rmse_manual

    # Tempo
    tempo = librosa.beat.tempo(y=y, sr=sr)[0]
    features["tempo"] = tempo

    # MFCC
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
    for i in range(n_mfcc):
        features.update(resumir_feature(mfcc[i], f"mfcc_{i+1}"))

    # Delta MFCC
    delta_mfcc = librosa.feature.delta(mfcc)
    for i in range(n_mfcc):
        features.update(resumir_feature(delta_mfcc[i], f"delta_mfcc_{i+1}"))

    # Delta-Delta MFCC
    delta2_mfcc = librosa.feature.delta(mfcc, order=2)
    for i in range(n_mfcc):
        features.update(resumir_feature(delta2_mfcc[i], f"delta2_mfcc_{i+1}"))

    # Spectral centroid
    centroid = librosa.feature.spectral_centroid(y=y, sr=sr)[0]
    features.update(resumir_feature(centroid, "centroid"))

    # Spectral bandwidth
    bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=sr)[0]
    features.update(resumir_feature(bandwidth, "bandwidth"))

    # Spectral contrast
    contrast = librosa.feature.spectral_contrast(y=y, sr=sr)
    for i in range(contrast.shape[0]):
        features.update(resumir_feature(contrast[i], f"contrast_{i+1}"))

    # Spectral flatness
    flatness = librosa.feature.spectral_flatness(y=y)[0]
    features.update(resumir_feature(flatness, "flatness"))

    # Spectral rolloff
    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)[0]
    features.update(resumir_feature(rolloff, "rolloff"))

    print(f"🎧 {os.path.basename(ruta_audio)}")
    print(f"   - Features extraídas: {len(features)}")
    print(f"   - Tempo: {tempo:.2f}")
    print(f"   - RMSE manual: {rmse_manual:.5f}")

    return features

In [ ]:
print("\n Probando extracción de features con un audio...\n")

for archivo in sorted(os.listdir(ruta_carpeta)):
    if archivo.lower().endswith(".wav"):
        ruta_audio_prueba = os.path.join(ruta_carpeta, archivo)

        try:
            ejemplo_features = extraer_features(ruta_audio_prueba)

            if ejemplo_features is None:
                print(f" Audio omitido (muy corto): {archivo}")
                continue

            print("\n Resultado:")
            print(f"   - Audio: {archivo}")
            print(f"   - Nº features: {len(ejemplo_features)}")

            print("\n Ejemplo de features:")
            for k, v in list(ejemplo_features.items())[:5]:
                print(f"   {k}: {v}")

            valores = list(ejemplo_features.values())
            n_nan = sum(np.isnan(valores))
            n_inf = sum(np.isinf(valores))

            print("\n Control de calidad:")
            print(f"   - NaN: {n_nan}")
            print(f"   - Inf: {n_inf}")

            break

        except Exception as e:
            print(f" Error con {archivo}: {e}")
            continue

 Probando extracción de features con un audio...

/tmp/ipykernel_9082/678304563.py:32: FutureWarning: librosa.beat.tempo
	This function was moved to 'librosa.feature.rhythm.tempo' in librosa version 0.10.0.
	This alias will be removed in librosa version 1.0.
  tempo = librosa.beat.tempo(y=y, sr=sr)[0]

🎧 cof_00610_00008989777.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05312

 Resultado:
   - Audio: cof_00610_00008989777.wav
   - Nº features: 575

 Ejemplo de features:
   duracion_seg: 4.5333125
   zcr_mean: 0.12801909110915494
   zcr_std: 0.10808946207186829
   zcr_min: 0.01123046875
   zcr_max: 0.52099609375

 Control de calidad:
   - NaN: 0
   - Inf: 0

In [ ]:
registros = []

archivos_wav = sorted([a for a in os.listdir(ruta_carpeta) if a.lower().endswith(".wav")])

for idx, archivo in enumerate(tqdm(archivos_wav), start=1):
    ruta_audio = os.path.join(ruta_carpeta, archivo)
    nombre_audio = archivo.replace(".wav", "")

    try:
        etiquetas = extraer_etiquetas(nombre_audio, modo=TIPO_DATASET)
        feats = extraer_features(ruta_audio)

        if feats is None:
            print(f"Audio omitido por ser demasiado corto: {archivo}")
            continue

        fila = {
            "id_audio": idx,
            "archivo": archivo
        }

        fila.update(etiquetas)
        fila.update(feats)

        registros.append(fila)

    except Exception as e:
        print(f"Error procesando {archivo}: {e}")

  0%|          | 0/500 [00:00<?, ?it/s]/tmp/ipykernel_9082/678304563.py:32: FutureWarning: librosa.beat.tempo
	This function was moved to 'librosa.feature.rhythm.tempo' in librosa version 0.10.0.
	This alias will be removed in librosa version 1.0.
  tempo = librosa.beat.tempo(y=y, sr=sr)[0]
  0%|          | 1/500 [00:00<01:48,  4.61it/s]

🎧 cof_00610_00008989777.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05312

  0%|          | 2/500 [00:00<01:47,  4.63it/s]

🎧 cof_00610_00011481761.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05705

  1%|          | 3/500 [00:00<01:48,  4.56it/s]

🎧 cof_00610_00026180919.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06693

  1%|          | 4/500 [00:00<01:50,  4.50it/s]

🎧 cof_00610_00083325222.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06943

  1%|          | 5/500 [00:01<01:47,  4.63it/s]

🎧 cof_00610_00100787111.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06885

  1%|          | 6/500 [00:01<02:21,  3.50it/s]

🎧 cof_00610_00106068443.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05829

  1%|▏         | 7/500 [00:03<05:37,  1.46it/s]

🎧 cof_00610_00128829414.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06964

  2%|▏         | 9/500 [00:03<03:31,  2.32it/s]

🎧 cof_00610_00129157870.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09265
🎧 cof_00610_00131238701.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07266

  2%|▏         | 10/500 [00:03<03:02,  2.68it/s]

🎧 cof_00610_00132949807.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.05514

  2%|▏         | 11/500 [00:03<02:43,  2.99it/s]

🎧 cof_00610_00137907909.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07899

  2%|▏         | 12/500 [00:04<02:24,  3.39it/s]

🎧 cof_00610_00143476359.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.07029

  3%|▎         | 13/500 [00:04<02:11,  3.69it/s]

🎧 cof_00610_00144757091.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06211

  3%|▎         | 14/500 [00:04<02:20,  3.46it/s]

🎧 cof_00610_00155617852.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07798

  3%|▎         | 15/500 [00:05<02:25,  3.33it/s]

🎧 cof_00610_00158081190.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.05230

  3%|▎         | 16/500 [00:05<02:23,  3.38it/s]

🎧 cof_00610_00159513728.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.05035

  3%|▎         | 17/500 [00:05<02:32,  3.17it/s]

🎧 cof_00610_00191114113.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06350

  4%|▎         | 18/500 [00:05<02:32,  3.15it/s]

🎧 cof_00610_00207818661.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04904

  4%|▍         | 19/500 [00:06<02:39,  3.01it/s]

🎧 cof_00610_00210133831.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06327

  4%|▍         | 20/500 [00:06<02:46,  2.88it/s]

🎧 cof_00610_00211979024.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06184

  4%|▍         | 21/500 [00:07<02:52,  2.78it/s]

🎧 cof_00610_00215905338.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07869

  4%|▍         | 22/500 [00:07<02:51,  2.79it/s]

🎧 cof_00610_00231725480.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.04806

  5%|▍         | 23/500 [00:07<02:52,  2.76it/s]

🎧 cof_00610_00245943195.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06204

  5%|▍         | 24/500 [00:08<02:58,  2.67it/s]

🎧 cof_00610_00249716623.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08159

  5%|▌         | 25/500 [00:08<02:53,  2.74it/s]

🎧 cof_00610_00258798338.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07731

  5%|▌         | 26/500 [00:08<02:38,  2.99it/s]

🎧 cof_00610_00287921418.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04186

  5%|▌         | 27/500 [00:09<02:35,  3.04it/s]

🎧 cof_00610_00300403819.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.04659

  6%|▌         | 28/500 [00:09<02:38,  2.98it/s]

🎧 cof_00610_00365026314.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06986

  6%|▌         | 29/500 [00:09<02:23,  3.28it/s]

🎧 cof_00610_00425695236.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05868

  6%|▌         | 30/500 [00:09<02:11,  3.56it/s]

🎧 cof_00610_00444664843.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05111

  6%|▋         | 32/500 [00:10<01:52,  4.16it/s]

🎧 cof_00610_00453007773.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05749
🎧 cof_00610_00478945971.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.06272

  7%|▋         | 33/500 [00:10<01:46,  4.39it/s]

🎧 cof_00610_00509877285.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06339

  7%|▋         | 34/500 [00:10<01:48,  4.30it/s]

🎧 cof_00610_00543400472.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06813

  7%|▋         | 35/500 [00:11<01:45,  4.40it/s]

🎧 cof_00610_00551983037.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06307

  7%|▋         | 36/500 [00:11<01:43,  4.49it/s]

🎧 cof_00610_00558869711.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04996

  7%|▋         | 37/500 [00:11<01:44,  4.45it/s]

🎧 cof_00610_00561353575.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07100

  8%|▊         | 38/500 [00:11<01:41,  4.56it/s]

🎧 cof_00610_00564437297.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05611

  8%|▊         | 39/500 [00:11<01:42,  4.50it/s]

🎧 cof_00610_00565615554.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06998

  8%|▊         | 40/500 [00:12<01:41,  4.55it/s]

🎧 cof_00610_00575817433.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06494

  8%|▊         | 41/500 [00:12<01:40,  4.57it/s]

🎧 cof_00610_00578771534.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07604

  8%|▊         | 42/500 [00:12<01:38,  4.65it/s]

🎧 cof_00610_00581998607.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06899

  9%|▉         | 44/500 [00:12<01:36,  4.70it/s]

🎧 cof_00610_00596208225.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06197
🎧 cof_00610_00618725454.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05800

  9%|▉         | 45/500 [00:13<01:40,  4.54it/s]

🎧 cof_00610_00648896188.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06938

  9%|▉         | 46/500 [00:13<01:41,  4.47it/s]

🎧 cof_00610_00655967363.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08300

  9%|▉         | 47/500 [00:13<01:38,  4.58it/s]

🎧 cof_00610_00657388450.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07681

 10%|▉         | 48/500 [00:13<01:40,  4.52it/s]

🎧 cof_00610_00683936383.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.05931

 10%|▉         | 49/500 [00:14<01:39,  4.55it/s]

🎧 cof_00610_00686388841.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05593

 10%|█         | 50/500 [00:14<01:40,  4.47it/s]

🎧 cof_00610_00749562938.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05424

 10%|█         | 51/500 [00:14<01:41,  4.42it/s]

🎧 cof_00610_00756082844.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07116

 10%|█         | 52/500 [00:14<01:38,  4.56it/s]

🎧 cof_00610_00797573887.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.07539

 11%|█         | 53/500 [00:14<01:39,  4.50it/s]

🎧 cof_00610_00798094083.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08160

 11%|█         | 54/500 [00:15<01:38,  4.54it/s]

🎧 cof_00610_00814799448.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06853

 11%|█         | 55/500 [00:15<01:41,  4.37it/s]

🎧 cof_00610_00845653420.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05957

 11%|█         | 56/500 [00:15<01:41,  4.38it/s]

🎧 cof_00610_00864540466.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07823

 11%|█▏        | 57/500 [00:15<01:38,  4.49it/s]

🎧 cof_00610_00913180829.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04958

 12%|█▏        | 58/500 [00:16<01:40,  4.39it/s]

🎧 cof_00610_00915357402.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06947

 12%|█▏        | 59/500 [00:16<01:41,  4.36it/s]

🎧 cof_00610_00925397497.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07611

 12%|█▏        | 60/500 [00:16<01:44,  4.21it/s]

🎧 cof_00610_00933823839.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05694

 12%|█▏        | 61/500 [00:16<01:40,  4.36it/s]

🎧 cof_00610_00951906695.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.04748

 12%|█▏        | 62/500 [00:17<01:37,  4.47it/s]

🎧 cof_00610_00975952674.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09642

 13%|█▎        | 63/500 [00:17<01:37,  4.49it/s]

🎧 cof_00610_00987056120.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05372

 13%|█▎        | 64/500 [00:17<01:36,  4.50it/s]

🎧 cof_00610_00992162135.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08462

 13%|█▎        | 65/500 [00:17<01:38,  4.41it/s]

🎧 cof_00610_01005920270.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05675

 13%|█▎        | 66/500 [00:17<01:40,  4.30it/s]

🎧 cof_00610_01034785289.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06099

 13%|█▎        | 67/500 [00:18<01:39,  4.36it/s]

🎧 cof_00610_01067172216.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07104

 14%|█▎        | 68/500 [00:18<01:40,  4.29it/s]

🎧 cof_00610_01074699717.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06633

 14%|█▍        | 70/500 [00:18<01:35,  4.49it/s]

🎧 cof_00610_01103751793.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05031
🎧 cof_00610_01122218651.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05842

 14%|█▍        | 71/500 [00:19<01:33,  4.60it/s]

🎧 cof_00610_01164601276.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08751

 14%|█▍        | 72/500 [00:19<01:34,  4.52it/s]

🎧 cof_00610_01177279569.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06993
🎧 cof_00610_01182042214.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.04564

 15%|█▍        | 74/500 [00:19<01:43,  4.13it/s]

🎧 cof_00610_01184239327.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06579

 15%|█▌        | 75/500 [00:20<01:48,  3.92it/s]

🎧 cof_00610_01208560288.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.04496

 15%|█▌        | 76/500 [00:20<02:00,  3.53it/s]

🎧 cof_00610_01233565904.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04995

 15%|█▌        | 77/500 [00:20<02:11,  3.21it/s]

🎧 cof_00610_01233644280.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07278

 16%|█▌        | 78/500 [00:21<02:21,  2.98it/s]

🎧 cof_00610_01237212237.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08996

 16%|█▌        | 79/500 [00:21<02:22,  2.96it/s]

🎧 cof_00610_01239420315.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05721

 16%|█▌        | 80/500 [00:21<02:27,  2.85it/s]

🎧 cof_00610_01242559354.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05821

 16%|█▌        | 81/500 [00:22<02:19,  3.00it/s]

🎧 cof_00610_01307574255.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.06033

 16%|█▋        | 82/500 [00:22<02:11,  3.19it/s]

🎧 cof_00610_01332160527.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06603

 17%|█▋        | 83/500 [00:22<02:04,  3.36it/s]

🎧 cof_00610_01351577649.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.08386

 17%|█▋        | 84/500 [00:23<02:05,  3.30it/s]

🎧 cof_00610_01352413514.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07388

 17%|█▋        | 85/500 [00:23<02:15,  3.07it/s]

🎧 cof_00610_01365273195.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06176

 17%|█▋        | 86/500 [00:23<02:20,  2.94it/s]

🎧 cof_00610_01380840235.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.07533

 17%|█▋        | 87/500 [00:24<02:15,  3.04it/s]

🎧 cof_00610_01398673747.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06701

 18%|█▊        | 88/500 [00:24<02:17,  3.00it/s]

🎧 cof_00610_01405447042.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05562

 18%|█▊        | 89/500 [00:24<02:08,  3.20it/s]

🎧 cof_00610_01424711494.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05669

 18%|█▊        | 90/500 [00:24<01:55,  3.54it/s]

🎧 cof_00610_01482178433.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05931

 18%|█▊        | 92/500 [00:25<01:43,  3.96it/s]

🎧 cof_00610_01484692642.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06186
🎧 cof_00610_01517257410.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06430

 19%|█▊        | 93/500 [00:25<01:36,  4.20it/s]

🎧 cof_00610_01518372199.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05571

 19%|█▉        | 94/500 [00:25<01:33,  4.35it/s]

🎧 cof_00610_01519839020.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05362

 19%|█▉        | 95/500 [00:26<01:30,  4.46it/s]

🎧 cof_00610_01521699555.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06794

 19%|█▉        | 96/500 [00:26<01:33,  4.31it/s]

🎧 cof_00610_01522609796.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06971

 19%|█▉        | 97/500 [00:26<01:31,  4.38it/s]

🎧 cof_00610_01546685593.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06535

 20%|█▉        | 98/500 [00:26<01:30,  4.44it/s]

🎧 cof_00610_01554940080.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05960

 20%|█▉        | 99/500 [00:26<01:31,  4.39it/s]

🎧 cof_00610_01570108574.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.07332

 20%|██        | 100/500 [00:27<01:29,  4.48it/s]

🎧 cof_00610_01571881249.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.04014

 20%|██        | 101/500 [00:27<01:31,  4.34it/s]

🎧 cof_00610_01576373712.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.06294

 20%|██        | 102/500 [00:27<01:32,  4.28it/s]

🎧 cof_00610_01582670094.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06479

 21%|██        | 103/500 [00:27<01:31,  4.33it/s]

🎧 cof_00610_01584809148.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06952

 21%|██        | 104/500 [00:28<01:29,  4.45it/s]

🎧 cof_00610_01598240500.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06771

 21%|██        | 105/500 [00:28<01:32,  4.29it/s]

🎧 cof_00610_01606969510.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07689

 21%|██        | 106/500 [00:28<01:29,  4.41it/s]

🎧 cof_00610_01617668800.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07495

 21%|██▏       | 107/500 [00:28<01:28,  4.43it/s]

🎧 cof_00610_01623396263.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06106

 22%|██▏       | 108/500 [00:28<01:26,  4.53it/s]

🎧 cof_00610_01645580179.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.04981

 22%|██▏       | 109/500 [00:29<01:27,  4.49it/s]

🎧 cof_00610_01645880972.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05891

 22%|██▏       | 110/500 [00:29<01:31,  4.25it/s]

🎧 cof_00610_01647927814.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08364

 22%|██▏       | 112/500 [00:29<01:26,  4.49it/s]

🎧 cof_00610_01648707087.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06442
🎧 cof_00610_01668621239.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05250

 23%|██▎       | 114/500 [00:30<01:21,  4.72it/s]

🎧 cof_00610_01681854955.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06751
🎧 cof_00610_01682930940.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06364

 23%|██▎       | 115/500 [00:30<01:24,  4.56it/s]

🎧 cof_00610_01717132249.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06751

 23%|██▎       | 116/500 [00:30<01:25,  4.47it/s]

🎧 cof_00610_01719338902.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08059

 23%|██▎       | 117/500 [00:30<01:24,  4.55it/s]

🎧 cof_00610_01723843413.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07351

 24%|██▍       | 119/500 [00:31<01:20,  4.75it/s]

🎧 cof_00610_01752734013.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06412
🎧 cof_00610_01756388857.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.05649

 24%|██▍       | 120/500 [00:31<01:20,  4.69it/s]

🎧 cof_00610_01768560254.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.04259

 24%|██▍       | 121/500 [00:31<01:22,  4.57it/s]

🎧 cof_00610_01769855518.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.07839

 24%|██▍       | 122/500 [00:32<01:22,  4.56it/s]

🎧 cof_00610_01780031534.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07012

 25%|██▍       | 124/500 [00:32<01:18,  4.81it/s]

🎧 cof_00610_01803432611.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06624
🎧 cof_00610_01826783460.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06620

 25%|██▌       | 125/500 [00:32<01:25,  4.37it/s]

🎧 cof_00610_01846322269.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05967

 25%|██▌       | 127/500 [00:33<01:20,  4.64it/s]

🎧 cof_00610_01860410978.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04847
🎧 cof_00610_01868155543.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06098

 26%|██▌       | 129/500 [00:33<01:17,  4.76it/s]

🎧 cof_00610_01874786532.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06418
🎧 cof_00610_01883761886.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.06048

 26%|██▌       | 131/500 [00:33<01:17,  4.78it/s]

🎧 cof_00610_01894857059.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06932
🎧 cof_00610_01899727337.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07416

 26%|██▋       | 132/500 [00:34<01:17,  4.77it/s]

🎧 cof_00610_01936293184.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08498

 27%|██▋       | 133/500 [00:34<01:16,  4.79it/s]

🎧 cof_00610_01937154120.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07790

 27%|██▋       | 134/500 [00:34<01:16,  4.79it/s]

🎧 cof_00610_01944219898.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07365

 27%|██▋       | 135/500 [00:34<01:28,  4.14it/s]

🎧 cof_00610_01944700504.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06536

 27%|██▋       | 136/500 [00:35<01:33,  3.90it/s]

🎧 cof_00610_01954876898.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05297

 27%|██▋       | 137/500 [00:35<01:38,  3.69it/s]

🎧 cof_00610_01967418412.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07241

 28%|██▊       | 138/500 [00:35<01:48,  3.32it/s]

🎧 cof_00610_01968851760.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.04199

 28%|██▊       | 139/500 [00:36<01:54,  3.15it/s]

🎧 cof_00610_02003889010.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05159

 28%|██▊       | 140/500 [00:36<01:47,  3.36it/s]

🎧 cof_00610_02017713890.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.04450

 28%|██▊       | 141/500 [00:36<01:48,  3.31it/s]

🎧 cof_00610_02033040142.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07605

 28%|██▊       | 142/500 [00:37<01:50,  3.23it/s]

🎧 cof_00610_02048411062.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07169

 29%|██▊       | 143/500 [00:37<01:51,  3.20it/s]

🎧 cof_00610_02059838335.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05490

 29%|██▉       | 144/500 [00:37<01:55,  3.07it/s]

🎧 cof_00610_02073822283.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06971

 29%|██▉       | 145/500 [00:38<01:53,  3.13it/s]

🎧 cof_00610_02093562767.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.06908

 29%|██▉       | 146/500 [00:38<01:55,  3.07it/s]

🎧 cof_00610_02098390712.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05424

 29%|██▉       | 147/500 [00:38<02:01,  2.91it/s]

🎧 cof_00610_02102765533.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.07772

 30%|██▉       | 148/500 [00:39<02:01,  2.90it/s]

🎧 cof_00610_02103979940.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06511

 30%|██▉       | 149/500 [00:39<02:06,  2.77it/s]

🎧 cof_00610_02123351169.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.05916

 30%|███       | 150/500 [00:39<01:59,  2.94it/s]

🎧 cof_00610_02127196066.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06404

 30%|███       | 152/500 [00:40<01:35,  3.66it/s]

🎧 cof_01523_00010305704.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.05231
🎧 cof_01523_00010635776.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07279

 31%|███       | 153/500 [00:40<01:28,  3.92it/s]

🎧 cof_01523_00017388571.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07978

 31%|███       | 154/500 [00:40<01:25,  4.06it/s]

🎧 cof_01523_00017665659.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08688

 31%|███       | 155/500 [00:40<01:21,  4.25it/s]

🎧 cof_01523_00023703164.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07302

 31%|███       | 156/500 [00:41<01:22,  4.18it/s]

🎧 cof_01523_00060644011.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09954

 31%|███▏      | 157/500 [00:41<01:19,  4.30it/s]

🎧 cof_01523_00073415337.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08294

 32%|███▏      | 158/500 [00:41<01:19,  4.28it/s]

🎧 cof_01523_00077386398.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05426

 32%|███▏      | 159/500 [00:41<01:17,  4.39it/s]

🎧 cof_01523_00095432224.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07610

 32%|███▏      | 160/500 [00:42<01:17,  4.39it/s]

🎧 cof_01523_00099138940.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06155

 32%|███▏      | 161/500 [00:42<01:20,  4.21it/s]

🎧 cof_01523_00108474815.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08075

 32%|███▏      | 162/500 [00:42<01:18,  4.32it/s]

🎧 cof_01523_00115400143.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07483

 33%|███▎      | 163/500 [00:42<01:19,  4.23it/s]

🎧 cof_01523_00124064108.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.04597

 33%|███▎      | 164/500 [00:43<01:19,  4.22it/s]

🎧 cof_01523_00137472745.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09059

 33%|███▎      | 165/500 [00:43<01:19,  4.21it/s]

🎧 cof_01523_00159959737.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06879

 33%|███▎      | 166/500 [00:43<01:20,  4.16it/s]

🎧 cof_01523_00162566952.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05058

 33%|███▎      | 167/500 [00:43<01:18,  4.22it/s]

🎧 cof_01523_00176362672.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09919

 34%|███▎      | 168/500 [00:43<01:15,  4.40it/s]

🎧 cof_01523_00241535803.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08122

 34%|███▍      | 169/500 [00:44<01:17,  4.27it/s]

🎧 cof_01523_00263223799.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04462

 34%|███▍      | 170/500 [00:44<01:20,  4.10it/s]

🎧 cof_01523_00272438245.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08098

 34%|███▍      | 171/500 [00:44<01:19,  4.14it/s]

🎧 cof_01523_00280869759.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05440

 34%|███▍      | 172/500 [00:44<01:17,  4.22it/s]

🎧 cof_01523_00286325544.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.06110

 35%|███▍      | 173/500 [00:45<01:14,  4.37it/s]

🎧 cof_01523_00287301417.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05538

 35%|███▍      | 174/500 [00:45<01:17,  4.21it/s]

🎧 cof_01523_00295602931.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05426

 35%|███▌      | 175/500 [00:45<01:16,  4.27it/s]

🎧 cof_01523_00300070090.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05858

 35%|███▌      | 176/500 [00:45<01:15,  4.27it/s]

🎧 cof_01523_00310910177.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06146

 35%|███▌      | 177/500 [00:46<01:15,  4.26it/s]

🎧 cof_01523_00324308563.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05564

 36%|███▌      | 178/500 [00:46<01:16,  4.23it/s]

🎧 cof_01523_00330363745.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.04699

 36%|███▌      | 179/500 [00:46<01:13,  4.35it/s]

🎧 cof_01523_00354041865.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09095

 36%|███▌      | 180/500 [00:46<01:13,  4.33it/s]

🎧 cof_01523_00364204205.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08356

 36%|███▌      | 181/500 [00:47<01:12,  4.42it/s]

🎧 cof_01523_00368573129.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.08646

 36%|███▋      | 182/500 [00:47<01:10,  4.51it/s]

🎧 cof_01523_00395423042.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.06581

 37%|███▋      | 183/500 [00:47<01:11,  4.46it/s]

🎧 cof_01523_00405514326.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06523

 37%|███▋      | 184/500 [00:47<01:10,  4.48it/s]

🎧 cof_01523_00419335523.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09034

 37%|███▋      | 185/500 [00:47<01:09,  4.54it/s]

🎧 cof_01523_00450174156.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06912

 37%|███▋      | 186/500 [00:48<01:08,  4.56it/s]

🎧 cof_01523_00473319817.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09675

 37%|███▋      | 187/500 [00:48<01:08,  4.57it/s]

🎧 cof_01523_00491195227.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06027

 38%|███▊      | 188/500 [00:48<01:12,  4.29it/s]

🎧 cof_01523_00529809810.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06839

 38%|███▊      | 189/500 [00:48<01:12,  4.28it/s]

🎧 cof_01523_00547503265.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07370

 38%|███▊      | 190/500 [00:49<01:14,  4.18it/s]

🎧 cof_01523_00549525543.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06039

 38%|███▊      | 191/500 [00:49<01:13,  4.21it/s]

🎧 cof_01523_00552427428.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04308

 38%|███▊      | 192/500 [00:49<01:13,  4.19it/s]

🎧 cof_01523_00555239207.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05044

 39%|███▊      | 193/500 [00:49<01:10,  4.34it/s]

🎧 cof_01523_00604591271.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07657

 39%|███▉      | 194/500 [00:50<01:11,  4.28it/s]

🎧 cof_01523_00611778179.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08339

 39%|███▉      | 195/500 [00:50<01:22,  3.71it/s]

🎧 cof_01523_00656220672.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08967

 39%|███▉      | 196/500 [00:50<01:34,  3.23it/s]

🎧 cof_01523_00673024470.wav
   - Features extraídas: 575
   - Tempo: 208.33
   - RMSE manual: 0.08419

 39%|███▉      | 197/500 [00:51<01:40,  3.03it/s]

🎧 cof_01523_00683660831.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08966

 40%|███▉      | 198/500 [00:51<01:45,  2.87it/s]

🎧 cof_01523_00715472611.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05684

 40%|███▉      | 199/500 [00:51<01:47,  2.79it/s]

🎧 cof_01523_00727366429.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.04491

 40%|████      | 200/500 [00:52<01:48,  2.75it/s]

🎧 cof_01523_00738701733.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06014

 40%|████      | 201/500 [00:52<01:44,  2.86it/s]

🎧 cof_01523_00742968789.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08101

 40%|████      | 202/500 [00:53<01:46,  2.80it/s]

🎧 cof_01523_00760114671.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.07507

 41%|████      | 203/500 [00:53<01:48,  2.74it/s]

🎧 cof_01523_00794097613.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09364

 41%|████      | 204/500 [00:53<01:49,  2.69it/s]

🎧 cof_01523_00795632842.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09740

 41%|████      | 205/500 [00:54<01:48,  2.71it/s]

🎧 cof_01523_00796365902.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08561

 41%|████      | 206/500 [00:54<01:51,  2.65it/s]

🎧 cof_01523_00800980650.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07773

 41%|████▏     | 207/500 [00:54<01:45,  2.79it/s]

🎧 cof_01523_00803058134.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06108

 42%|████▏     | 208/500 [00:55<01:46,  2.74it/s]

🎧 cof_01523_00813531077.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04577

 42%|████▏     | 209/500 [00:55<02:01,  2.39it/s]

🎧 cof_01523_00872061424.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.04881

 42%|████▏     | 210/500 [00:56<01:46,  2.71it/s]

🎧 cof_01523_00901336745.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09041

 42%|████▏     | 211/500 [00:56<02:07,  2.26it/s]

🎧 cof_01523_00910432729.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04688

 42%|████▏     | 212/500 [00:56<01:55,  2.49it/s]

🎧 cof_01523_00937961208.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.04390

 43%|████▎     | 213/500 [00:57<01:43,  2.79it/s]

🎧 cof_01523_00950688215.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.04778

 43%|████▎     | 214/500 [00:57<01:30,  3.17it/s]

🎧 cof_01523_00953609331.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05150

 43%|████▎     | 215/500 [00:57<01:21,  3.48it/s]

🎧 cof_01523_00960018686.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07723

 43%|████▎     | 216/500 [00:57<01:16,  3.73it/s]

🎧 cof_01523_00966521868.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06977

 43%|████▎     | 217/500 [00:58<01:12,  3.88it/s]

🎧 cof_01523_01007796511.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04695

 44%|████▎     | 218/500 [00:58<01:10,  3.97it/s]

🎧 cof_01523_01011132563.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.03663

 44%|████▍     | 219/500 [00:58<01:07,  4.16it/s]

🎧 cof_01523_01018200339.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05660

 44%|████▍     | 220/500 [00:58<01:07,  4.16it/s]

🎧 cof_01523_01029115021.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06817

 44%|████▍     | 221/500 [00:59<01:06,  4.21it/s]

🎧 cof_01523_01047300428.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05480

 44%|████▍     | 222/500 [00:59<01:05,  4.21it/s]

🎧 cof_01523_01054426342.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.05166

 45%|████▍     | 223/500 [00:59<01:05,  4.22it/s]

🎧 cof_01523_01064275630.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05700

 45%|████▍     | 224/500 [00:59<01:05,  4.20it/s]

🎧 cof_01523_01066959942.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05244

 45%|████▌     | 225/500 [00:59<01:03,  4.33it/s]

🎧 cof_01523_01133182583.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08146

 45%|████▌     | 226/500 [01:00<01:03,  4.34it/s]

🎧 cof_01523_01157644137.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08093

 45%|████▌     | 227/500 [01:00<01:04,  4.25it/s]

🎧 cof_01523_01168718366.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08988

 46%|████▌     | 228/500 [01:00<01:05,  4.18it/s]

🎧 cof_01523_01185002519.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06274

 46%|████▌     | 229/500 [01:00<01:01,  4.38it/s]

🎧 cof_01523_01192631468.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06877

 46%|████▌     | 230/500 [01:01<01:02,  4.32it/s]

🎧 cof_01523_01199131701.wav
   - Features extraídas: 575
   - Tempo: 208.33
   - RMSE manual: 0.03951

 46%|████▌     | 231/500 [01:01<01:02,  4.30it/s]

🎧 cof_01523_01199785560.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04903

 46%|████▋     | 232/500 [01:01<01:01,  4.36it/s]

🎧 cof_01523_01213923060.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08070

 47%|████▋     | 233/500 [01:01<01:02,  4.30it/s]

🎧 cof_01523_01214594801.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.05460

 47%|████▋     | 234/500 [01:02<01:00,  4.38it/s]

🎧 cof_01523_01245766736.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.04980

 47%|████▋     | 235/500 [01:02<01:00,  4.38it/s]

🎧 cof_01523_01247517654.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05021

 47%|████▋     | 236/500 [01:02<00:59,  4.45it/s]

🎧 cof_01523_01257141592.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07453

 47%|████▋     | 237/500 [01:02<01:00,  4.36it/s]

🎧 cof_01523_01257820936.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05268

 48%|████▊     | 238/500 [01:02<01:01,  4.27it/s]

🎧 cof_01523_01258689091.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07174

 48%|████▊     | 239/500 [01:03<01:00,  4.34it/s]

🎧 cof_01523_01261517830.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05589

 48%|████▊     | 240/500 [01:03<01:02,  4.15it/s]

🎧 cof_01523_01297047509.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05278

 48%|████▊     | 241/500 [01:03<01:00,  4.26it/s]

🎧 cof_01523_01318664847.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09081

 48%|████▊     | 242/500 [01:03<01:02,  4.15it/s]

🎧 cof_01523_01344889362.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.04158

 49%|████▊     | 243/500 [01:04<01:02,  4.09it/s]

🎧 cof_01523_01420951365.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08314

 49%|████▉     | 244/500 [01:04<01:00,  4.22it/s]

🎧 cof_01523_01421442232.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08793

 49%|████▉     | 245/500 [01:04<01:00,  4.24it/s]

🎧 cof_01523_01427683010.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06305

 49%|████▉     | 246/500 [01:04<01:00,  4.21it/s]

🎧 cof_01523_01430571518.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08796

 49%|████▉     | 247/500 [01:05<01:04,  3.91it/s]

🎧 cof_01523_01441635786.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.08701

 50%|████▉     | 248/500 [01:05<01:15,  3.34it/s]

🎧 cof_01523_01445950580.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07052

 50%|████▉     | 249/500 [01:05<01:14,  3.38it/s]

🎧 cof_01523_01446676618.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07391

 50%|█████     | 250/500 [01:06<01:19,  3.16it/s]

🎧 cof_01523_01463442812.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.06002

 50%|█████     | 251/500 [01:06<01:16,  3.24it/s]

🎧 com_00610_00008909944.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09975

 50%|█████     | 252/500 [01:06<01:21,  3.05it/s]

🎧 com_00610_00031576593.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.09038

 51%|█████     | 253/500 [01:07<01:19,  3.11it/s]

🎧 com_00610_00033748372.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.11061

 51%|█████     | 254/500 [01:07<01:20,  3.04it/s]

🎧 com_00610_00038696950.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.08703

 51%|█████     | 255/500 [01:07<01:26,  2.83it/s]

🎧 com_00610_00075952240.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09333

 51%|█████     | 256/500 [01:08<01:26,  2.84it/s]

🎧 com_00610_00084211564.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07137

 51%|█████▏    | 257/500 [01:08<01:24,  2.87it/s]

🎧 com_00610_00091167688.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07990

 52%|█████▏    | 258/500 [01:09<01:30,  2.68it/s]

🎧 com_00610_00113450014.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09605

 52%|█████▏    | 259/500 [01:09<01:26,  2.79it/s]

🎧 com_00610_00116192883.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09131

 52%|█████▏    | 260/500 [01:09<01:23,  2.88it/s]

🎧 com_00610_00117251706.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08449

 52%|█████▏    | 261/500 [01:10<01:22,  2.89it/s]

🎧 com_00610_00151605914.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10167

 52%|█████▏    | 262/500 [01:10<01:13,  3.25it/s]

🎧 com_00610_00188346532.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07840

 53%|█████▎    | 263/500 [01:10<01:07,  3.52it/s]

🎧 com_00610_00203701336.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09113

 53%|█████▎    | 264/500 [01:10<01:01,  3.83it/s]

🎧 com_00610_00222418092.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.13546

 53%|█████▎    | 265/500 [01:10<01:01,  3.81it/s]

🎧 com_00610_00235065361.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08277

 53%|█████▎    | 266/500 [01:11<00:58,  3.97it/s]

🎧 com_00610_00256578637.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08357

 53%|█████▎    | 267/500 [01:11<00:56,  4.14it/s]

🎧 com_00610_00259350907.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06524

 54%|█████▎    | 268/500 [01:11<00:53,  4.30it/s]

🎧 com_00610_00269776593.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14898

 54%|█████▍    | 269/500 [01:11<00:52,  4.39it/s]

🎧 com_00610_00271996006.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10401

 54%|█████▍    | 270/500 [01:12<00:55,  4.14it/s]

🎧 com_00610_00277968440.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.10390

 54%|█████▍    | 271/500 [01:12<00:54,  4.17it/s]

🎧 com_00610_00286786215.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04952

 54%|█████▍    | 272/500 [01:12<00:52,  4.31it/s]

🎧 com_00610_00289799881.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.07082

 55%|█████▍    | 273/500 [01:12<00:52,  4.36it/s]

🎧 com_00610_00307450954.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.08023

 55%|█████▍    | 274/500 [01:13<00:51,  4.36it/s]

🎧 com_00610_00355989030.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06923

 55%|█████▌    | 276/500 [01:13<00:49,  4.53it/s]

🎧 com_00610_00374570514.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.08271
🎧 com_00610_00374777459.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.07657

 55%|█████▌    | 277/500 [01:13<00:48,  4.58it/s]

🎧 com_00610_00384800145.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09755
🎧 com_00610_00400726428.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08634

 56%|█████▌    | 279/500 [01:14<00:48,  4.56it/s]

🎧 com_00610_00419273526.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07788

 56%|█████▌    | 280/500 [01:14<00:48,  4.58it/s]

🎧 com_00610_00428468193.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10448

 56%|█████▌    | 281/500 [01:14<00:48,  4.56it/s]

🎧 com_00610_00431285037.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.13020

 57%|█████▋    | 283/500 [01:14<00:47,  4.60it/s]

🎧 com_00610_00444288482.wav
   - Features extraídas: 575
   - Tempo: 81.52
   - RMSE manual: 0.06865
🎧 com_00610_00447984716.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09242

 57%|█████▋    | 285/500 [01:15<00:45,  4.68it/s]

🎧 com_00610_00455070357.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11351
🎧 com_00610_00457873809.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09400

 57%|█████▋    | 286/500 [01:15<00:45,  4.69it/s]

🎧 com_00610_00475485048.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.07896

 57%|█████▋    | 287/500 [01:15<00:45,  4.66it/s]

🎧 com_00610_00478019235.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.08402

 58%|█████▊    | 288/500 [01:16<00:45,  4.62it/s]

🎧 com_00610_00484202440.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10800

 58%|█████▊    | 289/500 [01:16<00:46,  4.50it/s]

🎧 com_00610_00486129050.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.11336

 58%|█████▊    | 290/500 [01:16<00:46,  4.54it/s]

🎧 com_00610_00490233140.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09010

 58%|█████▊    | 292/500 [01:16<00:43,  4.74it/s]

🎧 com_00610_00499134948.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07840
🎧 com_00610_00510820719.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.07658

 59%|█████▊    | 293/500 [01:17<00:44,  4.60it/s]

🎧 com_00610_00522401521.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07504

 59%|█████▉    | 294/500 [01:17<00:45,  4.55it/s]

🎧 com_00610_00535719087.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.06480

 59%|█████▉    | 296/500 [01:17<00:44,  4.54it/s]

🎧 com_00610_00540066680.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08548
🎧 com_00610_00583668414.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07565

 59%|█████▉    | 297/500 [01:18<00:45,  4.49it/s]

🎧 com_00610_00587260496.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09555

 60%|█████▉    | 298/500 [01:18<00:45,  4.41it/s]

🎧 com_00610_00611753776.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09556

 60%|█████▉    | 299/500 [01:18<00:48,  4.16it/s]

🎧 com_00610_00624270481.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09758

 60%|██████    | 300/500 [01:18<00:47,  4.22it/s]

🎧 com_00610_00680822802.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.12755

 60%|██████    | 301/500 [01:19<00:48,  4.10it/s]

🎧 com_00610_00684701583.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10237

 60%|██████    | 302/500 [01:19<00:46,  4.27it/s]

🎧 com_00610_00689174621.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13137

 61%|██████    | 303/500 [01:19<00:46,  4.22it/s]

🎧 com_00610_00756110230.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06199

 61%|██████    | 304/500 [01:19<00:46,  4.24it/s]

🎧 com_00610_00757633937.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.07264

 61%|██████    | 305/500 [01:19<00:46,  4.20it/s]

🎧 com_00610_00761631502.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09445

 61%|██████    | 306/500 [01:20<00:52,  3.70it/s]

🎧 com_00610_00782053262.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07057

 61%|██████▏   | 307/500 [01:20<00:58,  3.29it/s]

🎧 com_00610_00802253831.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.12314

 62%|██████▏   | 308/500 [01:21<00:58,  3.27it/s]

🎧 com_00610_00812301792.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09175

 62%|██████▏   | 309/500 [01:21<00:56,  3.39it/s]

🎧 com_00610_00816855072.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05220

 62%|██████▏   | 310/500 [01:21<00:55,  3.45it/s]

🎧 com_00610_00831455571.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.11819

 62%|██████▏   | 311/500 [01:21<00:57,  3.28it/s]

🎧 com_00610_00848224353.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07288

 62%|██████▏   | 312/500 [01:22<01:00,  3.10it/s]

🎧 com_00610_00861650446.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10761

 63%|██████▎   | 313/500 [01:22<00:59,  3.15it/s]

🎧 com_00610_00868776462.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08308

 63%|██████▎   | 314/500 [01:22<01:03,  2.91it/s]

🎧 com_00610_00907087676.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08779

 63%|██████▎   | 315/500 [01:23<01:04,  2.87it/s]

🎧 com_00610_00922028088.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.11101

 63%|██████▎   | 316/500 [01:23<01:08,  2.68it/s]

🎧 com_00610_00933250169.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.10088

 63%|██████▎   | 317/500 [01:24<01:04,  2.85it/s]

🎧 com_00610_00934577510.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09835

 64%|██████▎   | 318/500 [01:24<01:04,  2.81it/s]

🎧 com_00610_00944980201.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10589

 64%|██████▍   | 319/500 [01:24<01:03,  2.85it/s]

🎧 com_00610_00965877908.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09123

 64%|██████▍   | 320/500 [01:25<01:04,  2.79it/s]

🎧 com_00610_00972806335.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.04690

 64%|██████▍   | 321/500 [01:25<00:59,  3.02it/s]

🎧 com_00610_01017273046.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08794

 64%|██████▍   | 322/500 [01:25<00:53,  3.32it/s]

🎧 com_00610_01037237895.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10876

 65%|██████▍   | 323/500 [01:25<00:49,  3.56it/s]

🎧 com_00610_01041502986.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09890

 65%|██████▍   | 324/500 [01:26<00:47,  3.69it/s]

🎧 com_00610_01056955720.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05383

 65%|██████▌   | 325/500 [01:26<00:45,  3.89it/s]

🎧 com_00610_01067797138.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.11544

 65%|██████▌   | 326/500 [01:26<00:43,  4.03it/s]

🎧 com_00610_01079841693.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08066

 65%|██████▌   | 327/500 [01:26<00:42,  4.12it/s]

🎧 com_00610_01126869142.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09898

 66%|██████▌   | 328/500 [01:27<00:43,  3.93it/s]

🎧 com_00610_01133611136.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.08656

 66%|██████▌   | 329/500 [01:27<00:41,  4.13it/s]

🎧 com_00610_01139260148.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08934

 66%|██████▌   | 330/500 [01:27<00:39,  4.32it/s]

🎧 com_00610_01141323103.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.06440
🎧 com_00610_01144918243.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.11950

 66%|██████▋   | 332/500 [01:27<00:39,  4.27it/s]

🎧 com_00610_01148784017.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.14704

 67%|██████▋   | 333/500 [01:28<00:37,  4.46it/s]

🎧 com_00610_01152760554.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07124

 67%|██████▋   | 334/500 [01:28<00:37,  4.38it/s]

🎧 com_00610_01156712965.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09432
🎧 com_00610_01226934508.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09799

 67%|██████▋   | 336/500 [01:28<00:35,  4.65it/s]

🎧 com_00610_01229503605.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09087

 67%|██████▋   | 337/500 [01:29<00:36,  4.48it/s]

🎧 com_00610_01236993729.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07869

 68%|██████▊   | 338/500 [01:29<00:35,  4.54it/s]

🎧 com_00610_01242095809.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09055

 68%|██████▊   | 339/500 [01:29<00:35,  4.55it/s]

🎧 com_00610_01332319294.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11601

 68%|██████▊   | 340/500 [01:29<00:35,  4.50it/s]

🎧 com_00610_01345253353.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10130

 68%|██████▊   | 341/500 [01:29<00:36,  4.33it/s]

🎧 com_00610_01347530709.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08677

 68%|██████▊   | 342/500 [01:30<00:35,  4.41it/s]

🎧 com_00610_01356460222.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11499

 69%|██████▊   | 343/500 [01:30<00:36,  4.25it/s]

🎧 com_00610_01357734740.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10064

 69%|██████▉   | 344/500 [01:30<00:36,  4.27it/s]

🎧 com_00610_01399950713.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.15536

 69%|██████▉   | 345/500 [01:30<00:36,  4.28it/s]

🎧 com_00610_01412052726.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.04375

 69%|██████▉   | 347/500 [01:31<00:33,  4.57it/s]

🎧 com_00610_01427091610.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10319
🎧 com_00610_01431511605.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10795

 70%|██████▉   | 348/500 [01:31<00:34,  4.47it/s]

🎧 com_00610_01436828203.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09910

 70%|██████▉   | 349/500 [01:31<00:34,  4.44it/s]

🎧 com_00610_01439716755.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08963

 70%|███████   | 350/500 [01:32<00:34,  4.38it/s]

🎧 com_00610_01448106783.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.10334

 70%|███████   | 351/500 [01:32<00:34,  4.27it/s]

🎧 com_00610_01472433204.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09137

 70%|███████   | 352/500 [01:32<00:34,  4.29it/s]

🎧 com_00610_01485382013.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.07123

 71%|███████   | 353/500 [01:32<00:34,  4.29it/s]

🎧 com_00610_01503834738.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08898

 71%|███████   | 354/500 [01:32<00:33,  4.39it/s]

🎧 com_00610_01550783796.wav
   - Features extraídas: 575
   - Tempo: 78.12
   - RMSE manual: 0.09054

 71%|███████   | 355/500 [01:33<00:33,  4.35it/s]

🎧 com_00610_01574517929.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08147
🎧 com_00610_01623387216.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08309

 71%|███████▏  | 357/500 [01:33<00:31,  4.49it/s]

🎧 com_00610_01637422178.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07745

 72%|███████▏  | 358/500 [01:33<00:31,  4.58it/s]

🎧 com_00610_01638128865.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06681

 72%|███████▏  | 359/500 [01:34<00:30,  4.59it/s]

🎧 com_00610_01653012835.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09432

 72%|███████▏  | 360/500 [01:34<00:31,  4.46it/s]

🎧 com_00610_01661261400.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.19508

 72%|███████▏  | 361/500 [01:34<00:31,  4.40it/s]

🎧 com_00610_01674463222.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08889

 72%|███████▏  | 362/500 [01:34<00:31,  4.40it/s]

🎧 com_00610_01676103003.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11354

 73%|███████▎  | 364/500 [01:35<00:29,  4.57it/s]

🎧 com_00610_01691646053.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09148
🎧 com_00610_01706691030.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10172

 73%|███████▎  | 365/500 [01:35<00:34,  3.88it/s]

🎧 com_00610_01708458585.wav
   - Features extraídas: 575
   - Tempo: 208.33
   - RMSE manual: 0.10612

 73%|███████▎  | 366/500 [01:35<00:38,  3.50it/s]

🎧 com_00610_01711378856.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12330

 73%|███████▎  | 367/500 [01:36<00:41,  3.21it/s]

🎧 com_00610_01722982924.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08762

 74%|███████▎  | 368/500 [01:36<00:44,  3.00it/s]

🎧 com_00610_01744944249.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08300

 74%|███████▍  | 369/500 [01:36<00:44,  2.96it/s]

🎧 com_00610_01752347442.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09045

 74%|███████▍  | 370/500 [01:37<00:44,  2.93it/s]

🎧 com_00610_01752542331.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08279

 74%|███████▍  | 371/500 [01:37<00:43,  3.00it/s]

🎧 com_00610_01753570408.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08076

 74%|███████▍  | 372/500 [01:37<00:41,  3.07it/s]

🎧 com_00610_01757298897.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10611

 75%|███████▍  | 373/500 [01:38<00:42,  3.00it/s]

🎧 com_00610_01774275355.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.08780

 75%|███████▍  | 374/500 [01:38<00:44,  2.81it/s]

🎧 com_00610_01775757383.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09771

 75%|███████▌  | 375/500 [01:39<00:45,  2.74it/s]

🎧 com_00610_01790043462.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09544

 75%|███████▌  | 376/500 [01:39<00:44,  2.77it/s]

🎧 com_00610_01801581674.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08825

 75%|███████▌  | 377/500 [01:39<00:43,  2.80it/s]

🎧 com_00610_01819201422.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.12932

 76%|███████▌  | 378/500 [01:40<00:44,  2.71it/s]

🎧 com_00610_01828072638.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.07459

 76%|███████▌  | 379/500 [01:40<00:41,  2.92it/s]

🎧 com_00610_01854164402.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06072

 76%|███████▌  | 380/500 [01:40<00:37,  3.24it/s]

🎧 com_00610_01870400951.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09824

 76%|███████▌  | 381/500 [01:40<00:34,  3.41it/s]

🎧 com_00610_01875567670.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08905

 76%|███████▋  | 382/500 [01:41<00:31,  3.69it/s]

🎧 com_00610_01889054402.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.08802
🎧 com_00610_01899213381.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.15011

 77%|███████▋  | 385/500 [01:41<00:25,  4.43it/s]

🎧 com_00610_01907115357.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.11159
🎧 com_00610_01914562022.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.07578

 77%|███████▋  | 386/500 [01:42<00:26,  4.37it/s]

🎧 com_00610_01931248306.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08390

 77%|███████▋  | 387/500 [01:42<00:25,  4.47it/s]

🎧 com_00610_01936334927.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.11339

 78%|███████▊  | 388/500 [01:42<00:25,  4.35it/s]

🎧 com_00610_01941442448.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10551

 78%|███████▊  | 389/500 [01:42<00:25,  4.40it/s]

🎧 com_00610_01947011444.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.15457

 78%|███████▊  | 390/500 [01:42<00:24,  4.42it/s]

🎧 com_00610_01948541751.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11545

 78%|███████▊  | 391/500 [01:43<00:24,  4.48it/s]

🎧 com_00610_01954361962.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11018

 78%|███████▊  | 392/500 [01:43<00:23,  4.54it/s]

🎧 com_00610_01987193675.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09669

 79%|███████▊  | 393/500 [01:43<00:23,  4.57it/s]

🎧 com_00610_02054233665.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09467

 79%|███████▉  | 394/500 [01:43<00:23,  4.58it/s]

🎧 com_00610_02063882340.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.12795

 79%|███████▉  | 396/500 [01:44<00:23,  4.44it/s]

🎧 com_00610_02068255395.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10131
🎧 com_00610_02068399170.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11060

 79%|███████▉  | 397/500 [01:44<00:23,  4.47it/s]

🎧 com_00610_02106534667.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08912

 80%|███████▉  | 398/500 [01:44<00:22,  4.54it/s]

🎧 com_00610_02108585319.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09339

 80%|███████▉  | 399/500 [01:44<00:23,  4.34it/s]

🎧 com_00610_02138036045.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10164

 80%|████████  | 400/500 [01:45<00:23,  4.30it/s]

🎧 com_01523_00006065716.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09481

 80%|████████  | 401/500 [01:45<00:22,  4.40it/s]

🎧 com_01523_00010884441.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09574

 80%|████████  | 402/500 [01:45<00:22,  4.39it/s]

🎧 com_01523_00023325432.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08627

 81%|████████  | 403/500 [01:45<00:21,  4.41it/s]

🎧 com_01523_00023844062.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06977

 81%|████████  | 404/500 [01:46<00:22,  4.22it/s]

🎧 com_01523_00025978128.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08515

 81%|████████  | 406/500 [01:46<00:20,  4.54it/s]

🎧 com_01523_00040109759.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09230
🎧 com_01523_00045120750.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07067

 81%|████████▏ | 407/500 [01:46<00:20,  4.45it/s]

🎧 com_01523_00063393208.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08057

 82%|████████▏ | 408/500 [01:46<00:20,  4.51it/s]

🎧 com_01523_00063947279.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08664

 82%|████████▏ | 409/500 [01:47<00:21,  4.32it/s]

🎧 com_01523_00091488164.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08216

 82%|████████▏ | 410/500 [01:47<00:20,  4.39it/s]

🎧 com_01523_00117364064.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07923

 82%|████████▏ | 411/500 [01:47<00:19,  4.47it/s]

🎧 com_01523_00130328425.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08570

 82%|████████▏ | 412/500 [01:47<00:19,  4.52it/s]

🎧 com_01523_00139590753.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.07624

 83%|████████▎ | 413/500 [01:48<00:19,  4.51it/s]

🎧 com_01523_00168344357.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09446

 83%|████████▎ | 414/500 [01:48<00:19,  4.37it/s]

🎧 com_01523_00188509935.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10000

 83%|████████▎ | 415/500 [01:48<00:18,  4.48it/s]

🎧 com_01523_00188955970.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10371

 83%|████████▎ | 416/500 [01:48<00:18,  4.52it/s]

🎧 com_01523_00217869236.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07539

 83%|████████▎ | 417/500 [01:48<00:18,  4.58it/s]

🎧 com_01523_00220322993.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07455

 84%|████████▎ | 418/500 [01:49<00:18,  4.53it/s]

🎧 com_01523_00224898495.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.08537

 84%|████████▍ | 420/500 [01:49<00:17,  4.66it/s]

🎧 com_01523_00227092349.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09214
🎧 com_01523_00261301491.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09591

 84%|████████▍ | 421/500 [01:49<00:16,  4.68it/s]

🎧 com_01523_00271864966.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07880

 84%|████████▍ | 422/500 [01:50<00:16,  4.67it/s]

🎧 com_01523_00313372747.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08661

 85%|████████▍ | 423/500 [01:50<00:17,  4.51it/s]

🎧 com_01523_00314453562.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09130

 85%|████████▍ | 424/500 [01:50<00:19,  3.94it/s]

🎧 com_01523_00315309957.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09113

 85%|████████▌ | 425/500 [01:50<00:21,  3.53it/s]

🎧 com_01523_00322091798.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.11157

 85%|████████▌ | 426/500 [01:51<00:21,  3.42it/s]

🎧 com_01523_00322337364.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08040

 85%|████████▌ | 427/500 [01:51<00:22,  3.23it/s]

🎧 com_01523_00354247578.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10894

 86%|████████▌ | 428/500 [01:52<00:23,  3.06it/s]

🎧 com_01523_00377642703.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10263

 86%|████████▌ | 429/500 [01:52<00:24,  2.92it/s]

🎧 com_01523_00389808905.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09330

 86%|████████▌ | 430/500 [01:52<00:24,  2.91it/s]

🎧 com_01523_00410298204.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08930

 86%|████████▌ | 431/500 [01:53<00:24,  2.79it/s]

🎧 com_01523_00418027812.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07174

 86%|████████▋ | 432/500 [01:53<00:23,  2.89it/s]

🎧 com_01523_00434836794.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07483

 87%|████████▋ | 433/500 [01:53<00:23,  2.85it/s]

🎧 com_01523_00436288230.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08654

 87%|████████▋ | 434/500 [01:54<00:24,  2.74it/s]

🎧 com_01523_00461019966.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11553

 87%|████████▋ | 435/500 [01:54<00:22,  2.87it/s]

🎧 com_01523_00483493677.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10895

 87%|████████▋ | 436/500 [01:54<00:22,  2.86it/s]

🎧 com_01523_00500128089.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10677

 87%|████████▋ | 437/500 [01:55<00:22,  2.82it/s]

🎧 com_01523_00503563372.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08645

 88%|████████▊ | 438/500 [01:55<00:20,  3.00it/s]

🎧 com_01523_00513535788.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.10762

 88%|████████▊ | 439/500 [01:55<00:18,  3.23it/s]

🎧 com_01523_00517650276.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08163

 88%|████████▊ | 440/500 [01:56<00:17,  3.51it/s]

🎧 com_01523_00526521550.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09865

 88%|████████▊ | 441/500 [01:56<00:15,  3.76it/s]

🎧 com_01523_00546055786.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07280

 88%|████████▊ | 442/500 [01:56<00:14,  3.97it/s]

🎧 com_01523_00570931502.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07730

 89%|████████▊ | 443/500 [01:56<00:14,  4.04it/s]

🎧 com_01523_00579025369.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07547

 89%|████████▉ | 444/500 [01:56<00:13,  4.02it/s]

🎧 com_01523_00587725549.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08991

 89%|████████▉ | 445/500 [01:57<00:13,  4.05it/s]

🎧 com_01523_00587907853.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08791

 89%|████████▉ | 446/500 [01:57<00:12,  4.22it/s]

🎧 com_01523_00599170693.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08591

 89%|████████▉ | 447/500 [01:57<00:12,  4.30it/s]

🎧 com_01523_00608479921.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08698

 90%|████████▉ | 448/500 [01:57<00:12,  4.20it/s]

🎧 com_01523_00631006665.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08774

 90%|████████▉ | 449/500 [01:58<00:12,  4.22it/s]

🎧 com_01523_00631563696.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09866

 90%|█████████ | 450/500 [01:58<00:12,  4.15it/s]

🎧 com_01523_00653269687.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09286

 90%|█████████ | 451/500 [01:58<00:11,  4.25it/s]

🎧 com_01523_00660716568.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08952

 90%|█████████ | 452/500 [01:58<00:11,  4.12it/s]

🎧 com_01523_00673089408.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09172

 91%|█████████ | 454/500 [01:59<00:10,  4.45it/s]

🎧 com_01523_00673282088.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09379
🎧 com_01523_00685957576.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11152

 91%|█████████ | 455/500 [01:59<00:09,  4.53it/s]

🎧 com_01523_00700793916.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.08388
🎧 com_01523_00702264333.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.11135

 91%|█████████▏| 457/500 [01:59<00:09,  4.50it/s]

🎧 com_01523_00736757457.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09104

 92%|█████████▏| 458/500 [02:00<00:09,  4.54it/s]

🎧 com_01523_00756460053.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09465

 92%|█████████▏| 460/500 [02:00<00:08,  4.70it/s]

🎧 com_01523_00760381987.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09090
🎧 com_01523_00780716323.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07533

 92%|█████████▏| 461/500 [02:00<00:08,  4.75it/s]

🎧 com_01523_00796364014.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10524

 92%|█████████▏| 462/500 [02:00<00:08,  4.69it/s]

🎧 com_01523_00809141739.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08151

 93%|█████████▎| 464/500 [02:01<00:07,  4.75it/s]

🎧 com_01523_00819269643.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07615
🎧 com_01523_00822655651.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.08257

 93%|█████████▎| 466/500 [02:01<00:06,  4.91it/s]

🎧 com_01523_00832188467.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10125
🎧 com_01523_00833172649.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.08968

 93%|█████████▎| 467/500 [02:02<00:07,  4.71it/s]

🎧 com_01523_00854096469.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07777
🎧 com_01523_00872110638.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07782

 94%|█████████▍| 469/500 [02:02<00:06,  4.72it/s]

🎧 com_01523_00876109009.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10563

 94%|█████████▍| 471/500 [02:02<00:06,  4.83it/s]

🎧 com_01523_00882577536.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07154
🎧 com_01523_00915609895.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09058

 95%|█████████▍| 473/500 [02:03<00:05,  4.64it/s]

🎧 com_01523_00962087246.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09734
🎧 com_01523_00984800635.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08646

 95%|█████████▍| 474/500 [02:03<00:05,  4.64it/s]

🎧 com_01523_00987602132.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09800

 95%|█████████▌| 475/500 [02:03<00:05,  4.56it/s]

🎧 com_01523_00991304268.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08036

 95%|█████████▌| 476/500 [02:03<00:05,  4.66it/s]

🎧 com_01523_00993397923.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09004

 95%|█████████▌| 477/500 [02:04<00:05,  4.50it/s]

🎧 com_01523_01002118841.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10934

 96%|█████████▌| 478/500 [02:04<00:04,  4.50it/s]

🎧 com_01523_01036636017.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09471

 96%|█████████▌| 479/500 [02:04<00:04,  4.51it/s]

🎧 com_01523_01041828105.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08541

 96%|█████████▌| 480/500 [02:04<00:04,  4.49it/s]

🎧 com_01523_01045986801.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07489

 96%|█████████▌| 481/500 [02:05<00:04,  4.59it/s]

🎧 com_01523_01047048387.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06148

 96%|█████████▋| 482/500 [02:05<00:04,  4.35it/s]

🎧 com_01523_01066492627.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09317

 97%|█████████▋| 483/500 [02:05<00:04,  4.22it/s]

🎧 com_01523_01069222122.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.10271

 97%|█████████▋| 484/500 [02:05<00:04,  3.51it/s]

🎧 com_01523_01095752674.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08547

 97%|█████████▋| 485/500 [02:06<00:04,  3.53it/s]

🎧 com_01523_01105336609.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10367

 97%|█████████▋| 486/500 [02:06<00:04,  3.48it/s]

🎧 com_01523_01116504080.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08939

 97%|█████████▋| 487/500 [02:06<00:03,  3.32it/s]

🎧 com_01523_01153781311.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08565

 98%|█████████▊| 488/500 [02:07<00:03,  3.28it/s]

🎧 com_01523_01168861681.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08197

 98%|█████████▊| 489/500 [02:07<00:03,  3.08it/s]

🎧 com_01523_01196527605.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08755

 98%|█████████▊| 490/500 [02:07<00:03,  2.95it/s]

🎧 com_01523_01199769242.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10114

 98%|█████████▊| 491/500 [02:08<00:02,  3.02it/s]

🎧 com_01523_01219917632.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09726

 98%|█████████▊| 492/500 [02:08<00:02,  2.88it/s]

🎧 com_01523_01222424639.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08105

 99%|█████████▊| 493/500 [02:09<00:02,  2.80it/s]

🎧 com_01523_01226427880.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08046

 99%|█████████▉| 494/500 [02:09<00:01,  3.04it/s]

🎧 com_01523_01236040624.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08776

 99%|█████████▉| 495/500 [02:09<00:01,  3.15it/s]

🎧 com_01523_01237305140.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09971

 99%|█████████▉| 496/500 [02:09<00:01,  2.97it/s]

🎧 com_01523_01271172548.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08587

 99%|█████████▉| 497/500 [02:10<00:01,  2.82it/s]

🎧 com_01523_01282896905.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10157

100%|█████████▉| 498/500 [02:10<00:00,  2.80it/s]

🎧 com_01523_01286140247.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.07126

100%|█████████▉| 499/500 [02:10<00:00,  3.10it/s]

🎧 com_01523_01299556545.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08986

100%|██████████| 500/500 [02:11<00:00,  3.81it/s]

🎧 com_01523_01351282485.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08377

In [ ]:
print("\n Creando DataFrame...")

df = pd.DataFrame(registros)

print(" DataFrame creado")
print(f"   - Filas: {df.shape[0]}")
print(f"   - Columnas: {df.shape[1]}")

df.head()

 Creando DataFrame...
 DataFrame creado
   - Filas: 500
   - Columnas: 588

,id_audio,archivo,label,genero_f,colombiano,chileno,argentino,modelo_cyclegan,modelo_diff,modelo_stargan,...,rolloff_std,rolloff_min,rolloff_max,rolloff_median,rolloff_q1,rolloff_q3,rolloff_skew,rolloff_kurtosis,rolloff_mode,rolloff_iqr
0,1,cof_00610_00008989777.wav,0,1,1,0,0,0,0,0,...,2052.610133,148.4375,7046.8750,4171.87500,2703.125000,5951.171875,-0.464093,-1.007046,187.5000,3248.046875
1,2,cof_00610_00011481761.wav,0,1,1,0,0,0,0,0,...,1802.043666,351.5625,7226.5625,3691.40625,2548.828125,5773.437500,0.028474,-1.184660,1226.5625,3224.609375
2,3,cof_00610_00026180919.wav,0,1,1,0,0,0,0,0,...,2068.538695,148.4375,7195.3125,3437.50000,2603.515625,6167.968750,-0.163310,-1.342991,2734.3750,3564.453125
3,4,cof_00610_00083325222.wav,0,1,1,0,0,0,0,0,...,1927.039568,148.4375,7375.0000,3062.50000,2429.687500,5933.593750,0.229813,-1.189844,2679.6875,3503.906250
4,5,cof_00610_00100787111.wav,0,1,1,0,0,0,0,0,...,1914.970894,312.5000,7414.0625,4539.06250,2552.734375,6128.906250,-0.241595,-1.345283,6039.0625,3576.171875

In [ ]:
print("\n Distribución de labels:")
print(df["label"].value_counts())

print("\nProporciones:")
print(df["label"].value_counts(normalize=True))

 Distribución de labels:
label
0    500
Name: count, dtype: int64

Proporciones:
label
0    1.0
Name: proportion, dtype: float64

In [ ]:
#Revisar columnas
print("\n Información de columnas:")

print(f"Total columnas: {len(df.columns)}")

print("\nPrimeras 20 columnas:")
print(df.columns[:20])

print("\nÚltimas 20 columnas:")
print(df.columns[-20:])

 Información de columnas:
Total columnas: 588

Primeras 20 columnas:
Index(['id_audio', 'archivo', 'label', 'genero_f', 'colombiano', 'chileno',
       'argentino', 'modelo_cyclegan', 'modelo_diff', 'modelo_stargan',
       'modelo_tts_dif', 'modelo_tts_stargan', 'modelo_tts', 'duracion_seg',
       'zcr_mean', 'zcr_std', 'zcr_min', 'zcr_max', 'zcr_median', 'zcr_q1'],
      dtype='object')

Últimas 20 columnas:
Index(['flatness_min', 'flatness_max', 'flatness_median', 'flatness_q1',
       'flatness_q3', 'flatness_skew', 'flatness_kurtosis', 'flatness_mode',
       'flatness_iqr', 'rolloff_mean', 'rolloff_std', 'rolloff_min',
       'rolloff_max', 'rolloff_median', 'rolloff_q1', 'rolloff_q3',
       'rolloff_skew', 'rolloff_kurtosis', 'rolloff_mode', 'rolloff_iqr'],
      dtype='object')

In [ ]:
print("\n Información general del DataFrame:")
df.info()

 Información general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Columns: 588 entries, id_audio to rolloff_iqr
dtypes: float32(1), float64(574), int64(12), object(1)
memory usage: 2.2+ MB

In [ ]:
print("\n Estadísticas descriptivas:")
df.describe()

 Estadísticas descriptivas:

,id_audio,label,genero_f,colombiano,chileno,argentino,modelo_cyclegan,modelo_diff,modelo_stargan,modelo_tts_dif,...,rolloff_std,rolloff_min,rolloff_max,rolloff_median,rolloff_q1,rolloff_q3,rolloff_skew,rolloff_kurtosis,rolloff_mode,rolloff_iqr
count,500.000000,500.0,500.000000,500.0,500.0,500.0,500.0,500.0,500.0,500.0,...,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,250.500000,0.0,0.500000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1995.726868,331.484375,7105.06250,3678.117188,1996.660156,5704.640625,0.030629,-1.299474,2998.406250,3707.980469
std,144.481833,0.0,0.500501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,158.570321,265.743904,291.84244,1107.631344,556.800159,536.364429,0.404523,0.374352,2222.253564,627.853350
min,1.000000,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1425.633176,109.375000,5960.93750,1484.375000,890.625000,3210.937500,-1.459108,-1.787087,117.187500,921.875000
25%,125.750000,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1895.188415,148.437500,6929.68750,2849.609375,1593.261719,5562.500000,-0.209840,-1.556134,1294.921875,3397.949219
50%,250.500000,0.0,0.500000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2008.559981,203.125000,7140.62500,3484.375000,1920.898438,5854.492188,0.036758,-1.396424,1875.000000,3822.265625
75%,375.250000,0.0,1.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2115.018287,414.062500,7320.31250,4438.476562,2294.921875,6053.222656,0.289497,-1.167209,5859.375000,4187.988281
max,500.000000,0.0,1.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2391.257989,1679.687500,7703.12500,6171.875000,5429.687500,6375.000000,1.167386,0.981234,6632.812500,4734.375000

In [ ]:
print("\n Inspección de una fila completa:")

fila = df.iloc[0]

print(fila)
print("\nTotal de valores en esta fila:", len(fila))

 Inspección de una fila completa:
id_audio                                    1
archivo             cof_00610_00008989777.wav
label                                       0
genero_f                                    1
colombiano                                  1
                              ...
rolloff_q3                        5951.171875
rolloff_skew                        -0.464093
rolloff_kurtosis                    -1.007046
rolloff_mode                            187.5
rolloff_iqr                       3248.046875
Name: 0, Length: 588, dtype: object

Total de valores en esta fila: 588

In [ ]:
print("\n Guardando dataset...")

nombre_csv = f"dataset_features_{TIPO_DATASET}.csv"
ruta_salida_csv = f"/content/drive/MyDrive/Reto_Telefonica/{nombre_csv}"

df.to_csv(ruta_salida_csv, index=False)

print(" Dataset guardado correctamente")
print(f" Ruta: {ruta_salida_csv}")
print(f" Shape final: {df.shape}")

 Guardando dataset...
 Dataset guardado correctamente
 Ruta: /content/drive/MyDrive/Reto_Telefonica/dataset_features_real.csv
 Shape final: (500, 588)

In [ ]:
print("\n Preparando descarga...")

from google.colab import files
files.download(ruta_salida_csv)

print(" Descarga iniciada")

 Preparando descarga...

 Descarga iniciada

In [ ]:
print("\n Guardando archivo auxiliar de etiquetas...")

df_labels = df[["id_audio", "archivo", "label"]]

ruta_labels = f"/content/drive/MyDrive/Reto_Telefonica/labels_{TIPO_DATASET}.csv"
df_labels.to_csv(ruta_labels, index=False)

print(" Archivo de labels guardado")
print(f" Ruta: {ruta_labels}")

df_labels.head()

 Guardando archivo auxiliar de etiquetas...
 Archivo de labels guardado
 Ruta: /content/drive/MyDrive/Reto_Telefonica/labels_real.csv

   id_audio                    archivo  label
0         1  cof_00610_00008989777.wav      0
1         2  cof_00610_00011481761.wav      0
2         3  cof_00610_00026180919.wav      0
3         4  cof_00610_00083325222.wav      0
4         5  cof_00610_00100787111.wav      0