<a href="https://colab.research.google.com/github/txellbalada/Reto_IA/blob/main/500Datos_Sinteticos_colomb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Reto IA: Telefonica challenge:
###Objetivo: entrenar un modelo capaz de distinguir entre un áudio real vs uno generado con IA

In [ ]:
import numpy as np
import pandas as pd
import librosa
import os
from scipy import stats
from tqdm import tqdm
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
TIPO_DATASET = "sintetico"
ruta_carpeta = "/content/drive/MyDrive/Reto_Telefonica/Dataset_sint/Acento_Colombiano_F-M/"

In [ ]:
print("Carpeta configurada:")
print(ruta_carpeta)

print("\n¿Existe la carpeta?:", os.path.exists(ruta_carpeta))

if os.path.exists(ruta_carpeta):
    print("\nPrimeros archivos encontrados:")
    print(os.listdir(ruta_carpeta)[:10])

Carpeta configurada:
/content/drive/MyDrive/Reto_Telefonica/Dataset_sint/Acento_Colombiano_F-M/

¿Existe la carpeta?: True

Primeros archivos encontrados:
['CycleGAN-cof_02436_00052210902-cof_06136_015253.wav', 'CycleGAN-cof_02436_00301724065-cof_00610_006488.wav', 'CycleGAN-cof_02436_00733578342-cof_02484_012420.wav', 'CycleGAN-cof_02436_01680222370-cof_02484_015816.wav', 'CycleGAN-cof_02436_01718184551-cof_00610_016829.wav', 'CycleGAN-cof_02436_01680222370-cof_08784_007955.wav', 'CycleGAN-cof_02436_01718184551-com_00610_017757.wav', 'CycleGAN-cof_02436_00052210902-cof_00610_018463.wav', 'CycleGAN-cof_02436_00360598628-cof_08784_016788.wav', 'CycleGAN-cof_02436_01395350176-cof_06136_008334.wav']

In [ ]:
#Cargar audios
archivos = os.listdir(ruta_carpeta)
print(f"Se detectaron {len(archivos)} archivos en la carpeta.\n")

for archivo in archivos:
    if archivo.lower().endswith(".wav"):
        ruta_audio = os.path.join(ruta_carpeta, archivo)

        y, sr = librosa.load(ruta_audio, sr=16000)

        print(f"{archivo} cargado | duración: {len(y)/sr:.2f} segundos")

Se detectaron 500 archivos en la carpeta.

CycleGAN-cof_02436_00052210902-cof_06136_015253.wav cargado | duración: 6.07 segundos
CycleGAN-cof_02436_00301724065-cof_00610_006488.wav cargado | duración: 4.63 segundos
CycleGAN-cof_02436_00733578342-cof_02484_012420.wav cargado | duración: 6.25 segundos
CycleGAN-cof_02436_01680222370-cof_02484_015816.wav cargado | duración: 6.33 segundos
CycleGAN-cof_02436_01718184551-cof_00610_016829.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_01680222370-cof_08784_007955.wav cargado | duración: 6.33 segundos
CycleGAN-cof_02436_01718184551-com_00610_017757.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_00052210902-cof_00610_018463.wav cargado | duración: 6.07 segundos
CycleGAN-cof_02436_00360598628-cof_08784_016788.wav cargado | duración: 6.07 segundos
CycleGAN-cof_02436_01395350176-cof_06136_008334.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_01622222208-cof_02484_017436.wav cargado | duración: 5.31 segundos
CycleGAN-cof_02436_01395350176-cof_02484_019500.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_00052210902-cof_02484_006194.wav cargado | duración: 6.07 segundos
CycleGAN-cof_02436_01680222370-cof_06136_014632.wav cargado | duración: 6.33 segundos
CycleGAN-cof_02436_01622222208-cof_08784_019605.wav cargado | duración: 5.31 segundos
CycleGAN-cof_02436_01680222370-com_00610_008687.wav cargado | duración: 6.33 segundos
CycleGAN-cof_02436_00360598628-cof_02484_005125.wav cargado | duración: 6.07 segundos
CycleGAN-cof_02436_01306173906-cof_00610_011037.wav cargado | duración: 5.15 segundos
CycleGAN-cof_02436_01395350176-com_00610_014397.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_01306173906-cof_02484_010608.wav cargado | duración: 5.15 segundos
CycleGAN-cof_02436_00360598628-cof_00610_016479.wav cargado | duración: 6.07 segundos
CycleGAN-cof_02436_00360598628-cof_06136_003214.wav cargado | duración: 6.07 segundos
CycleGAN-cof_02436_01622222208-cof_00610_001379.wav cargado | duración: 5.31 segundos
CycleGAN-cof_02436_00733578342-cof_00610_016455.wav cargado | duración: 6.25 segundos
CycleGAN-cof_02436_00301724065-cof_02484_010086.wav cargado | duración: 4.63 segundos
CycleGAN-cof_02436_01718184551-cof_06136_021051.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_00301724065-cof_08784_020908.wav cargado | duración: 4.63 segundos
CycleGAN-cof_02436_01718184551-cof_08784_008615.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_00052210902-cof_08784_012992.wav cargado | duración: 6.07 segundos
CycleGAN-cof_02436_01622222208-cof_06136_013806.wav cargado | duración: 5.31 segundos
CycleGAN-cof_02436_00733578342-cof_06136_018668.wav cargado | duración: 6.25 segundos
CycleGAN-cof_02436_01680222370-cof_00610_017193.wav cargado | duración: 6.33 segundos
CycleGAN-cof_02436_01718184551-cof_02484_001055.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_01622222208-com_00610_017113.wav cargado | duración: 5.31 segundos
CycleGAN-cof_02436_01395350176-cof_00610_002101.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_01395350176-cof_08784_007856.wav cargado | duración: 5.23 segundos
CycleGAN-cof_02436_00301724065-cof_06136_006741.wav cargado | duración: 4.63 segundos
CycleGAN-cof_02436_01306173906-cof_08784_009143.wav cargado | duración: 5.15 segundos
CycleGAN-cof_02436_01306173906-cof_06136_020170.wav cargado | duración: 5.15 segundos
CycleGAN-cof_02436_00733578342-cof_08784_007698.wav cargado | duración: 6.25 segundos
CycleGAN-cof_04310_01548249039-cof_00610_009870.wav cargado | duración: 4.03 segundos
CycleGAN-cof_04310_01705476715-cof_00610_009519.wav cargado | duración: 5.99 segundos
CycleGAN-cof_04310_01734349225-cof_00610_009338.wav cargado | duración: 8.05 segundos
CycleGAN-cof_04310_01534630157-cof_00610_021233.wav cargado | duración: 6.59 segundos
CycleGAN-cof_04310_01664914398-cof_00610_005819.wav cargado | duración: 5.39 segundos
CycleGAN-com_03397_01422637121-com_00610_020542.wav cargado | duración: 4.45 segundos
CycleGAN-com_03397_02083059612-com_09334_001822.wav cargado | duración: 3.51 segundos
CycleGAN-com_03397_01345735056-com_00610_002565.wav cargado | duración: 4.89 segundos
CycleGAN-com_03397_00671793720-com_02436_013055.wav cargado | duración: 5.39 segundos
CycleGAN-com_03397_00153070180-com_02436_011059.wav cargado | duración: 3.51 segundos
CycleGAN-com_03397_01422637121-com_09334_003807.wav cargado | duración: 4.45 segundos
CycleGAN-com_03397_01519532274-com_00610_017084.wav cargado | duración: 4.11 segundos
CycleGAN-com_03397_00495289763-com_00610_012269.wav cargado | duración: 9.67 segundos
CycleGAN-com_03397_02083059612-com_04310_007894.wav cargado | duración: 3.51 segundos
CycleGAN-com_03397_00984240661-com_00610_002593.wav cargado | duración: 4.45 segundos
CycleGAN-com_03397_00391015228-com_00610_017742.wav cargado | duración: 5.05 segundos
CycleGAN-com_03397_01519532274-com_04310_000367.wav cargado | duración: 4.11 segundos
CycleGAN-com_03397_02083059612-com_02436_021214.wav cargado | duración: 3.51 segundos
CycleGAN-com_03397_00495289763-com_04310_006265.wav cargado | duración: 9.67 segundos
CycleGAN-com_03397_00495289763-com_09334_020584.wav cargado | duración: 9.67 segundos
CycleGAN-com_03397_01536556841-com_02436_004787.wav cargado | duración: 5.65 segundos
CycleGAN-com_03397_00153070180-com_04310_009166.wav cargado | duración: 3.51 segundos
CycleGAN-com_03397_01422637121-com_02436_000466.wav cargado | duración: 4.45 segundos
CycleGAN-com_03397_01536556841-com_00610_014120.wav cargado | duración: 5.65 segundos
CycleGAN-com_03397_00671793720-com_09334_004505.wav cargado | duración: 5.39 segundos
CycleGAN-com_03397_00495289763-com_02436_014183.wav cargado | duración: 9.67 segundos
CycleGAN-com_03397_02083059612-com_00610_019470.wav cargado | duración: 3.51 segundos
CycleGAN-com_03397_01519532274-com_09334_018293.wav cargado | duración: 4.11 segundos
CycleGAN-com_03397_00391015228-com_04310_005438.wav cargado | duración: 5.05 segundos
CycleGAN-com_03397_00153070180-com_09334_014272.wav cargado | duración: 3.51 segundos
CycleGAN-com_03397_01345735056-com_04310_013674.wav cargado | duración: 4.89 segundos
CycleGAN-com_03397_00391015228-com_09334_007292.wav cargado | duración: 5.05 segundos
CycleGAN-com_03397_01536556841-com_04310_007084.wav cargado | duración: 5.65 segundos
CycleGAN-com_03397_00984240661-com_02436_013827.wav cargado | duración: 4.45 segundos
CycleGAN-com_03397_01536556841-com_09334_004658.wav cargado | duración: 5.65 segundos
CycleGAN-com_03397_00671793720-com_00610_001516.wav cargado | duración: 5.39 segundos
CycleGAN-com_03397_01519532274-com_02436_010921.wav cargado | duración: 4.11 segundos
CycleGAN-com_03397_01345735056-com_02436_007971.wav cargado | duración: 4.89 segundos
CycleGAN-com_03397_01422637121-com_04310_018677.wav cargado | duración: 4.45 segundos
CycleGAN-com_03397_00984240661-com_09334_003473.wav cargado | duración: 4.45 segundos
CycleGAN-com_03397_00153070180-com_00610_016916.wav cargado | duración: 3.51 segundos
CycleGAN-com_03397_00671793720-com_04310_013128.wav cargado | duración: 5.39 segundos
CycleGAN-com_03397_00984240661-com_04310_017610.wav cargado | duración: 4.45 segundos
CycleGAN-com_03397_00391015228-com_02436_011527.wav cargado | duración: 5.05 segundos
CycleGAN-com_03397_01345735056-com_09334_016670.wav cargado | duración: 4.89 segundos
CycleGAN-com_08784_01642441049-com_00610_008168.wav cargado | duración: 7.27 segundos
CycleGAN-com_08784_00866705887-com_00610_019543.wav cargado | duración: 7.11 segundos
CycleGAN-com_08784_01684783873-com_00610_001516.wav cargado | duración: 5.57 segundos
CycleGAN-com_08784_00747945674-com_00610_019871.wav cargado | duración: 6.59 segundos
CycleGAN-com_08784_01573439386-com_00610_000842.wav cargado | duración: 6.07 segundos
Diff-cof_00610_00158081190-cof_08784_0174310328.wav cargado | duración: 3.83 segundos
Diff-cof_00610_00158081190-cof_03397_0089927024.wav cargado | duración: 3.83 segundos
Diff-cof_01523_01199131701-cof_06136_0045191048.wav cargado | duración: 6.14 segundos
Diff-cof_01523_00017388571-cof_03397_0119385628.wav cargado | duración: 4.52 segundos
Diff-cof_00610_01332160527-cof_08784_0009124657.wav cargado | duración: 4.77 segundos
Diff-cof_00610_00444664843-cof_08784_0178758525.wav cargado | duración: 5.38 segundos
Diff-cof_00610_01307574255-cof_09334_0205082724.wav cargado | duración: 3.83 segundos
Diff-cof_01523_00287301417-cof_06136_0138064158.wav cargado | duración: 4.60 segundos
Diff-cof_00610_01623396263-cof_08784_0077901315.wav cargado | duración: 5.20 segundos
Diff-cof_00610_00444664843-cof_03397_0044696594.wav cargado | duración: 5.38 segundos
Diff-cof_00610_00749562938-cof_03397_0091984475.wav cargado | duración: 6.40 segundos
Diff-cof_00610_01034785289-cof_06136_0198387608.wav cargado | duración: 6.73 segundos
Diff-cof_00610_01307574255-cof_08784_0179488973.wav cargado | duración: 3.83 segundos
Diff-cof_01523_00287301417-cof_03397_0018202330.wav cargado | duración: 4.60 segundos
Diff-cof_00610_01398673747-cof_03397_0042088430.wav cargado | duración: 4.01 segundos
Diff-cof_00610_01623396263-cof_06136_0166762008.wav cargado | duración: 5.20 segundos
Diff-cof_00610_01623396263-cof_09334_0011198998.wav cargado | duración: 5.20 segundos
Diff-cof_01523_01911321218-cof_03397_0061287382.wav cargado | duración: 8.95 segundos
Diff-cof_01523_01318664847-cof_03397_0193407042.wav cargado | duración: 5.03 segundos
Diff-cof_01523_00803058134-cof_06136_0147088627.wav cargado | duración: 6.14 segundos
Diff-cof_01523_02014850499-cof_03397_0172352763.wav cargado | duración: 6.22 segundos
Diff-cof_00610_01307574255-cof_03397_0013951126.wav cargado | duración: 3.83 segundos
Diff-cof_00610_01398673747-cof_08784_0164560055.wav cargado | duración: 4.01 segundos
Diff-cof_00610_00561353575-cof_09334_0141934040.wav cargado | duración: 6.73 segundos
Diff-cof_00610_01332160527-cof_03397_0061287382.wav cargado | duración: 4.77 segundos
Diff-cof_00610_00155617852-cof_06136_0140986186.wav cargado | duración: 6.48 segundos
Diff-cof_00610_01034785289-cof_09334_0066486683.wav cargado | duración: 6.73 segundos
Diff-cof_00610_00561353575-cof_08784_0211073133.wav cargado | duración: 6.73 segundos
Diff-cof_00610_00749562938-cof_09334_0127241222.wav cargado | duración: 6.40 segundos
Diff-cof_00610_00158081190-cof_06136_0186688255.wav cargado | duración: 3.83 segundos
Diff-cof_01523_01199131701-cof_03397_0009690315.wav cargado | duración: 6.14 segundos
Diff-cof_00610_01332160527-cof_09334_0154891939.wav cargado | duración: 4.77 segundos
Diff-cof_00610_00444664843-cof_06136_0080745076.wav cargado | duración: 5.38 segundos
Diff-cof_00610_01398673747-cof_06136_0042673780.wav cargado | duración: 4.01 segundos
Diff-cof_00610_01332160527-cof_06136_0168939491.wav cargado | duración: 4.77 segundos
Diff-cof_01523_00803058134-cof_03397_0130639404.wav cargado | duración: 6.14 segundos
Diff-cof_00610_00561353575-cof_06136_0059271049.wav cargado | duración: 6.73 segundos
Diff-cof_00610_00444664843-cof_09334_0046198134.wav cargado | duración: 5.38 segundos
Diff-cof_00610_00561353575-cof_03397_0044097123.wav cargado | duración: 6.73 segundos
Diff-cof_01523_00162566952-cof_06136_0139456426.wav cargado | duración: 6.83 segundos
Diff-cof_00610_00749562938-cof_06136_0003663539.wav cargado | duración: 6.40 segundos
Diff-cof_00610_00155617852-cof_03397_0015483685.wav cargado | duración: 6.48 segundos
Diff-cof_00610_00155617852-cof_08784_0129929867.wav cargado | duración: 6.48 segundos
Diff-cof_00610_01623396263-cof_03397_0115508741.wav cargado | duración: 5.20 segundos
Diff-cof_00610_00749562938-cof_08784_0129331080.wav cargado | duración: 6.40 segundos
Diff-cof_01523_01297047509-cof_03397_0131607662.wav cargado | duración: 5.79 segundos
Diff-cof_01523_00491195227-cof_03397_0213234935.wav cargado | duración: 5.28 segundos
Diff-cof_01523_00017388571-cof_06136_0039349756.wav cargado | duración: 4.52 segundos
Diff-cof_00610_00158081190-cof_09334_0050863880.wav cargado | duración: 3.83 segundos
Diff-cof_01523_00162566952-cof_03397_0179483382.wav cargado | duración: 6.83 segundos
Diff-cof_00610_01398673747-cof_09334_0136423076.wav cargado | duración: 4.01 segundos
Diff-cof_00610_01307574255-cof_06136_0059378057.wav cargado | duración: 3.83 segundos
Diff-cof_00610_01034785289-cof_03397_0202093827.wav cargado | duración: 6.73 segundos
Diff-cof_00610_01034785289-cof_08784_0091433377.wav cargado | duración: 6.73 segundos
Diff-cof_00610_00155617852-cof_09334_0117270978.wav cargado | duración: 6.48 segundos
Diff-cof_01523_00491195227-cof_06136_0059728655.wav cargado | duración: 5.28 segundos
Diff-cof_01523_00162566952-cof_09334_0031127525.wav cargado | duración: 6.83 segundos
Diff-cof_01523_01199131701-cof_09334_0116010015.wav cargado | duración: 6.14 segundos
Diff-cof_01523_02014850499-cof_08784_0209457101.wav cargado | duración: 6.22 segundos
Diff-cof_01523_00491195227-cof_09334_0011685477.wav cargado | duración: 5.28 segundos
Diff-cof_01523_00017388571-cof_09334_0139100870.wav cargado | duración: 4.52 segundos
Diff-cof_01523_01318664847-cof_09334_0051878998.wav cargado | duración: 5.03 segundos
Diff-cof_01523_01297047509-cof_09334_0013637451.wav cargado | duración: 5.79 segundos
Diff-cof_01523_00287301417-cof_09334_0081920497.wav cargado | duración: 4.60 segundos
Diff-cof_01523_00803058134-cof_08784_0012921582.wav cargado | duración: 6.14 segundos
Diff-cof_01523_01318664847-cof_08784_0016935679.wav cargado | duración: 5.03 segundos
Diff-cof_01523_01297047509-cof_08784_0093943398.wav cargado | duración: 5.79 segundos
Diff-cof_01523_00162566952-cof_08784_0154593412.wav cargado | duración: 6.83 segundos
Diff-cof_01523_01199131701-cof_08784_0162030971.wav cargado | duración: 6.14 segundos
Diff-cof_01523_02014850499-cof_06136_0143654051.wav cargado | duración: 6.22 segundos
Diff-cof_01523_01911321218-cof_06136_0051048826.wav cargado | duración: 8.95 segundos
Diff-cof_01523_02014850499-cof_09334_0131309107.wav cargado | duración: 6.22 segundos
Diff-cof_01523_01318664847-cof_06136_0146327642.wav cargado | duración: 5.03 segundos
Diff-cof_01523_01297047509-cof_06136_0114322370.wav cargado | duración: 5.79 segundos
Diff-cof_01523_00017388571-cof_08784_0166976291.wav cargado | duración: 4.52 segundos
Diff-cof_01523_00287301417-cof_08784_0017503433.wav cargado | duración: 4.60 segundos
Diff-cof_01523_01911321218-cof_09334_0138706379.wav cargado | duración: 8.95 segundos
Diff-cof_01523_01911321218-cof_08784_0147517360.wav cargado | duración: 8.95 segundos
Diff-cof_01523_00803058134-cof_09334_0054033309.wav cargado | duración: 6.14 segundos
Diff-cof_01523_00491195227-cof_08784_0045429384.wav cargado | duración: 5.28 segundos
Diff-com_02121_00092301756-com_02484_0168217593.wav cargado | duración: 6.65 segundos
Diff-com_02121_00055866196-com_02484_0085763625.wav cargado | duración: 5.54 segundos
Diff-com_02121_01715240584-com_08784_0109299797.wav cargado | duración: 6.99 segundos
Diff-com_02121_01818879615-com_03397_0106091960.wav cargado | duración: 6.22 segundos
Diff-com_02121_01256596109-com_03397_0121134432.wav cargado | duración: 9.04 segundos
Diff-com_02121_00055866196-com_08784_0086073476.wav cargado | duración: 5.54 segundos
Diff-com_02121_01818879615-com_09697_0054161868.wav cargado | duración: 6.22 segundos
Diff-com_02121_01809809142-com_02484_0012939601.wav cargado | duración: 6.14 segundos
Diff-com_02121_01715240584-com_03397_0111214656.wav cargado | duración: 6.99 segundos
Diff-com_02121_01256596109-com_08784_0036287663.wav cargado | duración: 9.04 segundos
Diff-com_02121_01818879615-com_08784_0148601772.wav cargado | duración: 6.22 segundos
Diff-com_02121_01170861108-com_03397_0122683242.wav cargado | duración: 5.89 segundos
Diff-com_02121_01809809142-com_08784_0212838863.wav cargado | duración: 6.14 segundos
Diff-com_02121_01809809142-com_03397_0006392577.wav cargado | duración: 6.14 segundos
Diff-com_02121_00092301756-com_08784_0045376496.wav cargado | duración: 6.65 segundos
Diff-com_02121_01256596109-com_02484_0131032960.wav cargado | duración: 9.04 segundos
Diff-com_02121_02073608306-com_08784_0060645418.wav cargado | duración: 5.38 segundos
Diff-com_02121_01715240584-com_02484_0101430602.wav cargado | duración: 6.99 segundos
Diff-com_02121_02073608306-com_03397_0150856269.wav cargado | duración: 5.38 segundos
Diff-com_02121_01715240584-com_09697_0105629758.wav cargado | duración: 6.99 segundos
Diff-com_02121_01326190855-com_02484_0023315825.wav cargado | duración: 5.38 segundos
Diff-com_02121_01256596109-com_09697_0049980416.wav cargado | duración: 9.04 segundos
Diff-com_02121_00740056573-com_02484_0094088807.wav cargado | duración: 5.79 segundos
Diff-com_02121_02073608306-com_09697_0145953998.wav cargado | duración: 5.38 segundos
Diff-com_02121_00092301756-com_09697_0051652043.wav cargado | duración: 6.65 segundos
Diff-com_02121_01326190855-com_08784_0014163279.wav cargado | duración: 5.38 segundos
Diff-com_02121_00740056573-com_09697_0014733619.wav cargado | duración: 5.79 segundos
Diff-com_02121_00740056573-com_03397_0196344001.wav cargado | duración: 5.79 segundos
Diff-com_02121_01170861108-com_09697_0163224310.wav cargado | duración: 5.89 segundos
Diff-com_02121_00055866196-com_09697_0029457407.wav cargado | duración: 5.54 segundos
Diff-com_02121_02073608306-com_02484_0118533204.wav cargado | duración: 5.38 segundos
Diff-com_02121_00055866196-com_03397_0028670387.wav cargado | duración: 5.54 segundos
Diff-com_02121_01809809142-com_09697_0200093021.wav cargado | duración: 6.14 segundos
Diff-com_02121_01326190855-com_09697_0066311509.wav cargado | duración: 5.38 segundos
Diff-com_02121_00092301756-com_03397_0054553643.wav cargado | duración: 6.65 segundos
Diff-com_02121_01818879615-com_02484_0157088217.wav cargado | duración: 6.22 segundos
Diff-com_02121_01326190855-com_03397_0079469967.wav cargado | duración: 5.38 segundos
Diff-com_02121_01170861108-com_08784_0011507616.wav cargado | duración: 5.89 segundos
Diff-com_02121_00740056573-com_08784_0108584834.wav cargado | duración: 5.79 segundos
Diff-com_02121_01170861108-com_02484_0049711515.wav cargado | duración: 5.89 segundos
Diff-com_02436_00254792024-com_02484_0049711515.wav cargado | duración: 4.43 segundos
Diff-com_02436_00330898967-com_02484_0185735502.wav cargado | duración: 4.09 segundos
Diff-com_02436_01884995837-com_09697_0046180067.wav cargado | duración: 4.09 segundos
Diff-com_02436_00669944333-com_09697_0152173704.wav cargado | duración: 3.58 segundos
Diff-com_02436_01809687779-com_08784_0044005854.wav cargado | duración: 3.75 segundos
Diff-com_02436_00254792024-com_08784_0021371211.wav cargado | duración: 4.43 segundos
Diff-com_02436_00330898967-com_08784_0020121861.wav cargado | duración: 4.09 segundos
Diff-com_02436_02031862691-com_08784_0088896815.wav cargado | duración: 3.49 segundos
Diff-com_02436_00669944333-com_03397_0036060181.wav cargado | duración: 3.58 segundos
Diff-com_02436_00772446157-com_03397_0078806516.wav cargado | duración: 5.12 segundos
Diff-com_02436_01113680738-com_09697_0101499470.wav cargado | duración: 5.38 segundos
Diff-com_02436_01113680738-com_02484_0117484855.wav cargado | duración: 5.38 segundos
Diff-com_02436_00669944333-com_02484_0113732683.wav cargado | duración: 3.58 segundos
Diff-com_02436_01113680738-com_08784_0119025494.wav cargado | duración: 5.38 segundos
Diff-com_02436_01691014862-com_03397_0039101522.wav cargado | duración: 3.83 segundos
Diff-com_02436_01691014862-com_09697_0214652136.wav cargado | duración: 3.83 segundos
Diff-com_02436_00772446157-com_08784_0145925834.wav cargado | duración: 5.12 segundos
Diff-com_02436_01557457002-com_09697_0113365686.wav cargado | duración: 4.18 segundos
Diff-com_02436_00254792024-com_09697_0014850634.wav cargado | duración: 4.43 segundos
Diff-com_02436_01557457002-com_02484_0055953863.wav cargado | duración: 4.18 segundos
Diff-com_02436_01884995837-com_03397_0109402348.wav cargado | duración: 4.09 segundos
Diff-com_02436_01809687779-com_02484_0195468578.wav cargado | duración: 3.75 segundos

In [ ]:
def extraer_etiquetas(nombre_audio, modo="auto"):
    """
    Extrae etiquetas binarias desde el nombre del audio.

    Devuelve un diccionario con:
    - label: 0 real / 1 sintético
    - genero_f: 1 mujer / 0 hombre
    - nacionalidad: colombiano / chileno / argentino
    - modelo generador: CycleGAN, Diff, StarGAN, TTS-Dif, TTS-StarGAN, TTS
    """

    nombre = nombre_audio.lower()

    etiquetas = {
        # Label principal
        "label": 0,

        # 🔥 Género (solo una columna)
        "genero_f": 0,

        # Nacionalidad
        "colombiano": 0,
        "chileno": 0,
        "argentino": 0,

        # Modelo generador
        "modelo_cyclegan": 0,
        "modelo_diff": 0,
        "modelo_stargan": 0,
        "modelo_tts_dif": 0,
        "modelo_tts_stargan": 0,
        "modelo_tts": 0
    }

    # -----------------------------
    # 1. Label principal
    # -----------------------------
    if modo == "real":
        etiquetas["label"] = 0
    elif modo == "sintetico":
        etiquetas["label"] = 1
    else:
        etiquetas["label"] = 1 if "-" in nombre_audio else 0

    # -----------------------------
    # 2. Nacionalidad + género
    # -----------------------------
    if "com" in nombre:
        etiquetas["colombiano"] = 1
        etiquetas["genero_f"] = 0

    elif "cof" in nombre:
        etiquetas["colombiano"] = 1
        etiquetas["genero_f"] = 1

    elif "clm" in nombre:
        etiquetas["chileno"] = 1
        etiquetas["genero_f"] = 0

    elif "clf" in nombre:
        etiquetas["chileno"] = 1
        etiquetas["genero_f"] = 1

    elif "arm" in nombre:
        etiquetas["argentino"] = 1
        etiquetas["genero_f"] = 0

    elif "arf" in nombre:
        etiquetas["argentino"] = 1
        etiquetas["genero_f"] = 1

    # -----------------------------
    # 3. Modelo generador
    # -----------------------------
    nombre_original = nombre_audio  # mantener mayúsculas

    if "TTS-StarGAN" in nombre_original:
        etiquetas["modelo_tts_stargan"] = 1
    elif "TTS-Dif" in nombre_original:
        etiquetas["modelo_tts_dif"] = 1
    elif "CycleGAN" in nombre_original:
        etiquetas["modelo_cyclegan"] = 1
    elif "StarGAN" in nombre_original:
        etiquetas["modelo_stargan"] = 1
    elif "Diff" in nombre_original:
        etiquetas["modelo_diff"] = 1
    elif "TTS" in nombre_original:
        etiquetas["modelo_tts"] = 1

    return etiquetas

In [ ]:
def generar_df_etiquetas(ruta_carpeta, tipo_dataset="auto"):
    """
    Genera un DataFrame con múltiples etiquetas:
    - id_audio: identificador secuencial (1, 2, 3, ...)
    - archivo: nombre original del archivo
    - label: real (0) vs sintético (1)
    - genero_f: mujer (1), hombre (0)
    - nacionalidad: colombiano / chileno / argentino
    - modelo generador
    """

    print(f"Explorando carpeta: {ruta_carpeta}")
    datos = []

    contador_id = 1

    for archivo in sorted(os.listdir(ruta_carpeta)):
        if archivo.lower().endswith(".wav"):
            nombre_audio = archivo.replace(".wav", "")

            etiquetas = extraer_etiquetas(nombre_audio, modo=tipo_dataset)

            fila = {
                "id_audio": contador_id,
                "archivo": archivo
            }

            fila.update(etiquetas)
            datos.append(fila)

            contador_id += 1

    df_etiquetas = pd.DataFrame(datos)

    print(f"DataFrame creado con {len(df_etiquetas)} registros.")
    print(f"Número de columnas: {df_etiquetas.shape[1]}")

    return df_etiquetas

In [ ]:
df_labels = generar_df_etiquetas(ruta_carpeta, tipo_dataset=TIPO_DATASET)
df_labels.head()

Explorando carpeta: /content/drive/MyDrive/Reto_Telefonica/Dataset_sint/Acento_Colombiano_F-M/
DataFrame creado con 500 registros.
Número de columnas: 13

,id_audio,archivo,label,genero_f,colombiano,chileno,argentino,modelo_cyclegan,modelo_diff,modelo_stargan,modelo_tts_dif,modelo_tts_stargan,modelo_tts
0,1,CycleGAN-cof_02436_00052210902-cof_00610_01846...,1,1,1,0,0,1,0,0,0,0,0
1,2,CycleGAN-cof_02436_00052210902-cof_02484_00619...,1,1,1,0,0,1,0,0,0,0,0
2,3,CycleGAN-cof_02436_00052210902-cof_06136_01525...,1,1,1,0,0,1,0,0,0,0,0
3,4,CycleGAN-cof_02436_00052210902-cof_08784_01299...,1,1,1,0,0,1,0,0,0,0,0
4,5,CycleGAN-cof_02436_00301724065-cof_00610_00648...,1,1,1,0,0,1,0,0,0,0,0

##  Mejor opción para TU problema (detección de voz fake)

Para detectar audio sintético, lo más importante es capturar:

- textura espectral (cómo suena la voz)  
- irregularidades (artefactos de IA)  
- dinámica (energía, variaciones)  

 Por eso, la mejor combinación es:


###  1. MFCC + Delta MFCC (OBLIGATORIO)

Son las más importantes.

Capturan:

- forma del espectro (timbre)  
- cambios en el tiempo  

✔ Detectan muy bien voces sintéticas  


###  2. Features de energía y estructura

- RMS → energía  
- ZCR → ruido/aspereza  

✔ Útiles para detectar artefactos de IA  



###  3. Features espectrales

- Spectral centroid → brillo  
- Bandwidth → dispersión  
- Rolloff → límite de energía  
- Flatness → tonal vs ruido  

✔ Clave para distinguir natural vs artificial  


###  4. Spectral contrast (MUY importante)

Esto muchas veces se subestima, pero:

 captura diferencias entre bandas de frecuencia  

✔ Muy útil para detectar:

- vocoders  
- modelos tipo GAN / TTS  


###  5. Estadísticas (CRÍTICO)

Esto es lo que mucha gente hace mal:

 NO usar los valores frame a frame  
 SÍ usar resumen:

- mean  
- std  
- min  
- max  
- median  
- q1  
- q3  

✔ Esto convierte el audio en una representación robusta  


## Entonces… ¿cuál es la mejor opción?

 EXACTAMENTE la que implementaste en el notebook nuevo:

✔ MFCC (13)  
✔ Delta MFCC  
✔ ZCR  
✔ RMS  
✔ Spectral features  
✔ Spectral contrast  
✔ Estadísticas completas

In [ ]:
from scipy import stats

def resumir_feature(vector, prefijo, debug=False):
    """
    Resume un vector numérico con estadísticas descriptivas avanzadas.
    """

    vector = np.asarray(vector).astype(float)

    if len(vector) == 0:
        return {}

    resultado = {
        f"{prefijo}_mean": np.mean(vector),
        f"{prefijo}_std": np.std(vector),
        f"{prefijo}_min": np.min(vector),
        f"{prefijo}_max": np.max(vector),
        f"{prefijo}_median": np.median(vector),
        f"{prefijo}_q1": np.quantile(vector, 0.25),
        f"{prefijo}_q3": np.quantile(vector, 0.75),
        f"{prefijo}_skew": stats.skew(vector),
        f"{prefijo}_kurtosis": stats.kurtosis(vector),
        f"{prefijo}_mode": stats.mode(vector, keepdims=True)[0][0],
        f"{prefijo}_iqr": stats.iqr(vector)
    }

In [ ]:
#Función de extracción de features
def extraer_features(ruta_audio, sr_objetivo=16000, n_mfcc=13):
    """
    Extrae features de un audio y devuelve un diccionario.
    """

    y, sr = librosa.load(ruta_audio, sr=sr_objetivo)

    # Recorte de silencios
    y, _ = librosa.effects.trim(y)

    if len(y) < 512:
        return None

    features = {}

    # -------------------
    # META
    # -------------------
    features["duracion_seg"] = len(y) / sr

    # -------------------
    # ZCR
    # -------------------
    zcr = librosa.feature.zero_crossing_rate(y)[0]
    features.update(resumir_feature(zcr, "zcr"))

    # -------------------
    # RMS (librosa)
    # -------------------
    rms = librosa.feature.rms(y=y)[0]
    features.update(resumir_feature(rms, "rms"))

    # -------------------
    # RMSE manual
    # -------------------
    rmse_manual = np.sqrt(np.mean(y**2))
    features["rmse_manual"] = rmse_manual

    # -------------------
    # TEMPO
    # -------------------
    tempo = librosa.beat.tempo(y=y, sr=sr)[0]
    features["tempo"] = tempo

    # -------------------
    # MFCC
    # -------------------
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
    for i in range(n_mfcc):
        features.update(resumir_feature(mfcc[i], f"mfcc_{i+1}"))

    # -------------------
    # DELTA MFCC
    # -------------------
    delta_mfcc = librosa.feature.delta(mfcc)
    for i in range(n_mfcc):
        features.update(resumir_feature(delta_mfcc[i], f"delta_mfcc_{i+1}"))

    # -------------------
    # DELTA-DELTA MFCC
    # -------------------
    delta2_mfcc = librosa.feature.delta(mfcc, order=2)
    for i in range(n_mfcc):
        features.update(resumir_feature(delta2_mfcc[i], f"delta2_mfcc_{i+1}"))

    # -------------------
    # SPECTRAL FEATURES
    # -------------------
    centroid = librosa.feature.spectral_centroid(y=y, sr=sr)[0]
    features.update(resumir_feature(centroid, "centroid"))

    bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=sr)[0]
    features.update(resumir_feature(bandwidth, "bandwidth"))

    contrast = librosa.feature.spectral_contrast(y=y, sr=sr)
    for i in range(contrast.shape[0]):
        features.update(resumir_feature(contrast[i], f"contrast_{i+1}"))

    flatness = librosa.feature.spectral_flatness(y=y)[0]
    features.update(resumir_feature(flatness, "flatness"))

    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)[0]
    features.update(resumir_feature(rolloff, "rolloff"))

    # -------------------
    # PRINT FINAL
    # -------------------
    print(f"🎧 {os.path.basename(ruta_audio)}")
    print(f"   - Features extraídas: {len(features)}")
    print(f"   - Tempo: {tempo:.2f}")
    print(f"   - RMSE manual: {rmse_manual:.5f}")

    return features

In [ ]:
print("\n🔎 Probando extracción de features con un audio...\n")

for archivo in sorted(os.listdir(ruta_carpeta)):
    if archivo.lower().endswith(".wav"):
        ruta_audio_prueba = os.path.join(ruta_carpeta, archivo)

        try:
            ejemplo_features = extraer_features(ruta_audio_prueba)

            if ejemplo_features is None:
                print(f"⚠️ Audio omitido (muy corto): {archivo}")
                continue

            print("\n📊 Resultado:")
            print(f"   - Audio: {archivo}")
            print(f"   - Nº features: {len(ejemplo_features)}")

            # 🔥 Mostrar algunas features clave
            print("\n🔑 Ejemplo de features:")
            for k, v in list(ejemplo_features.items())[:5]:
                print(f"   {k}: {v}")

            # 🔥 Verificar si hay valores problemáticos
            valores = list(ejemplo_features.values())
            n_nan = sum(np.isnan(valores))
            n_inf = sum(np.isinf(valores))

            print("\n🧪 Control de calidad:")
            print(f"   - NaN: {n_nan}")
            print(f"   - Inf: {n_inf}")

            break

        except Exception as e:
            print(f"❌ Error con {archivo}: {e}")
            continue

🔎 Probando extracción de features con un audio...

/tmp/ipykernel_5188/2322890922.py:43: FutureWarning: librosa.beat.tempo
	This function was moved to 'librosa.feature.rhythm.tempo' in librosa version 0.10.0.
	This alias will be removed in librosa version 1.0.
  tempo = librosa.beat.tempo(y=y, sr=sr)[0]

🎧 CycleGAN-cof_02436_00052210902-cof_00610_018463.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09733

📊 Resultado:
   - Audio: CycleGAN-cof_02436_00052210902-cof_00610_018463.wav
   - Nº features: 575

🔑 Ejemplo de features:
   duracion_seg: 4.0
   zcr_mean: 0.1693173363095238
   zcr_std: 0.07817229830859039
   zcr_min: 0.05224609375
   zcr_max: 0.353515625

🧪 Control de calidad:
   - NaN: 0
   - Inf: 0

In [ ]:
registros = []

archivos_wav = sorted([a for a in os.listdir(ruta_carpeta) if a.lower().endswith(".wav")])

for idx, archivo in enumerate(tqdm(archivos_wav), start=1):
    ruta_audio = os.path.join(ruta_carpeta, archivo)
    nombre_audio = archivo.replace(".wav", "")

    try:
        etiquetas = extraer_etiquetas(nombre_audio, modo=TIPO_DATASET)
        feats = extraer_features(ruta_audio)

        if feats is None:
            print(f"Audio omitido por ser demasiado corto: {archivo}")
            continue

        fila = {
            "id_audio": idx,
            "archivo": archivo
        }

        fila.update(etiquetas)
        fila.update(feats)

        registros.append(fila)

    except Exception as e:
        print(f"Error procesando {archivo}: {e}")

  0%|          | 0/500 [00:00<?, ?it/s]/tmp/ipykernel_5188/2322890922.py:43: FutureWarning: librosa.beat.tempo
	This function was moved to 'librosa.feature.rhythm.tempo' in librosa version 0.10.0.
	This alias will be removed in librosa version 1.0.
  tempo = librosa.beat.tempo(y=y, sr=sr)[0]
  0%|          | 1/500 [00:00<01:48,  4.59it/s]

🎧 CycleGAN-cof_02436_00052210902-cof_00610_018463.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09733

  0%|          | 2/500 [00:00<01:49,  4.53it/s]

🎧 CycleGAN-cof_02436_00052210902-cof_02484_006194.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.04725

  1%|          | 3/500 [00:00<01:49,  4.55it/s]

🎧 CycleGAN-cof_02436_00052210902-cof_06136_015253.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11618

  1%|          | 5/500 [00:01<01:46,  4.65it/s]

🎧 CycleGAN-cof_02436_00052210902-cof_08784_012992.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11713
🎧 CycleGAN-cof_02436_00301724065-cof_00610_006488.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11296

  1%|          | 6/500 [00:01<02:15,  3.66it/s]

🎧 CycleGAN-cof_02436_00301724065-cof_02484_010086.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05020

  2%|▏         | 8/500 [00:03<04:56,  1.66it/s]

🎧 CycleGAN-cof_02436_00301724065-cof_06136_006741.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13339
🎧 CycleGAN-cof_02436_00301724065-cof_08784_020908.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.14542

  2%|▏         | 9/500 [00:03<03:57,  2.06it/s]

🎧 CycleGAN-cof_02436_00360598628-cof_00610_016479.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06967

  2%|▏         | 10/500 [00:04<03:21,  2.43it/s]

🎧 CycleGAN-cof_02436_00360598628-cof_02484_005125.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04144

  2%|▏         | 11/500 [00:04<02:53,  2.82it/s]

🎧 CycleGAN-cof_02436_00360598628-cof_06136_003214.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10447

  2%|▏         | 12/500 [00:04<02:33,  3.18it/s]

🎧 CycleGAN-cof_02436_00360598628-cof_08784_016788.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10478

  3%|▎         | 13/500 [00:04<02:21,  3.44it/s]

🎧 CycleGAN-cof_02436_00733578342-cof_00610_016455.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06521

  3%|▎         | 14/500 [00:04<02:12,  3.66it/s]

🎧 CycleGAN-cof_02436_00733578342-cof_02484_012420.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04230

  3%|▎         | 15/500 [00:05<02:10,  3.73it/s]

🎧 CycleGAN-cof_02436_00733578342-cof_06136_018668.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09208

  3%|▎         | 16/500 [00:05<02:04,  3.89it/s]

🎧 CycleGAN-cof_02436_00733578342-cof_08784_007698.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08670

  3%|▎         | 17/500 [00:05<02:13,  3.63it/s]

🎧 CycleGAN-cof_02436_01306173906-cof_00610_011037.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06843

  4%|▎         | 18/500 [00:06<02:21,  3.41it/s]

🎧 CycleGAN-cof_02436_01306173906-cof_02484_010608.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04797

  4%|▍         | 19/500 [00:06<02:19,  3.45it/s]

🎧 CycleGAN-cof_02436_01306173906-cof_06136_020170.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12163

  4%|▍         | 20/500 [00:06<02:30,  3.19it/s]

🎧 CycleGAN-cof_02436_01306173906-cof_08784_009143.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.12801

  4%|▍         | 21/500 [00:07<02:36,  3.05it/s]

🎧 CycleGAN-cof_02436_01395350176-cof_00610_002101.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06896

  4%|▍         | 22/500 [00:07<02:44,  2.90it/s]

🎧 CycleGAN-cof_02436_01395350176-cof_02484_019500.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03428

  5%|▍         | 23/500 [00:07<02:39,  2.99it/s]

🎧 CycleGAN-cof_02436_01395350176-cof_06136_008334.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08210

  5%|▍         | 24/500 [00:08<02:43,  2.91it/s]

🎧 CycleGAN-cof_02436_01395350176-cof_08784_007856.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08157

  5%|▌         | 25/500 [00:08<02:48,  2.83it/s]

🎧 CycleGAN-cof_02436_01395350176-com_00610_014397.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.14229

  5%|▌         | 26/500 [00:08<02:38,  2.99it/s]

🎧 CycleGAN-cof_02436_01622222208-cof_00610_001379.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10193

  5%|▌         | 27/500 [00:09<02:44,  2.88it/s]

🎧 CycleGAN-cof_02436_01622222208-cof_02484_017436.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05996

  6%|▌         | 28/500 [00:09<02:50,  2.77it/s]

🎧 CycleGAN-cof_02436_01622222208-cof_06136_013806.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14307

  6%|▌         | 29/500 [00:09<02:48,  2.80it/s]

🎧 CycleGAN-cof_02436_01622222208-cof_08784_019605.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14710

  6%|▌         | 30/500 [00:10<02:54,  2.70it/s]

🎧 CycleGAN-cof_02436_01622222208-com_00610_017113.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.18752

  6%|▌         | 31/500 [00:10<02:52,  2.72it/s]

🎧 CycleGAN-cof_02436_01680222370-cof_00610_017193.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06195

  6%|▋         | 32/500 [00:10<02:32,  3.06it/s]

🎧 CycleGAN-cof_02436_01680222370-cof_02484_015816.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03683

  7%|▋         | 33/500 [00:11<02:18,  3.38it/s]

🎧 CycleGAN-cof_02436_01680222370-cof_06136_014632.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09691

  7%|▋         | 34/500 [00:11<02:08,  3.62it/s]

🎧 CycleGAN-cof_02436_01680222370-cof_08784_007955.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09058

  7%|▋         | 35/500 [00:11<02:04,  3.74it/s]

🎧 CycleGAN-cof_02436_01680222370-com_00610_008687.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.14710

  7%|▋         | 36/500 [00:11<01:57,  3.96it/s]

🎧 CycleGAN-cof_02436_01718184551-cof_00610_016829.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08146

  7%|▋         | 37/500 [00:12<01:53,  4.10it/s]

🎧 CycleGAN-cof_02436_01718184551-cof_02484_001055.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04931

  8%|▊         | 38/500 [00:12<01:49,  4.22it/s]

🎧 CycleGAN-cof_02436_01718184551-cof_06136_021051.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13575

  8%|▊         | 39/500 [00:12<01:46,  4.34it/s]

🎧 CycleGAN-cof_02436_01718184551-cof_08784_008615.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13418

  8%|▊         | 40/500 [00:12<01:47,  4.27it/s]

🎧 CycleGAN-cof_02436_01718184551-com_00610_017757.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.19266

  8%|▊         | 41/500 [00:12<01:46,  4.31it/s]

🎧 CycleGAN-cof_04310_01534630157-cof_00610_021233.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06182

  8%|▊         | 42/500 [00:13<01:46,  4.31it/s]

🎧 CycleGAN-cof_04310_01548249039-cof_00610_009870.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05685

  9%|▊         | 43/500 [00:13<01:43,  4.41it/s]

🎧 CycleGAN-cof_04310_01664914398-cof_00610_005819.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06414

  9%|▉         | 44/500 [00:13<01:43,  4.42it/s]

🎧 CycleGAN-cof_04310_01705476715-cof_00610_009519.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06658

  9%|▉         | 46/500 [00:14<01:41,  4.45it/s]

🎧 CycleGAN-cof_04310_01734349225-cof_00610_009338.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05235
🎧 CycleGAN-com_03397_00153070180-com_00610_016916.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09810

 10%|▉         | 48/500 [00:14<01:35,  4.74it/s]

🎧 CycleGAN-com_03397_00153070180-com_02436_011059.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06032
🎧 CycleGAN-com_03397_00153070180-com_04310_009166.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.02913

 10%|▉         | 49/500 [00:14<01:33,  4.82it/s]

🎧 CycleGAN-com_03397_00153070180-com_09334_014272.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.02921

 10%|█         | 50/500 [00:14<01:35,  4.73it/s]

🎧 CycleGAN-com_03397_00391015228-com_00610_017742.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.13197

 10%|█         | 51/500 [00:15<01:34,  4.75it/s]

🎧 CycleGAN-com_03397_00391015228-com_02436_011527.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08265

 10%|█         | 52/500 [00:15<01:34,  4.73it/s]

🎧 CycleGAN-com_03397_00391015228-com_04310_005438.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04027
🎧 CycleGAN-com_03397_00391015228-com_09334_007292.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04091

 11%|█         | 54/500 [00:15<01:40,  4.42it/s]

🎧 CycleGAN-com_03397_00495289763-com_00610_012269.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09802

 11%|█         | 55/500 [00:16<01:48,  4.09it/s]

🎧 CycleGAN-com_03397_00495289763-com_02436_014183.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06143

 11%|█         | 56/500 [00:16<01:52,  3.93it/s]

🎧 CycleGAN-com_03397_00495289763-com_04310_006265.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.02932

 11%|█▏        | 57/500 [00:16<01:55,  3.83it/s]

🎧 CycleGAN-com_03397_00495289763-com_09334_020584.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.02848

 12%|█▏        | 58/500 [00:16<01:50,  3.99it/s]

🎧 CycleGAN-com_03397_00671793720-com_00610_001516.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10135

 12%|█▏        | 59/500 [00:17<01:48,  4.08it/s]

🎧 CycleGAN-com_03397_00671793720-com_02436_013055.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06185

 12%|█▏        | 60/500 [00:17<01:44,  4.23it/s]

🎧 CycleGAN-com_03397_00671793720-com_04310_013128.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.02932

 12%|█▏        | 61/500 [00:17<01:41,  4.31it/s]

🎧 CycleGAN-com_03397_00671793720-com_09334_004505.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.02813

 12%|█▏        | 62/500 [00:17<01:39,  4.41it/s]

🎧 CycleGAN-com_03397_00984240661-com_00610_002593.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08097

 13%|█▎        | 63/500 [00:17<01:40,  4.36it/s]

🎧 CycleGAN-com_03397_00984240661-com_02436_013827.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04757

 13%|█▎        | 64/500 [00:18<01:37,  4.45it/s]

🎧 CycleGAN-com_03397_00984240661-com_04310_017610.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.02299

 13%|█▎        | 65/500 [00:18<01:35,  4.54it/s]

🎧 CycleGAN-com_03397_00984240661-com_09334_003473.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.02177

 13%|█▎        | 66/500 [00:18<01:35,  4.56it/s]

🎧 CycleGAN-com_03397_01345735056-com_00610_002565.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11070

 13%|█▎        | 67/500 [00:18<01:34,  4.58it/s]

🎧 CycleGAN-com_03397_01345735056-com_02436_007971.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07078

 14%|█▎        | 68/500 [00:19<01:37,  4.45it/s]

🎧 CycleGAN-com_03397_01345735056-com_04310_013674.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.03348

 14%|█▍        | 69/500 [00:19<01:36,  4.47it/s]

🎧 CycleGAN-com_03397_01345735056-com_09334_016670.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.03380

 14%|█▍        | 70/500 [00:19<01:34,  4.54it/s]

🎧 CycleGAN-com_03397_01422637121-com_00610_020542.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08248

 14%|█▍        | 71/500 [00:19<01:33,  4.59it/s]

🎧 CycleGAN-com_03397_01422637121-com_02436_000466.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05123

 14%|█▍        | 72/500 [00:19<01:32,  4.64it/s]

🎧 CycleGAN-com_03397_01422637121-com_04310_018677.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.02424

 15%|█▍        | 73/500 [00:20<01:33,  4.56it/s]

🎧 CycleGAN-com_03397_01422637121-com_09334_003807.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.02303

 15%|█▍        | 74/500 [00:20<01:31,  4.64it/s]

🎧 CycleGAN-com_03397_01519532274-com_00610_017084.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09156

 15%|█▌        | 75/500 [00:20<01:30,  4.70it/s]

🎧 CycleGAN-com_03397_01519532274-com_02436_010921.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05585

 15%|█▌        | 76/500 [00:20<01:38,  4.29it/s]

🎧 CycleGAN-com_03397_01519532274-com_04310_000367.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.02680

 15%|█▌        | 77/500 [00:21<01:54,  3.71it/s]

🎧 CycleGAN-com_03397_01519532274-com_09334_018293.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.02514

 16%|█▌        | 78/500 [00:21<02:04,  3.39it/s]

🎧 CycleGAN-com_03397_01536556841-com_00610_014120.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09436

 16%|█▌        | 79/500 [00:21<02:10,  3.24it/s]

🎧 CycleGAN-com_03397_01536556841-com_02436_004787.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.05699

 16%|█▌        | 80/500 [00:22<02:14,  3.13it/s]

🎧 CycleGAN-com_03397_01536556841-com_04310_007084.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.02723

 16%|█▌        | 81/500 [00:22<02:23,  2.91it/s]

🎧 CycleGAN-com_03397_01536556841-com_09334_004658.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.02549

 16%|█▋        | 82/500 [00:22<02:17,  3.04it/s]

🎧 CycleGAN-com_03397_02083059612-com_00610_019470.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09029

 17%|█▋        | 83/500 [00:23<02:11,  3.18it/s]

🎧 CycleGAN-com_03397_02083059612-com_02436_021214.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.05576

 17%|█▋        | 84/500 [00:23<02:06,  3.28it/s]

🎧 CycleGAN-com_03397_02083059612-com_04310_007894.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.02702

 17%|█▋        | 85/500 [00:23<02:12,  3.13it/s]

🎧 CycleGAN-com_03397_02083059612-com_09334_001822.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.02569

 17%|█▋        | 86/500 [00:24<02:21,  2.93it/s]

🎧 CycleGAN-com_08784_00747945674-com_00610_019871.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.21612

 17%|█▋        | 87/500 [00:24<02:22,  2.91it/s]

🎧 CycleGAN-com_08784_00866705887-com_00610_019543.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.19996

 18%|█▊        | 88/500 [00:24<02:22,  2.88it/s]

🎧 CycleGAN-com_08784_01573439386-com_00610_000842.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.20452

 18%|█▊        | 89/500 [00:25<02:32,  2.69it/s]

🎧 CycleGAN-com_08784_01642441049-com_00610_008168.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.18460

 18%|█▊        | 90/500 [00:25<02:30,  2.72it/s]

🎧 CycleGAN-com_08784_01684783873-com_00610_001516.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.19417

 18%|█▊        | 91/500 [00:25<02:13,  3.06it/s]

🎧 Diff-cof_00610_00155617852-cof_03397_0015483685.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10757

 18%|█▊        | 92/500 [00:26<02:00,  3.37it/s]

🎧 Diff-cof_00610_00155617852-cof_06136_0140986186.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.22888

 19%|█▊        | 93/500 [00:26<01:52,  3.63it/s]

🎧 Diff-cof_00610_00155617852-cof_08784_0129929867.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07589

 19%|█▉        | 95/500 [00:26<01:38,  4.11it/s]

🎧 Diff-cof_00610_00155617852-cof_09334_0117270978.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.18231
🎧 Diff-cof_00610_00158081190-cof_03397_0089927024.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07513

 19%|█▉        | 97/500 [00:27<01:29,  4.53it/s]

🎧 Diff-cof_00610_00158081190-cof_06136_0186688255.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10284
🎧 Diff-cof_00610_00158081190-cof_08784_0174310328.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.25497

 20%|█▉        | 98/500 [00:27<01:25,  4.68it/s]

🎧 Diff-cof_00610_00158081190-cof_09334_0050863880.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.07194

 20%|█▉        | 99/500 [00:27<01:27,  4.60it/s]

🎧 Diff-cof_00610_00444664843-cof_03397_0044696594.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14399

 20%|██        | 100/500 [00:27<01:26,  4.60it/s]

🎧 Diff-cof_00610_00444664843-cof_06136_0080745076.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15653

 20%|██        | 101/500 [00:28<01:26,  4.62it/s]

🎧 Diff-cof_00610_00444664843-cof_08784_0178758525.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.15805

 20%|██        | 102/500 [00:28<01:25,  4.64it/s]

🎧 Diff-cof_00610_00444664843-cof_09334_0046198134.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08194

 21%|██        | 103/500 [00:28<01:28,  4.50it/s]

🎧 Diff-cof_00610_00561353575-cof_03397_0044097123.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.04859

 21%|██        | 104/500 [00:28<01:31,  4.31it/s]

🎧 Diff-cof_00610_00561353575-cof_06136_0059271049.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03939

 21%|██        | 105/500 [00:29<01:31,  4.31it/s]

🎧 Diff-cof_00610_00561353575-cof_08784_0211073133.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.25233

 21%|██        | 106/500 [00:29<01:31,  4.33it/s]

🎧 Diff-cof_00610_00561353575-cof_09334_0141934040.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07910

 21%|██▏       | 107/500 [00:29<01:30,  4.36it/s]

🎧 Diff-cof_00610_00749562938-cof_03397_0091984475.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12556

 22%|██▏       | 108/500 [00:29<01:30,  4.32it/s]

🎧 Diff-cof_00610_00749562938-cof_06136_0003663539.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05359

 22%|██▏       | 109/500 [00:29<01:30,  4.30it/s]

🎧 Diff-cof_00610_00749562938-cof_08784_0129331080.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14160

 22%|██▏       | 110/500 [00:30<01:31,  4.25it/s]

🎧 Diff-cof_00610_00749562938-cof_09334_0127241222.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.03837

 22%|██▏       | 111/500 [00:30<01:31,  4.24it/s]

🎧 Diff-cof_00610_01034785289-cof_03397_0202093827.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.11186

 22%|██▏       | 112/500 [00:30<01:32,  4.21it/s]

🎧 Diff-cof_00610_01034785289-cof_06136_0198387608.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.03505

 23%|██▎       | 113/500 [00:30<01:34,  4.11it/s]

🎧 Diff-cof_00610_01034785289-cof_08784_0091433377.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.08320

 23%|██▎       | 115/500 [00:31<01:27,  4.38it/s]

🎧 Diff-cof_00610_01034785289-cof_09334_0066486683.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.25060
🎧 Diff-cof_00610_01307574255-cof_03397_0013951126.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.10682

 23%|██▎       | 117/500 [00:31<01:22,  4.65it/s]

🎧 Diff-cof_00610_01307574255-cof_06136_0059378057.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.03526
🎧 Diff-cof_00610_01307574255-cof_08784_0179488973.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.08760

 24%|██▎       | 118/500 [00:32<01:21,  4.68it/s]

🎧 Diff-cof_00610_01307574255-cof_09334_0205082724.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.08077

 24%|██▍       | 120/500 [00:32<01:19,  4.76it/s]

🎧 Diff-cof_00610_01332160527-cof_03397_0061287382.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.17553
🎧 Diff-cof_00610_01332160527-cof_06136_0168939491.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.08985

 24%|██▍       | 121/500 [00:32<01:19,  4.78it/s]

🎧 Diff-cof_00610_01332160527-cof_08784_0009124657.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05516

 24%|██▍       | 122/500 [00:32<01:18,  4.79it/s]

🎧 Diff-cof_00610_01332160527-cof_09334_0154891939.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06198

 25%|██▍       | 124/500 [00:33<01:17,  4.84it/s]

🎧 Diff-cof_00610_01398673747-cof_03397_0042088430.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15999
🎧 Diff-cof_00610_01398673747-cof_06136_0042673780.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.03834

 25%|██▌       | 126/500 [00:33<01:15,  4.96it/s]

🎧 Diff-cof_00610_01398673747-cof_08784_0164560055.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.22935
🎧 Diff-cof_00610_01398673747-cof_09334_0136423076.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.16675

 25%|██▌       | 127/500 [00:33<01:16,  4.88it/s]

🎧 Diff-cof_00610_01623396263-cof_03397_0115508741.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07263

 26%|██▌       | 128/500 [00:34<01:20,  4.65it/s]

🎧 Diff-cof_00610_01623396263-cof_06136_0166762008.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05968

 26%|██▌       | 129/500 [00:34<01:19,  4.66it/s]

🎧 Diff-cof_00610_01623396263-cof_08784_0077901315.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10842

 26%|██▌       | 130/500 [00:34<01:18,  4.69it/s]

🎧 Diff-cof_00610_01623396263-cof_09334_0011198998.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09859

 26%|██▌       | 131/500 [00:34<01:18,  4.71it/s]

🎧 Diff-cof_01523_00017388571-cof_03397_0119385628.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.15336

 26%|██▋       | 132/500 [00:34<01:18,  4.70it/s]

🎧 Diff-cof_01523_00017388571-cof_06136_0039349756.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07350

 27%|██▋       | 133/500 [00:35<01:20,  4.58it/s]

🎧 Diff-cof_01523_00017388571-cof_08784_0166976291.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07048

 27%|██▋       | 134/500 [00:35<01:19,  4.62it/s]

🎧 Diff-cof_01523_00017388571-cof_09334_0139100870.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05974

 27%|██▋       | 135/500 [00:35<01:20,  4.51it/s]

🎧 Diff-cof_01523_00162566952-cof_03397_0179483382.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13523

 27%|██▋       | 136/500 [00:35<01:32,  3.92it/s]

🎧 Diff-cof_01523_00162566952-cof_06136_0139456426.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07431

 27%|██▋       | 137/500 [00:36<01:47,  3.39it/s]

🎧 Diff-cof_01523_00162566952-cof_08784_0154593412.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12394

 28%|██▊       | 138/500 [00:36<01:58,  3.07it/s]

🎧 Diff-cof_01523_00162566952-cof_09334_0031127525.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.03563

 28%|██▊       | 139/500 [00:37<01:59,  3.01it/s]

🎧 Diff-cof_01523_00287301417-cof_03397_0018202330.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06513

 28%|██▊       | 140/500 [00:37<01:59,  3.02it/s]

🎧 Diff-cof_01523_00287301417-cof_06136_0138064158.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.03986

 28%|██▊       | 141/500 [00:37<01:50,  3.26it/s]

🎧 Diff-cof_01523_00287301417-cof_08784_0017503433.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09431

 28%|██▊       | 142/500 [00:37<01:49,  3.27it/s]

🎧 Diff-cof_01523_00287301417-cof_09334_0081920497.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06463

 29%|██▊       | 143/500 [00:38<01:49,  3.27it/s]

🎧 Diff-cof_01523_00491195227-cof_03397_0213234935.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10196

 29%|██▉       | 144/500 [00:38<01:50,  3.23it/s]

🎧 Diff-cof_01523_00491195227-cof_06136_0059728655.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.02559

 29%|██▉       | 145/500 [00:38<01:54,  3.10it/s]

🎧 Diff-cof_01523_00491195227-cof_08784_0045429384.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.07152

 29%|██▉       | 146/500 [00:39<02:00,  2.94it/s]

🎧 Diff-cof_01523_00491195227-cof_09334_0011685477.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.04702

 29%|██▉       | 147/500 [00:39<02:03,  2.85it/s]

🎧 Diff-cof_01523_00803058134-cof_03397_0130639404.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.17728

 30%|██▉       | 148/500 [00:40<02:08,  2.74it/s]

🎧 Diff-cof_01523_00803058134-cof_06136_0147088627.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06318

 30%|██▉       | 149/500 [00:40<02:12,  2.64it/s]

🎧 Diff-cof_01523_00803058134-cof_08784_0012921582.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09760

 30%|███       | 150/500 [00:40<02:10,  2.69it/s]

🎧 Diff-cof_01523_00803058134-cof_09334_0054033309.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11024

 30%|███       | 151/500 [00:41<01:56,  3.00it/s]

🎧 Diff-cof_01523_01199131701-cof_03397_0009690315.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.06367

 30%|███       | 152/500 [00:41<01:45,  3.31it/s]

🎧 Diff-cof_01523_01199131701-cof_06136_0045191048.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.08848

 31%|███       | 153/500 [00:41<01:38,  3.51it/s]

🎧 Diff-cof_01523_01199131701-cof_08784_0162030971.wav
   - Features extraídas: 575
   - Tempo: 208.33
   - RMSE manual: 0.04744

 31%|███       | 154/500 [00:41<01:32,  3.73it/s]

🎧 Diff-cof_01523_01199131701-cof_09334_0116010015.wav
   - Features extraídas: 575
   - Tempo: 208.33
   - RMSE manual: 0.05845

 31%|███       | 155/500 [00:42<01:28,  3.90it/s]

🎧 Diff-cof_01523_01297047509-cof_03397_0131607662.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05180

 31%|███       | 156/500 [00:42<01:25,  4.00it/s]

🎧 Diff-cof_01523_01297047509-cof_06136_0114322370.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.16752

 31%|███▏      | 157/500 [00:42<01:23,  4.11it/s]

🎧 Diff-cof_01523_01297047509-cof_08784_0093943398.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07882

 32%|███▏      | 158/500 [00:42<01:22,  4.14it/s]

🎧 Diff-cof_01523_01297047509-cof_09334_0013637451.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.04105

 32%|███▏      | 159/500 [00:42<01:19,  4.30it/s]

🎧 Diff-cof_01523_01318664847-cof_03397_0193407042.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10250

 32%|███▏      | 160/500 [00:43<01:17,  4.36it/s]

🎧 Diff-cof_01523_01318664847-cof_06136_0146327642.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07393

 32%|███▏      | 161/500 [00:43<01:16,  4.45it/s]

🎧 Diff-cof_01523_01318664847-cof_08784_0016935679.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07658

 32%|███▏      | 162/500 [00:43<01:14,  4.53it/s]

🎧 Diff-cof_01523_01318664847-cof_09334_0051878998.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10859

 33%|███▎      | 163/500 [00:43<01:19,  4.23it/s]

🎧 Diff-cof_01523_01911321218-cof_03397_0061287382.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.06192

 33%|███▎      | 164/500 [00:44<01:21,  4.14it/s]

🎧 Diff-cof_01523_01911321218-cof_06136_0051048826.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.05094

 33%|███▎      | 165/500 [00:44<01:22,  4.08it/s]

🎧 Diff-cof_01523_01911321218-cof_08784_0147517360.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.05122

 33%|███▎      | 166/500 [00:44<01:22,  4.05it/s]

🎧 Diff-cof_01523_01911321218-cof_09334_0138706379.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07134

 33%|███▎      | 167/500 [00:44<01:20,  4.12it/s]

🎧 Diff-cof_01523_02014850499-cof_03397_0172352763.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08099

 34%|███▎      | 168/500 [00:45<01:19,  4.19it/s]

🎧 Diff-cof_01523_02014850499-cof_06136_0143654051.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09971

 34%|███▍      | 169/500 [00:45<01:17,  4.28it/s]

🎧 Diff-cof_01523_02014850499-cof_08784_0209457101.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.17276

 34%|███▍      | 170/500 [00:45<01:16,  4.29it/s]

🎧 Diff-cof_01523_02014850499-cof_09334_0131309107.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.03445

 34%|███▍      | 171/500 [00:45<01:16,  4.32it/s]

🎧 Diff-com_02121_00055866196-com_02484_0085763625.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.12846

 34%|███▍      | 172/500 [00:46<01:16,  4.30it/s]

🎧 Diff-com_02121_00055866196-com_03397_0028670387.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11118

 35%|███▍      | 173/500 [00:46<01:14,  4.39it/s]

🎧 Diff-com_02121_00055866196-com_08784_0086073476.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.13532

 35%|███▍      | 174/500 [00:46<01:14,  4.40it/s]

🎧 Diff-com_02121_00055866196-com_09697_0029457407.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.02685

 35%|███▌      | 175/500 [00:46<01:14,  4.34it/s]

🎧 Diff-com_02121_00092301756-com_02484_0168217593.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.04858

 35%|███▌      | 176/500 [00:46<01:17,  4.20it/s]

🎧 Diff-com_02121_00092301756-com_03397_0054553643.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.13452

 35%|███▌      | 177/500 [00:47<01:16,  4.23it/s]

🎧 Diff-com_02121_00092301756-com_08784_0045376496.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.17621

 36%|███▌      | 178/500 [00:47<01:15,  4.24it/s]

🎧 Diff-com_02121_00092301756-com_09697_0051652043.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05441

 36%|███▌      | 179/500 [00:47<01:14,  4.29it/s]

🎧 Diff-com_02121_00740056573-com_02484_0094088807.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10555

 36%|███▌      | 180/500 [00:47<01:15,  4.24it/s]

🎧 Diff-com_02121_00740056573-com_03397_0196344001.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11835

 36%|███▌      | 181/500 [00:48<01:15,  4.24it/s]

🎧 Diff-com_02121_00740056573-com_08784_0108584834.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10678

 36%|███▋      | 182/500 [00:48<01:14,  4.28it/s]

🎧 Diff-com_02121_00740056573-com_09697_0014733619.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11044

 37%|███▋      | 183/500 [00:48<01:13,  4.31it/s]

🎧 Diff-com_02121_01170861108-com_02484_0049711515.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07488

 37%|███▋      | 184/500 [00:48<01:13,  4.29it/s]

🎧 Diff-com_02121_01170861108-com_03397_0122683242.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05672

 37%|███▋      | 185/500 [00:49<01:14,  4.25it/s]

🎧 Diff-com_02121_01170861108-com_08784_0011507616.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14760

 37%|███▋      | 186/500 [00:49<01:14,  4.23it/s]

🎧 Diff-com_02121_01170861108-com_09697_0163224310.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10390

 37%|███▋      | 187/500 [00:49<01:16,  4.10it/s]

🎧 Diff-com_02121_01256596109-com_02484_0131032960.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07795

 38%|███▊      | 188/500 [00:49<01:18,  4.00it/s]

🎧 Diff-com_02121_01256596109-com_03397_0121134432.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05122

 38%|███▊      | 189/500 [00:50<01:19,  3.90it/s]

🎧 Diff-com_02121_01256596109-com_08784_0036287663.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.13816

 38%|███▊      | 190/500 [00:50<01:21,  3.81it/s]

🎧 Diff-com_02121_01256596109-com_09697_0049980416.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08458

 38%|███▊      | 191/500 [00:50<01:17,  4.01it/s]

🎧 Diff-com_02121_01326190855-com_02484_0023315825.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.02911

 38%|███▊      | 192/500 [00:50<01:13,  4.17it/s]

🎧 Diff-com_02121_01326190855-com_03397_0079469967.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09253

 39%|███▊      | 193/500 [00:51<01:17,  3.97it/s]

🎧 Diff-com_02121_01326190855-com_08784_0014163279.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08130

 39%|███▉      | 194/500 [00:51<01:28,  3.46it/s]

🎧 Diff-com_02121_01326190855-com_09697_0066311509.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06696

 39%|███▉      | 195/500 [00:51<01:35,  3.21it/s]

🎧 Diff-com_02121_01715240584-com_02484_0101430602.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.06016

 39%|███▉      | 196/500 [00:52<01:37,  3.12it/s]

🎧 Diff-com_02121_01715240584-com_03397_0111214656.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.06938

 39%|███▉      | 197/500 [00:52<01:44,  2.91it/s]

🎧 Diff-com_02121_01715240584-com_08784_0109299797.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.12169

 40%|███▉      | 198/500 [00:52<01:49,  2.77it/s]

🎧 Diff-com_02121_01715240584-com_09697_0105629758.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.13648

 40%|███▉      | 199/500 [00:53<01:46,  2.83it/s]

🎧 Diff-com_02121_01809809142-com_02484_0012939601.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.21145

 40%|████      | 200/500 [00:53<01:47,  2.80it/s]

🎧 Diff-com_02121_01809809142-com_03397_0006392577.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.12788

 40%|████      | 201/500 [00:53<01:38,  3.02it/s]

🎧 Diff-com_02121_01809809142-com_08784_0212838863.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.15536

 40%|████      | 202/500 [00:54<01:33,  3.19it/s]

🎧 Diff-com_02121_01809809142-com_09697_0200093021.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.20877

 41%|████      | 203/500 [00:54<01:40,  2.95it/s]

🎧 Diff-com_02121_01818879615-com_02484_0157088217.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05104

 41%|████      | 204/500 [00:55<01:44,  2.82it/s]

🎧 Diff-com_02121_01818879615-com_03397_0106091960.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07728

 41%|████      | 205/500 [00:55<01:49,  2.70it/s]

🎧 Diff-com_02121_01818879615-com_08784_0148601772.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.03637

 41%|████      | 206/500 [00:55<01:54,  2.57it/s]

🎧 Diff-com_02121_01818879615-com_09697_0054161868.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.02340

 41%|████▏     | 207/500 [00:56<01:48,  2.69it/s]

🎧 Diff-com_02121_02073608306-com_02484_0118533204.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06832

 42%|████▏     | 208/500 [00:56<01:36,  3.03it/s]

🎧 Diff-com_02121_02073608306-com_03397_0150856269.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.02398

 42%|████▏     | 209/500 [00:56<01:27,  3.32it/s]

🎧 Diff-com_02121_02073608306-com_08784_0060645418.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.15649

 42%|████▏     | 210/500 [00:56<01:20,  3.59it/s]

🎧 Diff-com_02121_02073608306-com_09697_0145953998.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12101

 42%|████▏     | 211/500 [00:57<01:15,  3.85it/s]

🎧 Diff-com_02436_00254792024-com_02484_0049711515.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.02682

 42%|████▏     | 212/500 [00:57<01:11,  4.03it/s]

🎧 Diff-com_02436_00254792024-com_03397_0080471529.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04011

 43%|████▎     | 213/500 [00:57<01:09,  4.13it/s]

🎧 Diff-com_02436_00254792024-com_08784_0021371211.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.25528

 43%|████▎     | 214/500 [00:57<01:06,  4.28it/s]

🎧 Diff-com_02436_00254792024-com_09697_0014850634.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.11997

 43%|████▎     | 215/500 [00:57<01:04,  4.43it/s]

🎧 Diff-com_02436_00330898967-com_02484_0185735502.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05874

 43%|████▎     | 216/500 [00:58<01:02,  4.52it/s]

🎧 Diff-com_02436_00330898967-com_03397_0188938206.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.18443

 43%|████▎     | 217/500 [00:58<01:01,  4.59it/s]

🎧 Diff-com_02436_00330898967-com_08784_0020121861.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04153

 44%|████▎     | 218/500 [00:58<01:02,  4.50it/s]

🎧 Diff-com_02436_00330898967-com_09697_0042948854.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07412
🎧 Diff-com_02436_00669944333-com_02484_0113732683.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.10093

 44%|████▍     | 221/500 [00:59<00:58,  4.81it/s]

🎧 Diff-com_02436_00669944333-com_03397_0036060181.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.06982
🎧 Diff-com_02436_00669944333-com_08784_0099445683.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.02353

 44%|████▍     | 222/500 [00:59<00:57,  4.80it/s]

🎧 Diff-com_02436_00669944333-com_09697_0152173704.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.03995

 45%|████▍     | 223/500 [00:59<01:00,  4.59it/s]

🎧 Diff-com_02436_00772446157-com_02484_0213305141.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11791

 45%|████▍     | 224/500 [00:59<01:00,  4.58it/s]

🎧 Diff-com_02436_00772446157-com_03397_0078806516.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.08395

 45%|████▌     | 225/500 [01:00<01:00,  4.55it/s]

🎧 Diff-com_02436_00772446157-com_08784_0145925834.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.16854

 45%|████▌     | 226/500 [01:00<01:00,  4.53it/s]

🎧 Diff-com_02436_00772446157-com_09697_0171693532.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.20090

 45%|████▌     | 227/500 [01:00<00:59,  4.60it/s]

🎧 Diff-com_02436_01113680738-com_02484_0117484855.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.14903

 46%|████▌     | 228/500 [01:00<01:00,  4.48it/s]

🎧 Diff-com_02436_01113680738-com_03397_0023089983.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.12064

 46%|████▌     | 229/500 [01:00<01:00,  4.50it/s]

🎧 Diff-com_02436_01113680738-com_08784_0119025494.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.05151

 46%|████▌     | 230/500 [01:01<01:00,  4.49it/s]

🎧 Diff-com_02436_01113680738-com_09697_0101499470.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.03265

 46%|████▌     | 231/500 [01:01<00:59,  4.53it/s]

🎧 Diff-com_02436_01557457002-com_02484_0055953863.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.17868

 46%|████▋     | 232/500 [01:01<00:58,  4.58it/s]

🎧 Diff-com_02436_01557457002-com_03397_0078522470.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05513

 47%|████▋     | 233/500 [01:01<00:58,  4.54it/s]

🎧 Diff-com_02436_01557457002-com_08784_0149178815.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05399

 47%|████▋     | 234/500 [01:02<00:57,  4.60it/s]

🎧 Diff-com_02436_01557457002-com_09697_0113365686.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03320

 47%|████▋     | 235/500 [01:02<00:56,  4.66it/s]

🎧 Diff-com_02436_01691014862-com_02484_0155461412.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.13667

 47%|████▋     | 236/500 [01:02<00:56,  4.64it/s]

🎧 Diff-com_02436_01691014862-com_03397_0039101522.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10545
🎧 Diff-com_02436_01691014862-com_08784_0022818653.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.31610

 48%|████▊     | 238/500 [01:02<00:56,  4.63it/s]

🎧 Diff-com_02436_01691014862-com_09697_0214652136.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06725
🎧 Diff-com_02436_01809687779-com_02484_0195468578.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.03716

 48%|████▊     | 240/500 [01:03<00:54,  4.79it/s]

🎧 Diff-com_02436_01809687779-com_03397_0085438051.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06329

 48%|████▊     | 241/500 [01:03<00:53,  4.81it/s]

🎧 Diff-com_02436_01809687779-com_08784_0044005854.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06153
🎧 Diff-com_02436_01809687779-com_09697_0015050348.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06147

 49%|████▊     | 243/500 [01:03<00:53,  4.78it/s]

🎧 Diff-com_02436_01884995837-com_02484_0199685521.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.20701

 49%|████▉     | 244/500 [01:04<00:54,  4.71it/s]

🎧 Diff-com_02436_01884995837-com_03397_0109402348.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.03162

 49%|████▉     | 245/500 [01:04<00:54,  4.72it/s]

🎧 Diff-com_02436_01884995837-com_08784_0056709478.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.27488
🎧 Diff-com_02436_01884995837-com_09697_0046180067.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05479

 49%|████▉     | 247/500 [01:04<00:52,  4.81it/s]

🎧 Diff-com_02436_02031862691-com_02484_0094088807.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.03561

 50%|████▉     | 249/500 [01:05<00:51,  4.88it/s]

🎧 Diff-com_02436_02031862691-com_03397_0156652978.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12700
🎧 Diff-com_02436_02031862691-com_08784_0088896815.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.24625

 50%|█████     | 250/500 [01:05<00:51,  4.88it/s]

🎧 Diff-com_02436_02031862691-com_09697_0172450788.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09493

 50%|█████     | 251/500 [01:05<00:53,  4.65it/s]

🎧 StarGAN-cof_02436_00145881913-cof_00610_0074956.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09781

 50%|█████     | 252/500 [01:05<00:55,  4.51it/s]

🎧 StarGAN-cof_02436_00145881913-cof_02484_0048579.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10107

 51%|█████     | 253/500 [01:06<01:02,  3.95it/s]

🎧 StarGAN-cof_02436_00145881913-cof_03349_0140869.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09636

 51%|█████     | 254/500 [01:06<01:10,  3.48it/s]

🎧 StarGAN-cof_02436_00145881913-cof_06136_0056513.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09281

 51%|█████     | 255/500 [01:06<01:10,  3.46it/s]

🎧 StarGAN-cof_02436_00145881913-com_03397_0194571.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08842

 51%|█████     | 256/500 [01:07<01:19,  3.08it/s]

🎧 StarGAN-cof_02436_00145881913-com_05223_0096556.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10345

 51%|█████▏    | 257/500 [01:07<01:23,  2.91it/s]

🎧 StarGAN-cof_02436_00145881913-com_07508_0089809.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10201

 52%|█████▏    | 258/500 [01:08<01:27,  2.78it/s]

🎧 StarGAN-cof_02436_00145881913-com_08784_0040240.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10682

 52%|█████▏    | 259/500 [01:08<01:28,  2.71it/s]

🎧 StarGAN-cof_02436_00360598628-cof_00610_0123721.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07469

 52%|█████▏    | 260/500 [01:08<01:21,  2.93it/s]

🎧 StarGAN-cof_02436_00360598628-cof_02484_0145248.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07768

 52%|█████▏    | 261/500 [01:09<01:21,  2.93it/s]

🎧 StarGAN-cof_02436_00360598628-cof_03349_0063766.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07206

 52%|█████▏    | 262/500 [01:09<01:25,  2.78it/s]

🎧 StarGAN-cof_02436_00360598628-cof_06136_0059378.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07884

 53%|█████▎    | 263/500 [01:09<01:26,  2.73it/s]

🎧 StarGAN-cof_02436_00360598628-com_03397_0109402.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06909

 53%|█████▎    | 264/500 [01:10<01:28,  2.66it/s]

🎧 StarGAN-cof_02436_00360598628-com_05223_0135868.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08352

 53%|█████▎    | 265/500 [01:10<01:31,  2.56it/s]

🎧 StarGAN-cof_02436_00360598628-com_07508_0084960.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07574

 53%|█████▎    | 266/500 [01:10<01:24,  2.78it/s]

🎧 StarGAN-cof_02436_00360598628-com_08784_0204374.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08054

 53%|█████▎    | 267/500 [01:11<01:21,  2.87it/s]

🎧 StarGAN-cof_02436_00629767485-cof_00610_0000898.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08999

 54%|█████▎    | 268/500 [01:11<01:15,  3.08it/s]

🎧 StarGAN-cof_02436_00629767485-cof_02484_0047097.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09051

 54%|█████▍    | 269/500 [01:11<01:09,  3.34it/s]

🎧 StarGAN-cof_02436_00629767485-cof_03349_0177146.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08352

 54%|█████▍    | 270/500 [01:12<01:04,  3.57it/s]

🎧 StarGAN-cof_02436_00629767485-cof_06136_0059174.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08884

 54%|█████▍    | 271/500 [01:12<01:01,  3.72it/s]

🎧 StarGAN-cof_02436_00629767485-com_03397_0210804.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08540

 54%|█████▍    | 272/500 [01:12<01:00,  3.80it/s]

🎧 StarGAN-cof_02436_00629767485-com_05223_0117476.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11226

 55%|█████▍    | 273/500 [01:12<00:57,  3.91it/s]

🎧 StarGAN-cof_02436_00629767485-com_07508_0028095.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09748

 55%|█████▍    | 274/500 [01:13<00:56,  4.01it/s]

🎧 StarGAN-cof_02436_00629767485-com_08784_0037057.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10319

 55%|█████▌    | 275/500 [01:13<00:55,  4.08it/s]

🎧 StarGAN-cof_02436_01306793837-cof_00610_0068393.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08400

 55%|█████▌    | 276/500 [01:13<00:55,  4.05it/s]

🎧 StarGAN-cof_02436_01306793837-cof_02484_0109525.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08776

 55%|█████▌    | 277/500 [01:13<00:53,  4.14it/s]

🎧 StarGAN-cof_02436_01306793837-cof_03349_0091643.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09036

 56%|█████▌    | 278/500 [01:13<00:53,  4.18it/s]

🎧 StarGAN-cof_02436_01306793837-cof_06136_0186688.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08751

 56%|█████▌    | 279/500 [01:14<00:52,  4.22it/s]

🎧 StarGAN-cof_02436_01306793837-com_03397_0034811.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07909

 56%|█████▌    | 280/500 [01:14<00:51,  4.23it/s]

🎧 StarGAN-cof_02436_01306793837-com_05223_0123378.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09749

 56%|█████▌    | 281/500 [01:14<00:52,  4.20it/s]

🎧 StarGAN-cof_02436_01306793837-com_07508_0117500.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09735

 56%|█████▋    | 282/500 [01:14<00:51,  4.25it/s]

🎧 StarGAN-cof_02436_01306793837-com_08784_0186049.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10711

 57%|█████▋    | 283/500 [01:15<00:49,  4.35it/s]

🎧 StarGAN-cof_02436_01395350176-cof_00610_0148469.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08807

 57%|█████▋    | 284/500 [01:15<00:48,  4.41it/s]

🎧 StarGAN-cof_02436_01395350176-cof_02484_0175976.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08079

 57%|█████▋    | 285/500 [01:15<00:49,  4.35it/s]

🎧 StarGAN-cof_02436_01395350176-cof_03349_0096405.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07692

 57%|█████▋    | 286/500 [01:15<00:48,  4.38it/s]

🎧 StarGAN-cof_02436_01395350176-cof_06136_0186799.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08093

 57%|█████▋    | 287/500 [01:16<00:48,  4.41it/s]

🎧 StarGAN-cof_02436_01395350176-com_03397_0078416.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07590

 58%|█████▊    | 288/500 [01:16<00:47,  4.49it/s]

🎧 StarGAN-cof_02436_01395350176-com_05223_0132715.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09733

 58%|█████▊    | 289/500 [01:16<00:47,  4.41it/s]

🎧 StarGAN-cof_02436_01395350176-com_07508_0071111.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07811

 58%|█████▊    | 290/500 [01:16<00:48,  4.33it/s]

🎧 StarGAN-cof_02436_01395350176-com_08784_0144290.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10075

 58%|█████▊    | 291/500 [01:16<00:48,  4.30it/s]

🎧 StarGAN-cof_05223_01117638520-cof_00610_0135157.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09814

 58%|█████▊    | 292/500 [01:17<00:49,  4.19it/s]

🎧 StarGAN-cof_05223_01207015963-cof_00610_0045300.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06115

 59%|█████▊    | 293/500 [01:17<00:48,  4.30it/s]

🎧 StarGAN-cof_05223_01249220212-cof_00610_0059620.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08071

 59%|█████▉    | 294/500 [01:17<00:46,  4.43it/s]

🎧 StarGAN-cof_05223_01380056312-cof_00610_0057581.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.10406

 59%|█████▉    | 295/500 [01:17<00:47,  4.27it/s]

🎧 StarGAN-cof_05223_01849426663-cof_00610_0155494.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06911

 59%|█████▉    | 296/500 [01:18<00:46,  4.35it/s]

🎧 StarGAN-com_01523_00023325432-com_03397_0087007.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10115

 59%|█████▉    | 297/500 [01:18<00:46,  4.38it/s]

🎧 StarGAN-com_01523_00023325432-com_05223_0016528.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.14486

 60%|█████▉    | 298/500 [01:18<00:46,  4.37it/s]

🎧 StarGAN-com_01523_00023325432-com_07508_0024931.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10518

 60%|█████▉    | 299/500 [01:18<00:46,  4.34it/s]

🎧 StarGAN-com_01523_00023325432-com_08784_0022236.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.14070

 60%|██████    | 300/500 [01:19<00:46,  4.31it/s]

🎧 StarGAN-com_01523_00314453562-com_03397_0021943.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09343

 60%|██████    | 301/500 [01:19<00:46,  4.26it/s]

🎧 StarGAN-com_01523_00314453562-com_05223_0053336.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11385

 60%|██████    | 302/500 [01:19<00:46,  4.28it/s]

🎧 StarGAN-com_01523_00314453562-com_07508_0022325.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10510

 61%|██████    | 303/500 [01:19<00:45,  4.30it/s]

🎧 StarGAN-com_01523_00314453562-com_08784_0014163.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12001

 61%|██████    | 304/500 [01:19<00:46,  4.17it/s]

🎧 StarGAN-com_01523_00315309957-com_03397_0178613.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09524

 61%|██████    | 305/500 [01:20<00:46,  4.18it/s]

🎧 StarGAN-com_01523_00315309957-com_05223_0123378.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11271

 61%|██████    | 306/500 [01:20<00:46,  4.21it/s]

🎧 StarGAN-com_01523_00315309957-com_07508_0194702.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10114

 61%|██████▏   | 307/500 [01:20<00:45,  4.21it/s]

🎧 StarGAN-com_01523_00315309957-com_08784_0137185.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12222

 62%|██████▏   | 308/500 [01:20<00:46,  4.12it/s]

🎧 StarGAN-com_01523_00503563372-com_03397_0134573.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11796

 62%|██████▏   | 309/500 [01:21<00:46,  4.15it/s]

🎧 StarGAN-com_01523_00503563372-com_05223_0161097.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.14236

 62%|██████▏   | 310/500 [01:21<00:49,  3.81it/s]

🎧 StarGAN-com_01523_00503563372-com_07508_0040771.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.13126

 62%|██████▏   | 311/500 [01:21<00:58,  3.25it/s]

🎧 StarGAN-com_01523_00503563372-com_08784_0149178.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.14680

 62%|██████▏   | 312/500 [01:22<00:59,  3.17it/s]

🎧 StarGAN-com_01523_00546055786-com_03397_0063010.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09721

 63%|██████▎   | 313/500 [01:22<00:56,  3.32it/s]

🎧 StarGAN-com_01523_00546055786-com_05223_0204113.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.13234

 63%|██████▎   | 314/500 [01:22<01:00,  3.10it/s]

🎧 StarGAN-com_01523_00546055786-com_07508_0053848.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.11705

 63%|██████▎   | 315/500 [01:23<01:02,  2.96it/s]

🎧 StarGAN-com_01523_00546055786-com_08784_0025907.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14198

 63%|██████▎   | 316/500 [01:23<01:01,  2.97it/s]

🎧 StarGAN-com_01523_00872110638-com_03397_0002716.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07727

 63%|██████▎   | 317/500 [01:23<00:58,  3.14it/s]

🎧 StarGAN-com_01523_00872110638-com_05223_0102781.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10998

 64%|██████▎   | 318/500 [01:24<01:00,  2.99it/s]

🎧 StarGAN-com_01523_00872110638-com_07508_0126922.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08363

 64%|██████▍   | 319/500 [01:24<01:01,  2.93it/s]

🎧 StarGAN-com_01523_00872110638-com_08784_0095883.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11048

 64%|██████▍   | 320/500 [01:24<01:01,  2.92it/s]

🎧 StarGAN-com_01523_01365124566-com_03397_0150856.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08728

 64%|██████▍   | 321/500 [01:25<01:02,  2.87it/s]

🎧 StarGAN-com_01523_01365124566-com_05223_0012683.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10832

 64%|██████▍   | 322/500 [01:25<01:00,  2.96it/s]

🎧 StarGAN-com_01523_01365124566-com_07508_0093938.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09903

 65%|██████▍   | 323/500 [01:25<00:55,  3.17it/s]

🎧 StarGAN-com_01523_01365124566-com_08784_0111980.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09956

 65%|██████▍   | 324/500 [01:26<00:57,  3.06it/s]

🎧 StarGAN-com_01523_01556899942-com_03397_0206828.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10119

 65%|██████▌   | 325/500 [01:26<00:57,  3.05it/s]

🎧 StarGAN-com_01523_01556899942-com_05223_0181093.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.13452

 65%|██████▌   | 326/500 [01:26<00:50,  3.42it/s]

🎧 StarGAN-com_01523_01556899942-com_07508_0161424.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10666

 66%|██████▌   | 328/500 [01:27<00:42,  4.06it/s]

🎧 StarGAN-com_01523_01556899942-com_08784_0090219.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14054
🎧 StarGAN-com_01523_01655205076-com_03397_0197260.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08900

 66%|██████▌   | 330/500 [01:27<00:38,  4.45it/s]

🎧 StarGAN-com_01523_01655205076-com_05223_0189395.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10645
🎧 StarGAN-com_01523_01655205076-com_07508_0058957.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09640

 66%|██████▌   | 331/500 [01:27<00:36,  4.63it/s]

🎧 StarGAN-com_01523_01655205076-com_08784_0180378.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10974

 67%|██████▋   | 333/500 [01:28<00:35,  4.73it/s]

🎧 StarGAN-com_01523_01679133664-com_03397_0122683.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.09375
🎧 StarGAN-com_01523_01679133664-com_05223_0138911.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.13964

 67%|██████▋   | 334/500 [01:28<00:36,  4.50it/s]

🎧 StarGAN-com_01523_01679133664-com_07508_0143948.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.09906

 67%|██████▋   | 335/500 [01:28<00:35,  4.60it/s]

🎧 StarGAN-com_01523_01679133664-com_08784_0033465.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.14116

 67%|██████▋   | 336/500 [01:28<00:36,  4.47it/s]

🎧 StarGAN-com_04310_00857869313-com_03397_0161864.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06520

 67%|██████▋   | 337/500 [01:29<00:36,  4.48it/s]

🎧 StarGAN-com_04310_01463256198-com_03397_0125474.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.09400

 68%|██████▊   | 338/500 [01:29<00:36,  4.39it/s]

🎧 StarGAN-com_04310_01766019223-com_03397_0087007.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09697

 68%|██████▊   | 339/500 [01:29<00:38,  4.19it/s]

🎧 StarGAN-com_04310_01774205219-com_03397_0031642.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07065

 68%|██████▊   | 341/500 [01:30<00:34,  4.56it/s]

🎧 StarGAN-com_04310_02000246434-com_03397_0134573.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.05905
🎧 TTS-Diff-cof_00610_00158081190_TTS-cof_03397_01.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.21877

 68%|██████▊   | 342/500 [01:30<00:33,  4.67it/s]

🎧 TTS-Diff-cof_00610_00655967363_TTS-cof_04310_00.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.20045

 69%|██████▊   | 343/500 [01:30<00:33,  4.67it/s]

🎧 TTS-Diff-cof_00610_01647927814_TTS-cof_04310_01.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09050

 69%|██████▉   | 344/500 [01:30<00:33,  4.63it/s]

🎧 TTS-Diff-cof_01523_00364204205_TTS-com_07508_00.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.44199
🎧 TTS-Diff-cof_01523_00364204205_TTS-com_08784_01.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.17158

 69%|██████▉   | 346/500 [01:31<00:32,  4.79it/s]

🎧 TTS-Diff-cof_01523_00960018686_TTS-cof_06136_01.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.42670

 70%|██████▉   | 348/500 [01:31<00:31,  4.76it/s]

🎧 TTS-Diff-cof_01523_01420951365_TTS-cof_03397_00.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.03971
🎧 TTS-Diff-cof_01523_01583730156_TTS-cof_04310_02.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08166

 70%|███████   | 350/500 [01:31<00:31,  4.78it/s]

🎧 TTS-Diff-cof_01523_01665516790_TTS-cof_06136_00.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07081
🎧 TTS-Diff-cof_01523_01730918401_TTS-cof_05223_01.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14414

 70%|███████   | 352/500 [01:32<00:29,  5.09it/s]

🎧 TTS-Diff-cof_01523_01806955159_TTS-com_07508_01.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.13190
🎧 TTS-Diff-cof_01523_01869868652_TTS-com_02121_02.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.28952

 71%|███████   | 353/500 [01:32<00:28,  5.19it/s]

🎧 TTS-Diff-cof_01523_02048032351_TTS-cof_01523_01.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12498

 71%|███████   | 355/500 [01:32<00:28,  5.01it/s]

🎧 TTS-Diff-cof_02436_01072615731_TTS-com_09697_01.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.21080
🎧 TTS-Diff-cof_02484_00008039020_TTS-com_07508_02.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.33341

 71%|███████▏  | 357/500 [01:33<00:29,  4.91it/s]

🎧 TTS-Diff-cof_02484_01921144848_TTS-cof_03397_00.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.34011
🎧 TTS-Diff-cof_02484_02128604340_TTS-cof_05223_01.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08683

 72%|███████▏  | 358/500 [01:33<00:28,  4.94it/s]

🎧 TTS-Diff-cof_03034_00233774069_TTS-cof_04310_00.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.19852

 72%|███████▏  | 360/500 [01:33<00:28,  4.99it/s]

🎧 TTS-Diff-cof_03034_00689948160_TTS-cof_04310_00.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09318
🎧 TTS-Diff-cof_03034_00693994579_TTS-com_07508_01.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.37738

 72%|███████▏  | 362/500 [01:34<00:27,  5.00it/s]

🎧 TTS-Diff-com_00610_02054233665_TTS-cof_03397_00.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.14468
🎧 TTS-Diff-com_00610_02063882340_TTS-com_02121_01.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.16784

 73%|███████▎  | 364/500 [01:34<00:27,  5.01it/s]

🎧 TTS-Diff-com_01523_00673089408_TTS-com_09697_01.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.26233
🎧 TTS-Diff-com_01523_00991304268_TTS-com_08784_00.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.02511

 73%|███████▎  | 365/500 [01:34<00:28,  4.80it/s]

🎧 TTS-Diff-com_01523_01600687277_TTS-cof_05223_01.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.32173

 73%|███████▎  | 367/500 [01:35<00:27,  4.91it/s]

🎧 TTS-Diff-com_02121_00403218032_TTS-com_01523_02.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.20301
🎧 TTS-Diff-com_02121_00584037514_TTS-cof_06136_00.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08576

 74%|███████▍  | 369/500 [01:35<00:26,  5.01it/s]

🎧 TTS-Diff-com_02121_00624558942_TTS-com_08784_01.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.06739
🎧 TTS-Diff-com_02121_00787672012_TTS-cof_04310_01.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05373

 74%|███████▍  | 371/500 [01:36<00:26,  4.94it/s]

🎧 TTS-Diff-com_02121_00787672012_TTS-com_01523_01.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.22053
🎧 TTS-Diff-com_02121_00787672012_TTS-com_02121_01.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.02148

 74%|███████▍  | 372/500 [01:36<00:25,  5.06it/s]

🎧 TTS-Diff-com_02121_01658050388_TTS-cof_06136_01.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.22584

 75%|███████▍  | 373/500 [01:36<00:26,  4.72it/s]

🎧 TTS-Diff-com_02121_02122723128_TTS-cof_01523_02.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09489

 75%|███████▍  | 374/500 [01:36<00:30,  4.12it/s]

🎧 TTS-Diff-com_02436_01785523117_TTS-com_09697_01.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.21380

 75%|███████▌  | 375/500 [01:37<00:34,  3.59it/s]

🎧 TTS-Diff-com_02436_02056980305_TTS-com_02121_01.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10849

 75%|███████▌  | 376/500 [01:37<00:37,  3.30it/s]

🎧 TTS-Diff-com_03034_00081675596_TTS-cof_05223_00.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.12918

 75%|███████▌  | 377/500 [01:37<00:38,  3.16it/s]

🎧 TTS-Diff-com_03349_01510054374_TTS-cof_01523_00.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.01710

 76%|███████▌  | 378/500 [01:38<00:39,  3.06it/s]

🎧 TTS-Diff-com_04310_00044629618_TTS-cof_03397_02.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.29485

 76%|███████▌  | 379/500 [01:38<00:41,  2.92it/s]

🎧 TTS-Diff-com_04310_00338608959_TTS-com_09697_00.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.21987

 76%|███████▌  | 380/500 [01:38<00:37,  3.16it/s]

🎧 TTS-Diff-com_04310_02003610289_TTS-com_07508_01.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14666

 76%|███████▌  | 381/500 [01:39<00:37,  3.16it/s]

🎧 TTS-StarGAN-cof_00610_01606969510_TTS-cof_07508.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11839

 76%|███████▋  | 382/500 [01:39<00:39,  3.00it/s]

🎧 TTS-StarGAN-cof_01523_00295602931_TTS-cof_07508.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.11288

 77%|███████▋  | 383/500 [01:39<00:39,  2.99it/s]

🎧 TTS-StarGAN-cof_01523_00656220672_TTS-com_04310.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14407

 77%|███████▋  | 384/500 [01:40<00:38,  3.05it/s]

🎧 TTS-StarGAN-cof_01523_00950688215_TTS-cof_09697.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13985

 77%|███████▋  | 385/500 [01:40<00:35,  3.21it/s]

🎧 TTS-StarGAN-cof_01523_01029115021_TTS-cof_06136.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11899

 77%|███████▋  | 386/500 [01:40<00:33,  3.39it/s]

🎧 TTS-StarGAN-cof_01523_01029115021_TTS-cof_07508.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10920

 77%|███████▋  | 387/500 [01:41<00:32,  3.50it/s]

🎧 TTS-StarGAN-cof_01523_01583024640_TTS-cof_07508.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.10645

 78%|███████▊  | 388/500 [01:41<00:35,  3.14it/s]

🎧 TTS-StarGAN-cof_01523_01730918401_TTS-com_07049.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14182

 78%|███████▊  | 389/500 [01:41<00:33,  3.29it/s]

🎧 TTS-StarGAN-cof_01523_01966019149_TTS-cof_07508.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10051

 78%|███████▊  | 390/500 [01:41<00:30,  3.55it/s]

🎧 TTS-StarGAN-cof_01523_01979238963_TTS-com_08784.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.16140

 78%|███████▊  | 391/500 [01:42<00:28,  3.84it/s]

🎧 TTS-StarGAN-cof_02436_00073935569_TTS-com_03034.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.13360

 78%|███████▊  | 392/500 [01:42<00:26,  4.06it/s]

🎧 TTS-StarGAN-cof_02436_00833669679_TTS-com_09334.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.14046

 79%|███████▉  | 394/500 [01:42<00:24,  4.41it/s]

🎧 TTS-StarGAN-cof_02436_01021352124_TTS-cof_03397.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12054
🎧 TTS-StarGAN-cof_02436_02099975134_TTS-cof_03397.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.12052

 79%|███████▉  | 395/500 [01:42<00:22,  4.59it/s]

🎧 TTS-StarGAN-cof_02484_00353735337_TTS-com_08784.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.18186

 79%|███████▉  | 396/500 [01:43<00:22,  4.68it/s]

🎧 TTS-StarGAN-cof_02484_01155352236_TTS-cof_06136.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10428

 80%|███████▉  | 398/500 [01:43<00:21,  4.84it/s]

🎧 TTS-StarGAN-cof_03034_00503729338_TTS-cof_09697.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13696
🎧 TTS-StarGAN-cof_03034_00553866845_TTS-cof_06136.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10390

 80%|███████▉  | 399/500 [01:43<00:20,  4.93it/s]

🎧 TTS-StarGAN-cof_03034_01713215225_TTS-com_08784.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.15396

 80%|████████  | 400/500 [01:44<00:20,  4.80it/s]

🎧 TTS-StarGAN-cof_03349_00976532507_TTS-com_03034.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.13785

 80%|████████  | 401/500 [01:44<00:20,  4.81it/s]

🎧 TTS-StarGAN-com_00610_00761631502_TTS-cof_07508.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07578

 80%|████████  | 402/500 [01:44<00:20,  4.70it/s]

🎧 TTS-StarGAN-com_00610_01133611136_TTS-cof_01523.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08553

 81%|████████  | 403/500 [01:44<00:20,  4.67it/s]

🎧 TTS-StarGAN-com_00610_01357734740_TTS-com_07049.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10641

 81%|████████  | 405/500 [01:45<00:19,  4.78it/s]

🎧 TTS-StarGAN-com_02121_00750248256_TTS-cof_06136.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07687
🎧 TTS-StarGAN-com_02121_00787672012_TTS-com_09334.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08766

 81%|████████  | 406/500 [01:45<00:20,  4.69it/s]

🎧 TTS-StarGAN-com_02121_01523018450_TTS-cof_01523.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07372

 81%|████████▏ | 407/500 [01:45<00:20,  4.55it/s]

🎧 TTS-StarGAN-com_02436_00321718614_TTS-com_03034.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12402

 82%|████████▏ | 409/500 [01:45<00:19,  4.74it/s]

🎧 TTS-StarGAN-com_02436_00954839677_TTS-com_04310.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07628
🎧 TTS-StarGAN-com_03034_00173846424_TTS-cof_03397.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07671

 82%|████████▏ | 411/500 [01:46<00:18,  4.82it/s]

🎧 TTS-StarGAN-com_03034_01667122250_TTS-cof_01523.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07633
🎧 TTS-StarGAN-com_03034_02047985775_TTS-cof_01523.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06134

 82%|████████▏ | 412/500 [01:46<00:18,  4.80it/s]

🎧 TTS-StarGAN-com_03349_00369733152_TTS-cof_09697.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08823
🎧 TTS-StarGAN-com_03349_01146099126_TTS-com_04310.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10211

 83%|████████▎ | 415/500 [01:47<00:17,  4.89it/s]

🎧 TTS-StarGAN-com_03397_00780379824_TTS-cof_09697.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10015
🎧 TTS-StarGAN-com_03397_00990049800_TTS-com_09334.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12708

 83%|████████▎ | 416/500 [01:47<00:17,  4.82it/s]

🎧 TTS-StarGAN-com_04310_00338608959_TTS-cof_03397.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07718

 83%|████████▎ | 417/500 [01:47<00:17,  4.66it/s]

🎧 TTS-StarGAN-com_04310_01867791676_TTS-com_08784.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08464

 84%|████████▍ | 419/500 [01:48<00:17,  4.73it/s]

🎧 TTS-StarGAN-com_04310_01904025674_TTS-com_03034.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14053
🎧 TTS-StarGAN-com_05223_00598236981_TTS-cof_09697.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08467

 84%|████████▍ | 421/500 [01:48<00:16,  4.92it/s]

🎧 TTS-StarGAN-com_05223_01432857233_TTS-cof_06136.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08726
🎧 TTS-cof_00610_00158081190.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10009

 85%|████████▍ | 423/500 [01:48<00:15,  4.96it/s]

🎧 TTS-cof_00610_00191114113.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10239
🎧 TTS-cof_00610_00207818661.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08346

 85%|████████▌ | 425/500 [01:49<00:14,  5.17it/s]

🎧 TTS-cof_00610_00231725480.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.09600
🎧 TTS-cof_00610_00287921418.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.09152

 85%|████████▌ | 427/500 [01:49<00:14,  5.07it/s]

🎧 TTS-cof_00610_00543400472.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09756
🎧 TTS-cof_00610_00581998607.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08200

 86%|████████▌ | 429/500 [01:50<00:14,  4.88it/s]

🎧 TTS-cof_00610_00648896188.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10284
🎧 TTS-cof_00610_00655967363.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10042

 86%|████████▌ | 431/500 [01:50<00:13,  5.02it/s]

🎧 TTS-cof_00610_00686388841.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09234
🎧 TTS-cof_00610_00913180829.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10261

 86%|████████▋ | 432/500 [01:50<00:13,  5.07it/s]

🎧 TTS-cof_00610_00951906695.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10353

 87%|████████▋ | 433/500 [01:50<00:14,  4.78it/s]

🎧 TTS-cof_00610_01005920270.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10249

 87%|████████▋ | 435/500 [01:51<00:13,  4.75it/s]

🎧 TTS-cof_00610_01034785289.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10290
🎧 TTS-cof_00610_01067172216.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09834

 87%|████████▋ | 437/500 [01:51<00:12,  5.01it/s]

🎧 TTS-cof_00610_01122218651.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09036
🎧 TTS-cof_00610_01182042214.wav
   - Features extraídas: 575
   - Tempo: 81.52
   - RMSE manual: 0.10029

 88%|████████▊ | 438/500 [01:51<00:13,  4.46it/s]

🎧 TTS-cof_00610_01184239327.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09891

 88%|████████▊ | 439/500 [01:52<00:14,  4.13it/s]

🎧 TTS-cof_00610_01307574255.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08772

 88%|████████▊ | 440/500 [01:52<00:16,  3.71it/s]

🎧 TTS-cof_00610_01351577649.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.10941

 88%|████████▊ | 441/500 [01:52<00:17,  3.37it/s]

🎧 TTS-cof_00610_01365273195.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.10169

 88%|████████▊ | 442/500 [01:53<00:16,  3.43it/s]

🎧 TTS-cof_00610_01424711494.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11255

 89%|████████▊ | 443/500 [01:53<00:16,  3.56it/s]

🎧 TTS-cof_00610_01517257410.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09222

 89%|████████▉ | 444/500 [01:53<00:17,  3.22it/s]

🎧 TTS-cof_00610_01522609796.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09913

 89%|████████▉ | 445/500 [01:54<00:17,  3.09it/s]

🎧 TTS-cof_00610_01598240500.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10907

 89%|████████▉ | 446/500 [01:54<00:18,  2.99it/s]

🎧 TTS-cof_00610_01606969510.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09389

 89%|████████▉ | 447/500 [01:54<00:16,  3.13it/s]

🎧 TTS-cof_00610_01647927814.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.09979

 90%|████████▉ | 448/500 [01:55<00:17,  2.92it/s]

🎧 TTS-cof_00610_01717132249.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08920

 90%|████████▉ | 449/500 [01:55<00:17,  2.84it/s]

🎧 TTS-cof_00610_01719338902.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.09984

 90%|█████████ | 450/500 [01:55<00:17,  2.88it/s]

🎧 TTS-cof_00610_01768560254.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09337

 90%|█████████ | 451/500 [01:56<00:16,  2.93it/s]

🎧 TTS-cof_00610_01826783460.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09342

 90%|█████████ | 452/500 [01:56<00:15,  3.18it/s]

🎧 TTS-cof_00610_01860410978.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09518

 91%|█████████ | 453/500 [01:56<00:15,  3.04it/s]

🎧 TTS-cof_01523_00124064108.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09422

 91%|█████████ | 454/500 [01:57<00:14,  3.12it/s]

🎧 TTS-cof_01523_00263223799.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09591

 91%|█████████ | 456/500 [01:57<00:11,  3.78it/s]

🎧 TTS-cof_01523_00272438245.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10191
🎧 TTS-cof_01523_00295602931.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.10547

 92%|█████████▏| 458/500 [01:58<00:09,  4.35it/s]

🎧 TTS-cof_01523_00364204205.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09032
🎧 TTS-cof_01523_00552427428.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09122

 92%|█████████▏| 459/500 [01:58<00:08,  4.57it/s]

🎧 TTS-cof_01523_00656220672.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09690

 92%|█████████▏| 461/500 [01:58<00:08,  4.84it/s]

🎧 TTS-cof_01523_00683660831.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.11492
🎧 TTS-com_00610_00259350907.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07636

 92%|█████████▏| 462/500 [01:58<00:07,  5.02it/s]

🎧 TTS-com_00610_00535719087.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.09506

 93%|█████████▎| 464/500 [01:59<00:07,  4.92it/s]

🎧 TTS-com_00610_00540066680.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07097
🎧 TTS-com_00610_00761631502.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07644

 93%|█████████▎| 465/500 [01:59<00:06,  5.12it/s]

🎧 TTS-com_00610_00848224353.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09474
🎧 TTS-com_00610_00861650446.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08608

 94%|█████████▎| 468/500 [01:59<00:06,  5.12it/s]

🎧 TTS-com_00610_01079841693.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08269
🎧 TTS-com_00610_01133611136.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08779

 94%|█████████▍| 469/500 [02:00<00:06,  5.15it/s]

🎧 TTS-com_00610_01226934508.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.09914

 94%|█████████▍| 470/500 [02:00<00:05,  5.06it/s]

🎧 TTS-com_00610_01357734740.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08270

 94%|█████████▍| 472/500 [02:00<00:05,  4.96it/s]

🎧 TTS-com_00610_01448106783.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07612
🎧 TTS-com_00610_01503834738.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08186

 95%|█████████▍| 474/500 [02:01<00:05,  5.10it/s]

🎧 TTS-com_00610_01623387216.wav
   - Features extraídas: 575
   - Tempo: 78.12
   - RMSE manual: 0.10488
🎧 TTS-com_00610_01661261400.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07330

 95%|█████████▌| 475/500 [02:01<00:04,  5.17it/s]

🎧 TTS-com_00610_01691646053.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.09353

 95%|█████████▌| 477/500 [02:01<00:04,  5.08it/s]

🎧 TTS-com_00610_01752542331.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.08919
🎧 TTS-com_00610_01753570408.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08985

 96%|█████████▌| 479/500 [02:02<00:04,  5.14it/s]

🎧 TTS-com_00610_01899213381.wav
   - Features extraídas: 575
   - Tempo: 81.52
   - RMSE manual: 0.09760
🎧 TTS-com_00610_01947011444.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09623

 96%|█████████▌| 481/500 [02:02<00:03,  5.14it/s]

🎧 TTS-com_00610_01954361962.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08434
🎧 TTS-com_00610_02054233665.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10667

 97%|█████████▋| 483/500 [02:02<00:03,  4.92it/s]

🎧 TTS-com_00610_02063882340.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07965
🎧 TTS-com_01523_00010884441.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09569

 97%|█████████▋| 485/500 [02:03<00:03,  4.97it/s]

🎧 TTS-com_01523_00023844062.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.07338
🎧 TTS-com_01523_00139590753.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07751

 97%|█████████▋| 487/500 [02:03<00:02,  5.03it/s]

🎧 TTS-com_01523_00188955970.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.06948
🎧 TTS-com_01523_00220322993.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.08491

 98%|█████████▊| 488/500 [02:03<00:02,  4.87it/s]

🎧 TTS-com_01523_00314453562.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08111

 98%|█████████▊| 490/500 [02:04<00:02,  4.91it/s]

🎧 TTS-com_01523_00315309957.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07643
🎧 TTS-com_01523_00377642703.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07823

 98%|█████████▊| 491/500 [02:04<00:01,  5.00it/s]

🎧 TTS-com_01523_00461019966.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08278

 99%|█████████▊| 493/500 [02:05<00:01,  4.90it/s]

🎧 TTS-com_01523_00579025369.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08165
🎧 TTS-com_01523_00631006665.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08734

 99%|█████████▉| 495/500 [02:05<00:01,  4.99it/s]

🎧 TTS-com_01523_00660716568.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.08819
🎧 TTS-com_01523_00673089408.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08962

 99%|█████████▉| 496/500 [02:05<00:00,  5.09it/s]

🎧 TTS-com_01523_00685957576.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09119

100%|█████████▉| 498/500 [02:06<00:00,  5.01it/s]

🎧 TTS-com_01523_00819269643.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07479
🎧 TTS-com_01523_00822655651.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.08217

100%|██████████| 500/500 [02:06<00:00,  3.96it/s]

🎧 TTS-com_01523_00872110638.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09650
🎧 TTS-com_01523_00962087246.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08231

In [ ]:
print("\n Creando DataFrame...")

df = pd.DataFrame(registros)

print(" DataFrame creado")
print(f"   - Filas: {df.shape[0]}")
print(f"   - Columnas: {df.shape[1]}")

df.head()

 Creando DataFrame...
 DataFrame creado
   - Filas: 500
   - Columnas: 588

,id_audio,archivo,label,genero_f,colombiano,chileno,argentino,modelo_cyclegan,modelo_diff,modelo_stargan,...,rolloff_std,rolloff_min,rolloff_max,rolloff_median,rolloff_q1,rolloff_q3,rolloff_skew,rolloff_kurtosis,rolloff_mode,rolloff_iqr
0,1,CycleGAN-cof_02436_00052210902-cof_00610_01846...,1,1,1,0,0,1,0,0,...,1971.536037,789.0625,7562.5000,4183.59375,2037.109375,5710.937500,0.000705,-1.505250,1085.9375,3673.828125
1,2,CycleGAN-cof_02436_00052210902-cof_02484_00619...,1,1,1,0,0,1,0,0,...,2080.871242,554.6875,7539.0625,5492.18750,2152.343750,6203.125000,-0.451915,-1.419164,6304.6875,4050.781250
2,3,CycleGAN-cof_02436_00052210902-cof_06136_01525...,1,1,1,0,0,1,0,0,...,1965.394736,585.9375,7531.2500,4785.15625,1904.296875,5697.265625,-0.246978,-1.474301,1773.4375,3792.968750
3,4,CycleGAN-cof_02436_00052210902-cof_08784_01299...,1,1,1,0,0,1,0,0,...,1887.489328,601.5625,7468.7500,4789.06250,1978.515625,5585.937500,-0.261644,-1.407339,5585.9375,3607.421875
4,5,CycleGAN-cof_02436_00301724065-cof_00610_00648...,1,1,1,0,0,1,0,0,...,1878.109702,351.5625,7281.2500,4882.81250,2437.500000,5671.875000,-0.298326,-1.346327,1468.7500,3234.375000

In [ ]:
print("\n Distribución de labels:")
print(df["label"].value_counts())

print("\nProporciones:")
print(df["label"].value_counts(normalize=True))

 Distribución de labels:
label
1    500
Name: count, dtype: int64

Proporciones:
label
1    1.0
Name: proportion, dtype: float64

In [ ]:
#Revisar columnas
print("\n Información de columnas:")

print(f"Total columnas: {len(df.columns)}")

print("\nPrimeras 20 columnas:")
print(df.columns[:20])

print("\nÚltimas 20 columnas:")
print(df.columns[-20:])

 Información de columnas:
Total columnas: 588

Primeras 20 columnas:
Index(['id_audio', 'archivo', 'label', 'genero_f', 'colombiano', 'chileno',
       'argentino', 'modelo_cyclegan', 'modelo_diff', 'modelo_stargan',
       'modelo_tts_dif', 'modelo_tts_stargan', 'modelo_tts', 'duracion_seg',
       'zcr_mean', 'zcr_std', 'zcr_min', 'zcr_max', 'zcr_median', 'zcr_q1'],
      dtype='object')

Últimas 20 columnas:
Index(['flatness_min', 'flatness_max', 'flatness_median', 'flatness_q1',
       'flatness_q3', 'flatness_skew', 'flatness_kurtosis', 'flatness_mode',
       'flatness_iqr', 'rolloff_mean', 'rolloff_std', 'rolloff_min',
       'rolloff_max', 'rolloff_median', 'rolloff_q1', 'rolloff_q3',
       'rolloff_skew', 'rolloff_kurtosis', 'rolloff_mode', 'rolloff_iqr'],
      dtype='object')

In [ ]:
print("\n Información general del DataFrame:")
df.info()

 Información general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Columns: 588 entries, id_audio to rolloff_iqr
dtypes: float32(1), float64(574), int64(12), object(1)
memory usage: 2.2+ MB

In [ ]:
print("\n Estadísticas descriptivas:")
df.describe()

 Estadísticas descriptivas:

,id_audio,label,genero_f,colombiano,chileno,argentino,modelo_cyclegan,modelo_diff,modelo_stargan,modelo_tts_dif,...,rolloff_std,rolloff_min,rolloff_max,rolloff_median,rolloff_q1,rolloff_q3,rolloff_skew,rolloff_kurtosis,rolloff_mode,rolloff_iqr
count,500.000000,500.0,500.000000,500.0,500.0,500.0,500.000000,500.000000,500.000000,500.000000,...,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,250.500000,1.0,0.422000,1.0,0.0,0.0,0.180000,0.320000,0.180000,0.080000,...,1870.111740,511.921875,7239.218750,3589.734375,2118.132812,5232.843750,0.183033,-0.966562,2696.906250,3114.710938
std,144.481833,0.0,0.494373,0.0,0.0,0.0,0.384572,0.466943,0.384572,0.271565,...,213.235915,384.705693,327.829596,958.775987,510.565807,759.093836,0.506393,0.634523,1859.416679,814.784689
min,1.000000,1.0,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,956.765792,85.937500,5164.062500,1675.781250,1015.625000,2498.046875,-1.143836,-1.700453,117.187500,488.281250
25%,125.750000,1.0,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1749.434610,171.875000,7083.984375,2849.609375,1778.808594,4849.609375,-0.188963,-1.403751,1328.125000,2720.703125
50%,250.500000,1.0,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1887.491265,437.500000,7312.500000,3353.515625,2062.500000,5416.015625,0.144847,-1.172475,2117.187500,3209.960938
75%,375.250000,1.0,1.000000,1.0,0.0,0.0,0.000000,1.000000,0.000000,0.000000,...,2007.260652,773.437500,7460.937500,4444.335938,2393.066406,5762.695312,0.578675,-0.752437,4289.062500,3679.199219
max,500.000000,1.0,1.000000,1.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,...,2418.111770,2101.562500,7843.750000,5875.000000,4468.750000,7140.625000,1.557499,2.207138,7375.000000,5021.484375

In [ ]:
print("\n Inspección de una fila completa:")

fila = df.iloc[0]

print(fila)
print("\nTotal de valores en esta fila:", len(fila))

 Inspección de una fila completa:
id_audio                                                            1
archivo             CycleGAN-cof_02436_00052210902-cof_00610_01846...
label                                                               1
genero_f                                                            1
colombiano                                                          1
                                          ...
rolloff_q3                                                  5710.9375
rolloff_skew                                                 0.000705
rolloff_kurtosis                                             -1.50525
rolloff_mode                                                1085.9375
rolloff_iqr                                               3673.828125
Name: 0, Length: 588, dtype: object

Total de valores en esta fila: 588

In [ ]:
print("\n Guardando dataset...")

nombre_csv = f"dataset_features_{TIPO_DATASET}.csv"
ruta_salida_csv = f"/content/drive/MyDrive/Reto_Telefonica/{nombre_csv}"

df.to_csv(ruta_salida_csv, index=False)

print(" Dataset guardado correctamente")
print(f" Ruta: {ruta_salida_csv}")
print(f" Shape final: {df.shape}")

 Guardando dataset...
 Dataset guardado correctamente
 Ruta: /content/drive/MyDrive/Reto_Telefonica/dataset_features_sintetico.csv
 Shape final: (500, 588)

In [ ]:
print("\n Preparando descarga...")

from google.colab import files
files.download(ruta_salida_csv)

print(" Descarga iniciada")

 Preparando descarga...

 Descarga iniciada

In [ ]:
print("\n Guardando archivo auxiliar de etiquetas...")

df_labels = df[["id_audio", "archivo", "label"]]

ruta_labels = f"/content/drive/MyDrive/Reto_Telefonica/labels_{TIPO_DATASET}.csv"
df_labels.to_csv(ruta_labels, index=False)

print(" Archivo de labels guardado")
print(f" Ruta: {ruta_labels}")

df_labels.head()

 Guardando archivo auxiliar de etiquetas...
 Archivo de labels guardado
 Ruta: /content/drive/MyDrive/Reto_Telefonica/labels_sintetico.csv

   id_audio                                            archivo  label
0         1  CycleGAN-cof_02436_00052210902-cof_00610_01846...      1
1         2  CycleGAN-cof_02436_00052210902-cof_02484_00619...      1
2         3  CycleGAN-cof_02436_00052210902-cof_06136_01525...      1
3         4  CycleGAN-cof_02436_00052210902-cof_08784_01299...      1
4         5  CycleGAN-cof_02436_00301724065-cof_00610_00648...      1