#Reto IA: Telefonica challenge - Extracción de festures y creación de los CSV

Este documento contiene el flujo principal para transformar los archivos de audio crudos en datos estructurados listos para entrenar y testear los modelos.

Fases del proceso:
*  Carga de datos: Lectura de los audios de entrenamiento y validación.
*  Extracción y enriquecimiento: Cálculo de las features de audio y asignación de metadatos mediante una función automatizada.
*  Exportación: Guardado de los resultados definitivos en un archivo CSV, optimizado para su ingesta inmediata en un DataFrame.

Este pipeline se ha ejecutado en múltiples ocasiones a medida que se han ido incorporando nuevos audios para el análisi

# 0. Importación de librerías, connexión con drive y cargar áudios

In [ ]:
import numpy as np
import pandas as pd
import librosa
import os
from scipy import stats
from tqdm import tqdm
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
TIPO_DATASET = "sintetico"
ruta_carpeta = "/content/drive/MyDrive/Reto_Telefonica/audios_dataset_sint/Acento_Chileno_F-M/"

In [ ]:
print("Carpeta configurada:")
print(ruta_carpeta)

print("\n¿Existe la carpeta?:", os.path.exists(ruta_carpeta))

if os.path.exists(ruta_carpeta):
    print("\nPrimeros archivos encontrados:")
    print(os.listdir(ruta_carpeta)[:10])

Carpeta configurada:
/content/drive/MyDrive/Reto_Telefonica/audios_dataset_sint/Acento_Chileno_F-M/

¿Existe la carpeta?: True

Primeros archivos encontrados:
['CycleGAN-clf_05223_01102038735-clf_03397_019712.wav', 'CycleGAN-clf_05223_01948250535-clf_04310_009487.wav', 'CycleGAN-clf_05223_00086574876-clf_04310_016292.wav', 'CycleGAN-clf_05223_00571992422-clf_07049_007720.wav', 'CycleGAN-clf_05223_01578311399-clf_04310_000891.wav', 'CycleGAN-clf_05223_00759208930-clf_04310_020744.wav', 'CycleGAN-clf_05223_01601629897-clf_03397_014183.wav', 'CycleGAN-clf_05223_00571992422-clf_04310_014822.wav', 'CycleGAN-clf_05223_00759208930-clf_03397_002525.wav', 'CycleGAN-clf_05223_01601629897-clf_04310_004879.wav']

In [ ]:
#Cargar audios
archivos = os.listdir(ruta_carpeta)
print(f"Se detectaron {len(archivos)} archivos en la carpeta.\n")

for archivo in archivos:
    if archivo.lower().endswith(".wav"):
        ruta_audio = os.path.join(ruta_carpeta, archivo)

        y, sr = librosa.load(ruta_audio, sr=16000)

        print(f"{archivo} cargado | duración: {len(y)/sr:.2f} segundos")

Se detectaron 500 archivos en la carpeta.

CycleGAN-clf_05223_01102038735-clf_03397_019712.wav cargado | duración: 5.73 segundos
CycleGAN-clf_05223_01948250535-clf_04310_009487.wav cargado | duración: 7.61 segundos
CycleGAN-clf_05223_00086574876-clf_04310_016292.wav cargado | duración: 5.39 segundos
CycleGAN-clf_05223_00571992422-clf_07049_007720.wav cargado | duración: 4.45 segundos
CycleGAN-clf_05223_01578311399-clf_04310_000891.wav cargado | duración: 7.53 segundos
CycleGAN-clf_05223_00759208930-clf_04310_020744.wav cargado | duración: 5.31 segundos
CycleGAN-clf_05223_01601629897-clf_03397_014183.wav cargado | duración: 9.15 segundos
CycleGAN-clf_05223_00571992422-clf_04310_014822.wav cargado | duración: 4.45 segundos
CycleGAN-clf_05223_00759208930-clf_03397_002525.wav cargado | duración: 5.31 segundos
CycleGAN-clf_05223_01601629897-clf_04310_004879.wav cargado | duración: 9.15 segundos
CycleGAN-clf_05223_01692372116-clf_03397_002178.wav cargado | duración: 5.15 segundos
CycleGAN-clf_05223_00086574876-clf_07049_001473.wav cargado | duración: 5.39 segundos
CycleGAN-clf_05223_01578311399-clf_03397_003730.wav cargado | duración: 7.53 segundos
CycleGAN-clf_05223_00887476571-clf_07049_002971.wav cargado | duración: 7.27 segundos
CycleGAN-clf_05223_01948687797-clf_04310_001171.wav cargado | duración: 9.83 segundos
CycleGAN-clf_05223_00759208930-clf_07049_002494.wav cargado | duración: 5.31 segundos
CycleGAN-clf_05223_00571992422-clf_03397_008310.wav cargado | duración: 4.45 segundos
CycleGAN-clf_05223_01948687797-clf_03397_016539.wav cargado | duración: 9.83 segundos
CycleGAN-clf_05223_01102038735-clf_07049_020749.wav cargado | duración: 5.73 segundos
CycleGAN-clf_05223_01948250535-clf_03397_020448.wav cargado | duración: 7.61 segundos
CycleGAN-clf_05223_00887476571-clf_03397_003676.wav cargado | duración: 7.27 segundos
CycleGAN-clf_05223_01102038735-clf_04310_013030.wav cargado | duración: 5.73 segundos
CycleGAN-clf_05223_01692372116-clf_04310_011701.wav cargado | duración: 5.15 segundos
CycleGAN-clf_05223_00887476571-clf_04310_017406.wav cargado | duración: 7.27 segundos
CycleGAN-clf_05223_00086574876-clf_03397_013360.wav cargado | duración: 5.39 segundos
CycleGAN-clf_05223_01948250535-clf_07049_007914.wav cargado | duración: 7.61 segundos
CycleGAN-clf_05223_00086574876-clf_09697_009656.wav cargado | duración: 5.39 segundos
CycleGAN-clf_05223_01692372116-clf_07049_012608.wav cargado | duración: 5.15 segundos
CycleGAN-clf_05223_01948250535-clf_09697_003239.wav cargado | duración: 7.61 segundos
CycleGAN-clf_06136_01963409888-clf_03397_002525.wav cargado | duración: 9.41 segundos
CycleGAN-clf_05223_01948687797-clf_07049_020773.wav cargado | duración: 9.83 segundos
CycleGAN-clf_06136_00968508047-clf_03397_019574.wav cargado | duración: 9.33 segundos
CycleGAN-clf_05223_01692372116-clf_09697_006663.wav cargado | duración: 5.15 segundos
CycleGAN-clf_05223_01102038735-clf_09697_015169.wav cargado | duración: 5.73 segundos
CycleGAN-clf_06136_01757942488-clf_03397_007050.wav cargado | duración: 8.39 segundos
CycleGAN-clf_05223_01578311399-clf_07049_004062.wav cargado | duración: 7.53 segundos
CycleGAN-clf_05223_01948687797-clf_09697_005379.wav cargado | duración: 9.83 segundos
CycleGAN-clf_06136_01489700273-clf_03397_009334.wav cargado | duración: 6.51 segundos
CycleGAN-clf_05223_00887476571-clf_09697_010470.wav cargado | duración: 7.27 segundos
CycleGAN-clf_05223_00759208930-clf_09697_006111.wav cargado | duración: 5.31 segundos
CycleGAN-clf_05223_00571992422-clf_09697_019756.wav cargado | duración: 4.45 segundos
CycleGAN-clf_06136_01435825802-clf_03397_009747.wav cargado | duración: 6.17 segundos
CycleGAN-clf_05223_01601629897-clf_09697_010549.wav cargado | duración: 9.15 segundos
CycleGAN-clf_05223_01578311399-clf_09697_019489.wav cargado | duración: 7.53 segundos
CycleGAN-clf_05223_01601629897-clf_07049_016650.wav cargado | duración: 9.15 segundos
CycleGAN-clm_03034_00223642325-clm_02121_019465.wav cargado | duración: 5.73 segundos
CycleGAN-clm_03034_01181457087-clm_02121_008359.wav cargado | duración: 6.43 segundos
CycleGAN-clm_03034_01784318956-clm_02121_020610.wav cargado | duración: 9.07 segundos
CycleGAN-clm_03034_01208798223-clm_02121_010492.wav cargado | duración: 6.25 segundos
CycleGAN-clm_03034_00658805472-clm_02121_018786.wav cargado | duración: 5.15 segundos
CycleGAN-clm_03034_00522931279-clm_02121_018799.wav cargado | duración: 6.85 segundos
CycleGAN-clm_03034_01728660592-clm_02121_009881.wav cargado | duración: 5.83 segundos
CycleGAN-clm_03034_00746585521-clm_02121_008580.wav cargado | duración: 7.01 segundos
CycleGAN-clm_03034_01781920238-clm_02121_012444.wav cargado | duración: 6.85 segundos
CycleGAN-clm_03034_01781920238-clm_08421_013126.wav cargado | duración: 6.85 segundos
CycleGAN-clm_03034_01728660592-clm_08421_006528.wav cargado | duración: 5.83 segundos
CycleGAN-clm_03034_01181457087-clm_04310_015969.wav cargado | duración: 6.43 segundos
CycleGAN-clm_03034_01784318956-clm_07049_008731.wav cargado | duración: 9.07 segundos
CycleGAN-clm_03397_01842975985-clm_02121_016361.wav cargado | duración: 4.55 segundos
CycleGAN-clm_03034_01784318956-clm_04310_000234.wav cargado | duración: 9.07 segundos
CycleGAN-clm_03034_00746585521-clm_07049_019140.wav cargado | duración: 7.01 segundos
CycleGAN-clm_03034_00658805472-clm_08421_008868.wav cargado | duración: 5.15 segundos
CycleGAN-clm_03034_00746585521-clm_04310_004587.wav cargado | duración: 7.01 segundos
CycleGAN-clm_03034_00223642325-clm_04310_002989.wav cargado | duración: 5.73 segundos
CycleGAN-clm_03034_01728660592-clm_04310_007992.wav cargado | duración: 5.83 segundos
CycleGAN-clm_03034_00746585521-clm_08421_017687.wav cargado | duración: 7.01 segundos
CycleGAN-clm_03034_01208798223-clm_07049_007073.wav cargado | duración: 6.25 segundos
CycleGAN-clm_03034_00658805472-clm_04310_006498.wav cargado | duración: 5.15 segundos
CycleGAN-clm_03397_01778279941-clm_02121_014347.wav cargado | duración: 5.65 segundos
CycleGAN-clm_03034_01784318956-clm_08421_004336.wav cargado | duración: 9.07 segundos
CycleGAN-clm_03034_01728660592-clm_07049_019106.wav cargado | duración: 5.83 segundos
CycleGAN-clm_03397_02012774879-clm_02121_013999.wav cargado | duración: 5.65 segundos
CycleGAN-clm_03034_01181457087-clm_07049_004980.wav cargado | duración: 6.43 segundos
CycleGAN-clm_03034_01802784121-clm_07049_000671.wav cargado | duración: 5.73 segundos
CycleGAN-clm_03034_01802784121-clm_02121_005918.wav cargado | duración: 5.73 segundos
CycleGAN-clm_03034_01802784121-clm_08421_007628.wav cargado | duración: 5.73 segundos
CycleGAN-clm_03034_01802784121-clm_04310_014284.wav cargado | duración: 5.73 segundos
CycleGAN-clm_03034_00658805472-clm_07049_004536.wav cargado | duración: 5.15 segundos
CycleGAN-clm_03034_00522931279-clm_07049_020870.wav cargado | duración: 6.85 segundos
CycleGAN-clm_03034_00522931279-clm_04310_020654.wav cargado | duración: 6.85 segundos
CycleGAN-clm_03034_01781920238-clm_07049_013642.wav cargado | duración: 6.85 segundos
CycleGAN-clm_03034_01208798223-clm_08421_020517.wav cargado | duración: 6.25 segundos
CycleGAN-clm_03397_01764614541-clm_02121_002381.wav cargado | duración: 5.91 segundos
CycleGAN-clm_03034_00223642325-clm_07049_009911.wav cargado | duración: 5.73 segundos
CycleGAN-clm_03034_01781920238-clm_04310_017174.wav cargado | duración: 6.85 segundos
CycleGAN-clm_03034_01208798223-clm_04310_013012.wav cargado | duración: 6.25 segundos
CycleGAN-clm_03034_01181457087-clm_08421_003030.wav cargado | duración: 6.43 segundos
CycleGAN-clm_03034_00522931279-clm_08421_019874.wav cargado | duración: 6.85 segundos
CycleGAN-clm_03397_01585012436-clm_02121_020183.wav cargado | duración: 6.25 segundos
CycleGAN-clm_03034_00223642325-clm_08421_003892.wav cargado | duración: 5.73 segundos
Diff-clf_00610_01624352669-clf_07049_0181142112.wav cargado | duración: 6.99 segundos
Diff-clf_00610_00541921480-clf_01523_0000271886.wav cargado | duración: 9.55 segundos
Diff-clf_00610_01194622067-clf_07049_0177866312.wav cargado | duración: 6.65 segundos
Diff-clf_00610_00800782811-clf_05223_0011424356.wav cargado | duración: 8.53 segundos
Diff-clf_00610_01980026766-clf_01523_0036067739.wav cargado | duración: 8.44 segundos
Diff-clf_00610_00425819568-clf_05223_0070275794.wav cargado | duración: 9.72 segundos
Diff-clf_00610_00041705766-clf_07049_0018616364.wav cargado | duración: 7.42 segundos
Diff-clf_00610_00531398189-clf_05223_0085807635.wav cargado | duración: 10.66 segundos
Diff-clf_00610_00541921480-clf_09697_0183106620.wav cargado | duración: 9.55 segundos
Diff-clf_00610_01624352669-clf_09697_0140997269.wav cargado | duración: 6.99 segundos
Diff-clf_00610_00041705766-clf_01523_0179470137.wav cargado | duración: 7.42 segundos
Diff-clf_00610_01422471184-clf_01523_0115788745.wav cargado | duración: 8.44 segundos
Diff-clf_00610_01194622067-clf_09697_0205355989.wav cargado | duración: 6.65 segundos
Diff-clf_00610_00425819568-clf_07049_0123657859.wav cargado | duración: 9.72 segundos
Diff-clf_00610_00531398189-clf_07049_0189883332.wav cargado | duración: 10.66 segundos
Diff-clf_00610_01980026766-clf_05223_0110289558.wav cargado | duración: 8.44 segundos
Diff-clf_00610_00531398189-clf_01523_0207387070.wav cargado | duración: 10.66 segundos
Diff-clf_00610_00425819568-clf_09697_0010977496.wav cargado | duración: 9.72 segundos
Diff-clf_00610_01341150653-clf_07049_0059279001.wav cargado | duración: 7.50 segundos
Diff-clf_00610_00531398189-clf_09697_0046693667.wav cargado | duración: 10.66 segundos
Diff-clf_00610_01624352669-clf_01523_0011609557.wav cargado | duración: 6.99 segundos
Diff-clf_00610_00800782811-clf_09697_0157366854.wav cargado | duración: 8.53 segundos
Diff-clf_00610_00541921480-clf_07049_0021087815.wav cargado | duración: 9.55 segundos
Diff-clf_00610_01624352669-clf_05223_0173010537.wav cargado | duración: 6.99 segundos
Diff-clf_00610_01341150653-clf_09697_0010840718.wav cargado | duración: 7.50 segundos
Diff-clf_00610_01194622067-clf_01523_0024715228.wav cargado | duración: 6.65 segundos
Diff-clf_00610_01341150653-clf_05223_0089004159.wav cargado | duración: 7.50 segundos
Diff-clf_00610_00425819568-clf_01523_0073906580.wav cargado | duración: 9.72 segundos
Diff-clf_00610_00541921480-clf_05223_0048279294.wav cargado | duración: 9.55 segundos
Diff-clf_00610_01194622067-clf_05223_0168723603.wav cargado | duración: 6.65 segundos
Diff-clf_00610_01422471184-clf_05223_0005141554.wav cargado | duración: 8.44 segundos
Diff-clf_00610_00041705766-clf_05223_0200517343.wav cargado | duración: 7.42 segundos
Diff-clf_00610_01422471184-clf_07049_0004094925.wav cargado | duración: 8.44 segundos
Diff-clf_00610_01422471184-clf_09697_0061976278.wav cargado | duración: 8.44 segundos
Diff-clf_00610_01341150653-clf_01523_0105050848.wav cargado | duración: 7.50 segundos
Diff-clf_00610_00800782811-clf_01523_0084826109.wav cargado | duración: 8.53 segundos
Diff-clf_00610_00041705766-clf_09697_0157293666.wav cargado | duración: 7.42 segundos
Diff-clf_00610_01980026766-clf_07049_0179551984.wav cargado | duración: 8.44 segundos
Diff-clf_00610_00800782811-clf_07049_0057476618.wav cargado | duración: 8.53 segundos
Diff-clf_00610_01980026766-clf_09697_0178667393.wav cargado | duración: 8.44 segundos
Diff-clf_03397_01124427937-clf_01523_0026728360.wav cargado | duración: 3.06 segundos
Diff-clf_03397_01329926118-clf_01523_0036976828.wav cargado | duración: 3.15 segundos
Diff-clf_03397_01558221291-clf_05223_0029034304.wav cargado | duración: 3.15 segundos
Diff-clf_03397_01124427937-clf_05223_0173382939.wav cargado | duración: 3.06 segundos
Diff-clf_03397_01936219933-clf_01523_0203367484.wav cargado | duración: 5.54 segundos
Diff-clf_03397_00761403935-clf_05223_0168723603.wav cargado | duración: 5.20 segundos
Diff-clf_03397_02084497079-clf_01523_0209620610.wav cargado | duración: 5.63 segundos
Diff-clf_03397_02084497079-clf_05223_0184568426.wav cargado | duración: 5.63 segundos
Diff-clf_03397_00007216922-clf_09697_0048123925.wav cargado | duración: 7.16 segundos
Diff-clf_03397_00761403935-clf_01523_0021126251.wav cargado | duración: 5.20 segundos
Diff-clf_03397_01329926118-clf_05223_0015332209.wav cargado | duración: 3.15 segundos
Diff-clf_03397_00761403935-clf_07049_0122075267.wav cargado | duración: 5.20 segundos
Diff-clf_03397_01558221291-clf_07049_0024940648.wav cargado | duración: 3.15 segundos
Diff-clf_03397_00890001417-clf_01523_0102552215.wav cargado | duración: 6.30 segundos
Diff-clf_03397_00475591253-clf_05223_0089160532.wav cargado | duración: 3.49 segundos
Diff-clf_03397_00475591253-clf_01523_0158861966.wav cargado | duración: 3.49 segundos
Diff-clf_03397_00475591253-clf_07049_0006776033.wav cargado | duración: 3.49 segundos
Diff-clf_03397_01386651670-clf_01523_0077484245.wav cargado | duración: 3.49 segundos
Diff-clf_03397_01936219933-clf_07049_0122294255.wav cargado | duración: 5.54 segundos
Diff-clf_03397_00890001417-clf_05223_0173010537.wav cargado | duración: 6.30 segundos
Diff-clf_03397_01386651670-clf_05223_0040092737.wav cargado | duración: 3.49 segundos
Diff-clf_03397_02084497079-clf_07049_0200087503.wav cargado | duración: 5.63 segundos
Diff-clf_03397_01936219933-clf_05223_0137654768.wav cargado | duración: 5.54 segundos
Diff-clf_03397_00007216922-clf_01523_0128501192.wav cargado | duración: 7.16 segundos
Diff-clf_03397_00890001417-clf_07049_0099428190.wav cargado | duración: 6.30 segundos
Diff-clf_03397_01386651670-clf_07049_0082452816.wav cargado | duración: 3.49 segundos
Diff-clf_03397_01329926118-clf_07049_0004094925.wav cargado | duración: 3.15 segundos
Diff-clf_03397_00007216922-clf_07049_0203340025.wav cargado | duración: 7.16 segundos
Diff-clf_03397_00475591253-clf_09697_0206713486.wav cargado | duración: 3.49 segundos
Diff-clf_03397_01558221291-clf_01523_0168659927.wav cargado | duración: 3.15 segundos
Diff-clf_03397_01124427937-clf_07049_0195496062.wav cargado | duración: 3.06 segundos
Diff-clf_03397_00007216922-clf_05223_0075920893.wav cargado | duración: 7.16 segundos
Diff-clf_03397_02084497079-clf_09697_0114118106.wav cargado | duración: 5.63 segundos
Diff-clf_03397_01936219933-clf_09697_0057283493.wav cargado | duración: 5.54 segundos
Diff-clf_03397_00890001417-clf_09697_0061114857.wav cargado | duración: 6.30 segundos
Diff-clf_03397_01124427937-clf_09697_0208877913.wav cargado | duración: 3.06 segundos
Diff-clf_03397_01386651670-clf_09697_0194106148.wav cargado | duración: 3.49 segundos
Diff-clf_03397_01329926118-clf_09697_0151935015.wav cargado | duración: 3.15 segundos
Diff-clf_03397_01558221291-clf_09697_0129685471.wav cargado | duración: 3.15 segundos
Diff-clf_03397_00761403935-clf_09697_0133830442.wav cargado | duración: 5.20 segundos
Diff-clm_02121_00982290337-clm_05223_0197471922.wav cargado | duración: 11.85 segundos
Diff-clm_02121_01328510599-clm_06136_0099875710.wav cargado | duración: 8.10 segundos
Diff-clm_02121_00144740661-clm_06136_0138872060.wav cargado | duración: 9.04 segundos
Diff-clm_02121_01923437403-clm_01208_0090956492.wav cargado | duración: 7.59 segundos
Diff-clm_02121_01499208065-clm_01208_0201631551.wav cargado | duración: 7.93 segundos
Diff-clm_02121_01878637699-clm_06136_0166512684.wav cargado | duración: 8.01 segundos
Diff-clm_02121_01878637699-clm_05223_0207165762.wav cargado | duración: 8.01 segundos
Diff-clm_02121_01499208065-clm_05223_0213561683.wav cargado | duración: 7.93 segundos
Diff-clm_02121_01499208065-clm_06136_0010330382.wav cargado | duración: 7.93 segundos
Diff-clm_02121_00144740661-clm_01208_0133293225.wav cargado | duración: 9.04 segundos
Diff-clm_02121_00584464825-clm_01208_0083969432.wav cargado | duración: 5.12 segundos
Diff-clm_02121_01317943059-clm_06136_0158564555.wav cargado | duración: 7.16 segundos
Diff-clm_02121_01878637699-clm_01208_0088530317.wav cargado | duración: 8.01 segundos
Diff-clm_02121_00982290337-clm_00610_0001476160.wav cargado | duración: 11.85 segundos
Diff-clm_02121_01878637699-clm_00610_0027626301.wav cargado | duración: 8.01 segundos
Diff-clm_02121_00584464825-clm_00610_0102835083.wav cargado | duración: 5.12 segundos
Diff-clm_02121_01149397551-clm_05223_0209867529.wav cargado | duración: 11.77 segundos
Diff-clm_02121_01499208065-clm_00610_0005894809.wav cargado | duración: 7.93 segundos
Diff-clm_02121_00144740661-clm_00610_0060018021.wav cargado | duración: 9.04 segundos
Diff-clm_02121_01328510599-clm_05223_0030949096.wav cargado | duración: 8.10 segundos
Diff-clm_02121_01923437403-clm_06136_0026743692.wav cargado | duración: 7.59 segundos
Diff-clm_02121_00584464825-clm_05223_0059061317.wav cargado | duración: 5.12 segundos
Diff-clm_02121_01328510599-clm_00610_0084726239.wav cargado | duración: 8.10 segundos
Diff-clm_02121_01930296583-clm_01208_0122113124.wav cargado | duración: 5.97 segundos
Diff-clm_02121_01149397551-clm_00610_0207996888.wav cargado | duración: 11.77 segundos
Diff-clm_02121_00584464825-clm_06136_0038286730.wav cargado | duración: 5.12 segundos
Diff-clm_02121_01149397551-clm_01208_0200570787.wav cargado | duración: 11.77 segundos
Diff-clm_02121_00144740661-clm_05223_0049826934.wav cargado | duración: 9.04 segundos
Diff-clm_02121_00982290337-clm_06136_0145894666.wav cargado | duración: 11.85 segundos
Diff-clm_02121_01923437403-clm_05223_0109856605.wav cargado | duración: 7.59 segundos
Diff-clm_02121_01923437403-clm_00610_0097400416.wav cargado | duración: 7.59 segundos
Diff-clm_02121_01149397551-clm_06136_0096915804.wav cargado | duración: 11.77 segundos
Diff-clm_02121_00982290337-clm_01208_0201740975.wav cargado | duración: 11.85 segundos
Diff-clm_02121_01317943059-clm_05223_0014588025.wav cargado | duración: 7.16 segundos
Diff-clm_02121_01317943059-clm_01208_0182208027.wav cargado | duración: 7.16 segundos
Diff-clm_02121_01317943059-clm_00610_0019778812.wav cargado | duración: 7.16 segundos
Diff-clm_02121_01930296583-clm_05223_0097041920.wav cargado | duración: 5.97 segundos
Diff-clm_02121_01328510599-clm_01208_0078018650.wav cargado | duración: 8.10 segundos
Diff-clm_02121_01930296583-clm_06136_0212466005.wav cargado | duración: 5.97 segundos
Diff-clm_02121_01930296583-clm_00610_0034540814.wav cargado | duración: 5.97 segundos
Diff-clm_03349_02015822892-clm_05223_0159700406.wav cargado | duración: 4.26 segundos
Diff-clm_03349_01504548446-clm_06136_0197878989.wav cargado | duración: 6.73 segundos
Diff-clm_03349_00335831013-clm_00610_0157419130.wav cargado | duración: 5.46 segundos
Diff-clm_03349_01504548446-clm_01208_0038726715.wav cargado | duración: 6.73 segundos
Diff-clm_03349_00138186603-clm_01208_0088530317.wav cargado | duración: 8.27 segundos
Diff-clm_03349_00138186603-clm_06136_0107628126.wav cargado | duración: 8.27 segundos
Diff-clm_03349_00138186603-clm_05223_0097041920.wav cargado | duración: 8.27 segundos
Diff-clm_03349_01504548446-clm_00610_0075385555.wav cargado | duración: 6.73 segundos
Diff-clm_03349_01489548395-clm_06136_0054640934.wav cargado | duración: 7.16 segundos
Diff-clm_03349_00303377873-clm_05223_0076016195.wav cargado | duración: 3.83 segundos
Diff-clm_03349_00303377873-clm_01208_0137638611.wav cargado | duración: 3.83 segundos
Diff-clm_03349_01489548395-clm_05223_0008995161.wav cargado | duración: 7.16 segundos
Diff-clm_03349_01619891787-clm_05223_0061066243.wav cargado | duración: 7.59 segundos
Diff-clm_03349_02015822892-clm_01208_0201631551.wav cargado | duración: 4.26 segundos
Diff-clm_03349_01619891787-clm_06136_0195089880.wav cargado | duración: 7.59 segundos
Diff-clm_03349_00138186603-clm_00610_0027868898.wav cargado | duración: 8.27 segundos
Diff-clm_03349_01824880873-clm_05223_0001330418.wav cargado | duración: 4.60 segundos
Diff-clm_03349_01824880873-clm_01208_0075802629.wav cargado | duración: 4.60 segundos
Diff-clm_03349_02015822892-clm_06136_0148544231.wav cargado | duración: 4.26 segundos
Diff-clm_03349_00335831013-clm_06136_0015602334.wav cargado | duración: 5.46 segundos
Diff-clm_03349_00335831013-clm_05223_0139773380.wav cargado | duración: 5.46 segundos

# 1.0 Definición de funciones para extraer features

In [ ]:
#Generamos función para extraer sus atributos de unáudio a través de su nombre
def extraer_etiquetas(nombre_audio, modo="auto"):
    """
    Extrae etiquetas binarias desde el nombre del audio.

    Devuelve un diccionario con:
    - label: 0 real / 1 sintético
    - genero_f: 1 mujer / 0 hombre
    - nacionalidad: colombiano / chileno / argentino / peruano
    - modelo generador: CycleGAN, Diff, StarGAN, TTS-Dif, TTS-StarGAN, TTS
    """

    nombre = nombre_audio.lower()

    etiquetas = {
        # Label principal
        "label": 0,

        # 🔥 Género (solo una columna)
        "genero_f": 0,

        # Nacionalidad
        "colombiano": 0,
        "chileno": 0,
        "argentino": 0,
        "peruano":0,

        # Modelo generador
        "modelo_cyclegan": 0,
        "modelo_diff": 0,
        "modelo_stargan": 0,
        "modelo_tts_dif": 0,
        "modelo_tts_stargan": 0,
        "modelo_tts": 0
    }

    # -----------------------------
    # 1. Label principal
    # -----------------------------
    if modo == "real":
        etiquetas["label"] = 0
    elif modo == "sintetico":
        etiquetas["label"] = 1
    else:
        etiquetas["label"] = 1 if "-" in nombre_audio else 0

    # -----------------------------
    # 2. Nacionalidad + género
    # -----------------------------
    if "com" in nombre:
        etiquetas["colombiano"] = 1
        etiquetas["genero_f"] = 0

    elif "cof" in nombre:
        etiquetas["colombiano"] = 1
        etiquetas["genero_f"] = 1

    elif "clm" in nombre:
        etiquetas["chileno"] = 1
        etiquetas["genero_f"] = 0

    elif "clf" in nombre:
        etiquetas["chileno"] = 1
        etiquetas["genero_f"] = 1

    elif "arm" in nombre:
        etiquetas["argentino"] = 1
        etiquetas["genero_f"] = 0

    elif "arf" in nombre:
        etiquetas["argentino"] = 1
        etiquetas["genero_f"] = 1

    elif "pem" in nombre:
        etiquetas["peruano"] = 1
        etiquetas["genero_f"] = 0

    elif "pef" in nombre:
        etiquetas["peruano"] = 1
        etiquetas["genero_f"] = 1

    # -----------------------------
    # 3. Modelo generador
    # -----------------------------
    nombre_original = nombre_audio  # mantener mayúsculas

    if "TTS-StarGAN" in nombre_original:
        etiquetas["modelo_tts_stargan"] = 1
    elif "TTS-Dif" in nombre_original:
        etiquetas["modelo_tts_dif"] = 1
    elif "CycleGAN" in nombre_original:
        etiquetas["modelo_cyclegan"] = 1
    elif "StarGAN" in nombre_original:
        etiquetas["modelo_stargan"] = 1
    elif "Diff" in nombre_original:
        etiquetas["modelo_diff"] = 1
    elif "TTS" in nombre_original:
        etiquetas["modelo_tts"] = 1

    return etiquetas

In [ ]:
#Función para ejecutar la extración de etiquetas y guardarlo
def generar_df_etiquetas(ruta_carpeta, tipo_dataset="auto"):
    """
    Genera un DataFrame con múltiples etiquetas:
    - id_audio: identificador secuencial (1, 2, 3, ...)
    - archivo: nombre original del archivo
    - label: real (0) vs sintético (1)
    - genero_f: mujer (1), hombre (0)
    - nacionalidad: colombiano / chileno / argentino / peruano
    - modelo generador
    """

    print(f"Explorando carpeta: {ruta_carpeta}")
    datos = []

    contador_id = 1

    for archivo in sorted(os.listdir(ruta_carpeta)):
        if archivo.lower().endswith(".wav"):
            nombre_audio = archivo.replace(".wav", "")

            etiquetas = extraer_etiquetas(nombre_audio, modo=tipo_dataset)

            fila = {
                "id_audio": contador_id,
                "archivo": archivo
            }

            fila.update(etiquetas)
            datos.append(fila)

            contador_id += 1

    df_etiquetas = pd.DataFrame(datos)

    print(f"DataFrame creado con {len(df_etiquetas)} registros.")
    print(f"Número de columnas: {df_etiquetas.shape[1]}")

    return df_etiquetas

In [ ]:
df_labels = generar_df_etiquetas(ruta_carpeta, tipo_dataset=TIPO_DATASET)
df_labels.head()

Explorando carpeta: /content/drive/MyDrive/Reto_Telefonica/audios_dataset_sint/Acento_Chileno_F-M/
DataFrame creado con 500 registros.
Número de columnas: 14

,id_audio,archivo,label,genero_f,colombiano,chileno,argentino,peruano,modelo_cyclegan,modelo_diff,modelo_stargan,modelo_tts_dif,modelo_tts_stargan,modelo_tts
0,1,CycleGAN-clf_05223_00086574876-clf_03397_01336...,1,1,0,1,0,0,1,0,0,0,0,0
1,2,CycleGAN-clf_05223_00086574876-clf_04310_01629...,1,1,0,1,0,0,1,0,0,0,0,0
2,3,CycleGAN-clf_05223_00086574876-clf_07049_00147...,1,1,0,1,0,0,1,0,0,0,0,0
3,4,CycleGAN-clf_05223_00086574876-clf_09697_00965...,1,1,0,1,0,0,1,0,0,0,0,0
4,5,CycleGAN-clf_05223_00571992422-clf_03397_00831...,1,1,0,1,0,0,1,0,0,0,0,0

## 1.1 Extracción de features

Además de la extracción de etiquetas y metadatos —como la naturaleza real o sintética del audio, el género del locutor y el modelo generador utilizado—, el siguiente paso crítico es la extracción de las características acústicas (features). La selección y el procesamiento de estas métricas se fundamentan en la metodología descrita por Mael Fabien*, la cual detalla qué atributos de la señal de voz son los más idóneos para transformar el audio en datos estructurados y optimizados para modelos de Machine Learning


* https://maelfabien.github.io/machinelearning/Speech9/#7-mel-frequency-cepstral-differential-coefficients


A continuación, se detallan las características extraídas por cada archivo de audio:

1. Metadatos Temporales y de Ritmo
*  Duración (duracion_seg): El tiempo total del audio en segundos (tras eliminar los silencios iniciales y finales).
*  Tempo (tempo): Una estimación del ritmo del audio medido en pulsos por minuto (BPM). Ayuda a detectar si la cadencia del habla es natural.

2. Energía y Amplitud (Dominio del Tiempo)
*  ZCR (zcr - Zero Crossing Rate): Mide la tasa a la que la señal cambia de signo (de positivo a negativo). Es fundamental para identificar sonidos ruidosos o consonantes fricativas (como la "s" o la "f"), donde las IAs suelen cometer errores.
*  RMS (rms) y RMSE Manual (rmse_manual): Miden la energía de la raíz cuadrada media de la señal. En términos prácticos, representan el volumen percibido o la intensidad del audio. Se extrae tanto de forma automatizada (vía librosa) como mediante cálculo matemático directo.

3. Coeficientes Cepstrales (La "Huella Dactilar" de la Voz)
*  MFCC (mfcc_1 a mfcc_13): Los Coeficientes Cepstrales en las Frecuencias de Mel. Son 13 bandas que describen la "textura" o el timbre de la voz, modelando cómo el oído humano percibe el sonido.
*  Delta MFCC (delta_mfcc): La primera derivada (velocidad de cambio) de los MFCC. Indica cómo cambia el timbre de la voz de un instante a otro (transiciones entre fonemas).
*  Delta-Delta MFCC (delta2_mfcc): La segunda derivada (aceleración) de los MFCC. Captura variaciones aún más finas y rápidas en el habla, muy difíciles de replicar perfectamente por un modelo sintético.

4. Características Espectrales (Dominio de la Frecuencia)
*  Centroide Espectral (centroid): Representa el "centro de masa" del espectro. Determina si un sonido se percibe como "brillante" (frecuencias altas) u "opaco" (frecuencias bajas).
*  Ancho de Banda Espectral (bandwidth): Mide la dispersión de las frecuencias alrededor del centroide. Un ancho de banda artificialmente estrecho puede ser un claro indicio de compresión o generación por IA.
*  Contraste Espectral (contrast): Calcula la diferencia de amplitud entre los picos y los valles del espectro de frecuencias. Ayuda a distinguir sonidos armónicos de ruidos de fondo.
*  Planitud Espectral (flatness): Mide qué tan similar al "ruido blanco" es un sonido. Valores altos indican ruido (sin tono claro), mientras que valores bajos indican un sonido tonal (como una vocal clara).
*  Rolloff Espectral (rolloff): Representa la frecuencia por debajo de la cual se concentra el 85% de la energía del audio. Es muy útil para detectar si un modelo generativo ha aplicado cortes artificiales en las frecuencias más agudas.

In [ ]:
#Función de extracción de features
def extraer_features(ruta_audio, sr_objetivo=16000, n_mfcc=13):
    """
    Extrae features de un audio y devuelve un diccionario.
    """

    y, sr = librosa.load(ruta_audio, sr=sr_objetivo)

    # Recorte de silencios
    y, _ = librosa.effects.trim(y)

    if len(y) < 512:
        return None

    features = {}

    # -------------------
    # META
    # -------------------
    features["duracion_seg"] = len(y) / sr

    # -------------------
    # ZCR
    # -------------------
    zcr = librosa.feature.zero_crossing_rate(y)[0]
    features.update(resumir_feature(zcr, "zcr"))

    # -------------------
    # RMS (librosa)
    # -------------------
    rms = librosa.feature.rms(y=y)[0]
    features.update(resumir_feature(rms, "rms"))

    # -------------------
    # RMSE manual
    # -------------------
    rmse_manual = np.sqrt(np.mean(y**2))
    features["rmse_manual"] = rmse_manual

    # -------------------
    # TEMPO
    # -------------------
    tempo = librosa.beat.tempo(y=y, sr=sr)[0]
    features["tempo"] = tempo

    # -------------------
    # MFCC
    # -------------------
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
    for i in range(n_mfcc):
        features.update(resumir_feature(mfcc[i], f"mfcc_{i+1}"))

    # -------------------
    # DELTA MFCC
    # -------------------
    delta_mfcc = librosa.feature.delta(mfcc)
    for i in range(n_mfcc):
        features.update(resumir_feature(delta_mfcc[i], f"delta_mfcc_{i+1}"))

    # -------------------
    # DELTA-DELTA MFCC
    # -------------------
    delta2_mfcc = librosa.feature.delta(mfcc, order=2)
    for i in range(n_mfcc):
        features.update(resumir_feature(delta2_mfcc[i], f"delta2_mfcc_{i+1}"))

    # -------------------
    # SPECTRAL FEATURES
    # -------------------
    centroid = librosa.feature.spectral_centroid(y=y, sr=sr)[0]
    features.update(resumir_feature(centroid, "centroid"))

    bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=sr)[0]
    features.update(resumir_feature(bandwidth, "bandwidth"))

    contrast = librosa.feature.spectral_contrast(y=y, sr=sr)
    for i in range(contrast.shape[0]):
        features.update(resumir_feature(contrast[i], f"contrast_{i+1}"))

    flatness = librosa.feature.spectral_flatness(y=y)[0]
    features.update(resumir_feature(flatness, "flatness"))

    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)[0]
    features.update(resumir_feature(rolloff, "rolloff"))

    # -------------------
    # PRINT FINAL
    # -------------------
    print(f"🎧 {os.path.basename(ruta_audio)}")
    print(f"   - Features extraídas: {len(features)}")
    print(f"   - Tempo: {tempo:.2f}")
    print(f"   - RMSE manual: {rmse_manual:.5f}")

    return features

Dado que el sonido es una señal dinámica que cambia a lo largo del tiempo, extraer un único valor estático no proporciona información suficiente. Por ello, la gran mayoría de estas métricas las procesamos mediante una función de resumen que extrae 11 estadísticas descriptivas para cada variable temporal: media, desviación estándar, mínimo, máximo, mediana, cuartiles (Q1 y Q3), asimetría (skewness), curtosis, moda y rango intercuartílico (IQR). Esto nos permite capturar no solo el tono promedio del audio, sino también la micro-variabilidad y las posibles anomalías matemáticas que suelen dejar los algoritmos de IA al generar voces falsas.

In [ ]:
#Función generación estadísticas de las features
def resumir_feature(vector, prefijo, debug=False):
    vector = np.asarray(vector).astype(float)

    if len(vector) == 0:
        return {}

    resultado = {
        f"{prefijo}_mean": np.mean(vector),
        f"{prefijo}_std": np.std(vector),
        f"{prefijo}_min": np.min(vector),
        f"{prefijo}_max": np.max(vector),
        f"{prefijo}_median": np.median(vector),
        f"{prefijo}_q1": np.quantile(vector, 0.25),
        f"{prefijo}_q3": np.quantile(vector, 0.75),
        f"{prefijo}_skew": stats.skew(vector),
        f"{prefijo}_kurtosis": stats.kurtosis(vector),
        f"{prefijo}_mode": stats.mode(vector, keepdims=True)[0][0],
        f"{prefijo}_iqr": stats.iqr(vector)
    }

    if debug:
        print(f"\n🔍 Feature: {prefijo}")
        print(f"   Total valores generados: {len(resultado)}")
        for k, v in list(resultado.items())[:3]:
            print(f"   {k}: {v:.4f}")

    return resultado

#2.0 Ejecución de las funciones

In [ ]:
registros = []

archivos_wav = sorted([a for a in os.listdir(ruta_carpeta) if a.lower().endswith(".wav")])

for idx, archivo in enumerate(tqdm(archivos_wav), start=1):
    ruta_audio = os.path.join(ruta_carpeta, archivo)
    nombre_audio = archivo.replace(".wav", "")

    try:
        etiquetas = extraer_etiquetas(nombre_audio, modo=TIPO_DATASET)
        feats = extraer_features(ruta_audio)

        if feats is None:
            print(f"Audio omitido por ser demasiado corto: {archivo}")
            continue

        fila = {
            "id_audio": idx,
            "archivo": archivo
        }

        fila.update(etiquetas)
        fila.update(feats)

        registros.append(fila)

    except Exception as e:
        print(f"Error procesando {archivo}: {e}")

  0%|          | 0/500 [00:00<?, ?it/s]/tmp/ipykernel_2955/2322890922.py:43: FutureWarning: librosa.beat.tempo
	This function was moved to 'librosa.feature.rhythm.tempo' in librosa version 0.10.0.
	This alias will be removed in librosa version 1.0.
  tempo = librosa.beat.tempo(y=y, sr=sr)[0]
  0%|          | 1/500 [00:17<2:26:42, 17.64s/it]

🎧 CycleGAN-clf_05223_00086574876-clf_03397_013360.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09616

  0%|          | 2/500 [00:17<1:01:29,  7.41s/it]

🎧 CycleGAN-clf_05223_00086574876-clf_04310_016292.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06964

  1%|          | 3/500 [00:18<34:16,  4.14s/it]

🎧 CycleGAN-clf_05223_00086574876-clf_07049_001473.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.02680

  1%|          | 4/500 [00:18<21:30,  2.60s/it]

🎧 CycleGAN-clf_05223_00086574876-clf_09697_009656.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05258

  1%|          | 5/500 [00:18<14:25,  1.75s/it]

🎧 CycleGAN-clf_05223_00571992422-clf_03397_008310.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10362

  1%|          | 6/500 [00:18<10:11,  1.24s/it]

🎧 CycleGAN-clf_05223_00571992422-clf_04310_014822.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08071

  1%|▏         | 7/500 [00:19<07:28,  1.10it/s]

🎧 CycleGAN-clf_05223_00571992422-clf_07049_007720.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.02943

  2%|▏         | 8/500 [00:19<05:39,  1.45it/s]

🎧 CycleGAN-clf_05223_00571992422-clf_09697_019756.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06146

  2%|▏         | 9/500 [00:19<04:30,  1.82it/s]

🎧 CycleGAN-clf_05223_00759208930-clf_03397_002525.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08289

  2%|▏         | 10/500 [00:19<03:46,  2.17it/s]

🎧 CycleGAN-clf_05223_00759208930-clf_04310_020744.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06629

  2%|▏         | 11/500 [00:20<03:14,  2.52it/s]

🎧 CycleGAN-clf_05223_00759208930-clf_07049_002494.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.02511

  2%|▏         | 12/500 [00:20<02:51,  2.84it/s]

🎧 CycleGAN-clf_05223_00759208930-clf_09697_006111.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05026

  3%|▎         | 13/500 [00:20<02:38,  3.08it/s]

🎧 CycleGAN-clf_05223_00887476571-clf_03397_003676.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.08599

  3%|▎         | 14/500 [00:20<02:30,  3.24it/s]

🎧 CycleGAN-clf_05223_00887476571-clf_04310_017406.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06905

  3%|▎         | 15/500 [00:21<02:23,  3.39it/s]

🎧 CycleGAN-clf_05223_00887476571-clf_07049_002971.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.02573

  3%|▎         | 16/500 [00:21<02:18,  3.51it/s]

🎧 CycleGAN-clf_05223_00887476571-clf_09697_010470.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05203

  3%|▎         | 17/500 [00:21<02:11,  3.67it/s]

🎧 CycleGAN-clf_05223_01102038735-clf_03397_019712.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09127

  4%|▎         | 18/500 [00:21<02:08,  3.76it/s]

🎧 CycleGAN-clf_05223_01102038735-clf_04310_013030.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07270

  4%|▍         | 19/500 [00:22<02:05,  3.84it/s]

🎧 CycleGAN-clf_05223_01102038735-clf_07049_020749.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.02799

  4%|▍         | 20/500 [00:22<02:03,  3.89it/s]

🎧 CycleGAN-clf_05223_01102038735-clf_09697_015169.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05243

  4%|▍         | 21/500 [00:22<02:04,  3.84it/s]

🎧 CycleGAN-clf_05223_01578311399-clf_03397_003730.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07245

  4%|▍         | 22/500 [00:22<02:07,  3.76it/s]

🎧 CycleGAN-clf_05223_01578311399-clf_04310_000891.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05630

  5%|▍         | 23/500 [00:23<02:06,  3.76it/s]

🎧 CycleGAN-clf_05223_01578311399-clf_07049_004062.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.02162

  5%|▍         | 24/500 [00:23<02:06,  3.76it/s]

🎧 CycleGAN-clf_05223_01578311399-clf_09697_019489.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04291

  5%|▌         | 25/500 [00:23<02:08,  3.68it/s]

🎧 CycleGAN-clf_05223_01601629897-clf_03397_014183.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09689

  5%|▌         | 26/500 [00:24<02:11,  3.60it/s]

🎧 CycleGAN-clf_05223_01601629897-clf_04310_004879.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07481

  5%|▌         | 27/500 [00:24<02:31,  3.11it/s]

🎧 CycleGAN-clf_05223_01601629897-clf_07049_016650.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.02923

  6%|▌         | 28/500 [00:24<02:41,  2.92it/s]

🎧 CycleGAN-clf_05223_01601629897-clf_09697_010549.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05660

  6%|▌         | 29/500 [00:25<02:37,  2.98it/s]

🎧 CycleGAN-clf_05223_01692372116-clf_03397_002178.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11204

  6%|▌         | 30/500 [00:25<02:33,  3.07it/s]

🎧 CycleGAN-clf_05223_01692372116-clf_04310_011701.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09073

  6%|▌         | 31/500 [00:25<02:40,  2.92it/s]

🎧 CycleGAN-clf_05223_01692372116-clf_07049_012608.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.03471

  6%|▋         | 32/500 [00:26<02:48,  2.78it/s]

🎧 CycleGAN-clf_05223_01692372116-clf_09697_006663.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.06393

  7%|▋         | 33/500 [00:26<02:56,  2.64it/s]

🎧 CycleGAN-clf_05223_01948250535-clf_03397_020448.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11157

  7%|▋         | 34/500 [00:27<03:01,  2.57it/s]

🎧 CycleGAN-clf_05223_01948250535-clf_04310_009487.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08371

  7%|▋         | 35/500 [00:27<02:53,  2.67it/s]

🎧 CycleGAN-clf_05223_01948250535-clf_07049_007914.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.03316

  7%|▋         | 36/500 [00:27<02:42,  2.85it/s]

🎧 CycleGAN-clf_05223_01948250535-clf_09697_003239.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06398

  7%|▋         | 37/500 [00:28<02:53,  2.67it/s]

🎧 CycleGAN-clf_05223_01948687797-clf_03397_016539.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09084

  8%|▊         | 38/500 [00:28<03:10,  2.43it/s]

🎧 CycleGAN-clf_05223_01948687797-clf_04310_001171.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07443

  8%|▊         | 39/500 [00:29<03:24,  2.25it/s]

🎧 CycleGAN-clf_05223_01948687797-clf_07049_020773.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.02754

  8%|▊         | 40/500 [00:29<03:29,  2.20it/s]

🎧 CycleGAN-clf_05223_01948687797-clf_09697_005379.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05625

  8%|▊         | 41/500 [00:30<03:19,  2.31it/s]

🎧 CycleGAN-clf_06136_00968508047-clf_03397_019574.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.13616

  8%|▊         | 42/500 [00:30<03:20,  2.28it/s]

🎧 CycleGAN-clf_06136_01435825802-clf_03397_009747.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.13219

  9%|▊         | 43/500 [00:30<03:03,  2.49it/s]

🎧 CycleGAN-clf_06136_01489700273-clf_03397_009334.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.14700

  9%|▉         | 44/500 [00:31<03:03,  2.48it/s]

🎧 CycleGAN-clf_06136_01757942488-clf_03397_007050.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13024

  9%|▉         | 45/500 [00:31<02:47,  2.72it/s]

🎧 CycleGAN-clf_06136_01963409888-clf_03397_002525.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14834

  9%|▉         | 46/500 [00:31<02:30,  3.02it/s]

🎧 CycleGAN-clm_03034_00223642325-clm_02121_019465.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07813

  9%|▉         | 47/500 [00:31<02:16,  3.32it/s]

🎧 CycleGAN-clm_03034_00223642325-clm_04310_002989.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.18268

 10%|▉         | 48/500 [00:32<02:06,  3.58it/s]

🎧 CycleGAN-clm_03034_00223642325-clm_07049_009911.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.05077

 10%|▉         | 49/500 [00:32<01:59,  3.78it/s]

🎧 CycleGAN-clm_03034_00223642325-clm_08421_003892.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.05674

 10%|█         | 50/500 [00:32<02:00,  3.72it/s]

🎧 CycleGAN-clm_03034_00522931279-clm_02121_018799.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06063

 10%|█         | 51/500 [00:32<02:00,  3.73it/s]

🎧 CycleGAN-clm_03034_00522931279-clm_04310_020654.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.15261

 10%|█         | 52/500 [00:33<01:59,  3.76it/s]

🎧 CycleGAN-clm_03034_00522931279-clm_07049_020870.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.03952

 11%|█         | 53/500 [00:33<01:59,  3.74it/s]

🎧 CycleGAN-clm_03034_00522931279-clm_08421_019874.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.04167

 11%|█         | 54/500 [00:33<01:59,  3.74it/s]

🎧 CycleGAN-clm_03034_00658805472-clm_02121_018786.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.06450

 11%|█         | 55/500 [00:33<01:54,  3.88it/s]

🎧 CycleGAN-clm_03034_00658805472-clm_04310_006498.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14764

 11%|█         | 56/500 [00:34<01:52,  3.95it/s]

🎧 CycleGAN-clm_03034_00658805472-clm_07049_004536.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.04156

 11%|█▏        | 57/500 [00:34<01:50,  4.02it/s]

🎧 CycleGAN-clm_03034_00658805472-clm_08421_008868.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.04461

 12%|█▏        | 58/500 [00:34<01:53,  3.91it/s]

🎧 CycleGAN-clm_03034_00746585521-clm_02121_008580.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06765

 12%|█▏        | 59/500 [00:35<01:53,  3.90it/s]

🎧 CycleGAN-clm_03034_00746585521-clm_04310_004587.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.15748

 12%|█▏        | 60/500 [00:35<01:52,  3.90it/s]

🎧 CycleGAN-clm_03034_00746585521-clm_07049_019140.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04368

 12%|█▏        | 61/500 [00:35<01:52,  3.89it/s]

🎧 CycleGAN-clm_03034_00746585521-clm_08421_017687.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.04743

 12%|█▏        | 62/500 [00:35<01:54,  3.83it/s]

🎧 CycleGAN-clm_03034_01181457087-clm_02121_008359.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.06328

 13%|█▎        | 63/500 [00:36<01:53,  3.86it/s]

🎧 CycleGAN-clm_03034_01181457087-clm_04310_015969.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.14404

 13%|█▎        | 64/500 [00:36<01:52,  3.87it/s]

🎧 CycleGAN-clm_03034_01181457087-clm_07049_004980.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.04162

 13%|█▎        | 65/500 [00:36<01:52,  3.86it/s]

🎧 CycleGAN-clm_03034_01181457087-clm_08421_003030.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.04514

 13%|█▎        | 66/500 [00:36<01:53,  3.82it/s]

🎧 CycleGAN-clm_03034_01208798223-clm_02121_010492.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07607

 13%|█▎        | 67/500 [00:37<01:52,  3.86it/s]

🎧 CycleGAN-clm_03034_01208798223-clm_04310_013012.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.17001

 14%|█▎        | 68/500 [00:37<01:50,  3.90it/s]

🎧 CycleGAN-clm_03034_01208798223-clm_07049_007073.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05025

 14%|█▍        | 69/500 [00:37<01:49,  3.94it/s]

🎧 CycleGAN-clm_03034_01208798223-clm_08421_020517.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05507

 14%|█▍        | 70/500 [00:37<01:47,  3.99it/s]

🎧 CycleGAN-clm_03034_01728660592-clm_02121_009881.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07759

 14%|█▍        | 71/500 [00:38<01:47,  4.00it/s]

🎧 CycleGAN-clm_03034_01728660592-clm_04310_007992.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.17420

 14%|█▍        | 72/500 [00:38<01:45,  4.05it/s]

🎧 CycleGAN-clm_03034_01728660592-clm_07049_019106.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04977

 15%|█▍        | 73/500 [00:38<01:44,  4.07it/s]

🎧 CycleGAN-clm_03034_01728660592-clm_08421_006528.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05482

 15%|█▍        | 74/500 [00:38<01:44,  4.07it/s]

🎧 CycleGAN-clm_03034_01781920238-clm_02121_012444.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08207

 15%|█▌        | 75/500 [00:39<01:47,  3.96it/s]

🎧 CycleGAN-clm_03034_01781920238-clm_04310_017174.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.18012

 15%|█▌        | 76/500 [00:39<01:46,  3.98it/s]

🎧 CycleGAN-clm_03034_01781920238-clm_07049_013642.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05395

 15%|█▌        | 77/500 [00:39<01:46,  3.97it/s]

🎧 CycleGAN-clm_03034_01781920238-clm_08421_013126.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05880

 16%|█▌        | 78/500 [00:40<02:50,  2.47it/s]

🎧 CycleGAN-clm_03034_01784318956-clm_02121_020610.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06682

 16%|█▌        | 79/500 [00:40<02:35,  2.71it/s]

🎧 CycleGAN-clm_03034_01784318956-clm_04310_000234.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.15435

 16%|█▌        | 80/500 [00:40<02:24,  2.92it/s]

🎧 CycleGAN-clm_03034_01784318956-clm_07049_008731.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.04311

 16%|█▌        | 81/500 [00:41<02:29,  2.80it/s]

🎧 CycleGAN-clm_03034_01784318956-clm_08421_004336.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.04725

 16%|█▋        | 82/500 [00:41<02:24,  2.88it/s]

🎧 CycleGAN-clm_03034_01802784121-clm_02121_005918.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07830

 17%|█▋        | 83/500 [00:42<02:31,  2.75it/s]

🎧 CycleGAN-clm_03034_01802784121-clm_04310_014284.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.15779

 17%|█▋        | 84/500 [00:42<02:35,  2.67it/s]

🎧 CycleGAN-clm_03034_01802784121-clm_07049_000671.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05137

 17%|█▋        | 85/500 [00:42<02:30,  2.77it/s]

🎧 CycleGAN-clm_03034_01802784121-clm_08421_007628.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05428

 17%|█▋        | 86/500 [00:43<02:33,  2.69it/s]

🎧 CycleGAN-clm_03397_01585012436-clm_02121_020183.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.03943

 17%|█▋        | 87/500 [00:43<02:33,  2.70it/s]

🎧 CycleGAN-clm_03397_01764614541-clm_02121_002381.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04052

 18%|█▊        | 88/500 [00:43<02:35,  2.64it/s]

🎧 CycleGAN-clm_03397_01778279941-clm_02121_014347.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03633

 18%|█▊        | 89/500 [00:44<02:27,  2.78it/s]

🎧 CycleGAN-clm_03397_01842975985-clm_02121_016361.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.04740

 18%|█▊        | 90/500 [00:44<02:32,  2.69it/s]

🎧 CycleGAN-clm_03397_02012774879-clm_02121_013999.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.03648

 18%|█▊        | 91/500 [00:45<02:33,  2.66it/s]

🎧 Diff-clf_00610_00041705766-clf_01523_0179470137.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.04252

 18%|█▊        | 92/500 [00:45<02:36,  2.61it/s]

🎧 Diff-clf_00610_00041705766-clf_05223_0200517343.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.10692

 19%|█▊        | 93/500 [00:45<02:45,  2.45it/s]

🎧 Diff-clf_00610_00041705766-clf_07049_0018616364.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.04771

 19%|█▉        | 94/500 [00:46<02:53,  2.34it/s]

🎧 Diff-clf_00610_00041705766-clf_09697_0157293666.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.12494

 19%|█▉        | 95/500 [00:46<02:56,  2.29it/s]

🎧 Diff-clf_00610_00425819568-clf_01523_0073906580.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07276

 19%|█▉        | 96/500 [00:47<02:50,  2.37it/s]

🎧 Diff-clf_00610_00425819568-clf_05223_0070275794.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05223

 19%|█▉        | 97/500 [00:47<02:47,  2.40it/s]

🎧 Diff-clf_00610_00425819568-clf_07049_0123657859.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05230

 20%|█▉        | 98/500 [00:48<02:46,  2.42it/s]

🎧 Diff-clf_00610_00425819568-clf_09697_0010977496.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05357

 20%|█▉        | 99/500 [00:48<02:38,  2.53it/s]

🎧 Diff-clf_00610_00531398189-clf_01523_0207387070.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10869

 20%|██        | 100/500 [00:48<02:27,  2.70it/s]

🎧 Diff-clf_00610_00531398189-clf_05223_0085807635.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03603

 20%|██        | 101/500 [00:48<02:22,  2.81it/s]

🎧 Diff-clf_00610_00531398189-clf_07049_0189883332.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10353

 20%|██        | 102/500 [00:49<02:16,  2.91it/s]

🎧 Diff-clf_00610_00531398189-clf_09697_0046693667.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12208

 21%|██        | 103/500 [00:49<02:10,  3.05it/s]

🎧 Diff-clf_00610_00541921480-clf_01523_0000271886.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.18277

 21%|██        | 104/500 [00:49<02:07,  3.11it/s]

🎧 Diff-clf_00610_00541921480-clf_05223_0048279294.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06509

 21%|██        | 105/500 [00:50<02:03,  3.20it/s]

🎧 Diff-clf_00610_00541921480-clf_07049_0021087815.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05920

 21%|██        | 106/500 [00:50<02:00,  3.27it/s]

🎧 Diff-clf_00610_00541921480-clf_09697_0183106620.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.04385

 21%|██▏       | 107/500 [00:50<01:56,  3.37it/s]

🎧 Diff-clf_00610_00800782811-clf_01523_0084826109.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08319

 22%|██▏       | 108/500 [00:51<01:57,  3.33it/s]

🎧 Diff-clf_00610_00800782811-clf_05223_0011424356.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.14581

 22%|██▏       | 109/500 [00:51<01:55,  3.40it/s]

🎧 Diff-clf_00610_00800782811-clf_07049_0057476618.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13797

 22%|██▏       | 110/500 [00:51<01:52,  3.47it/s]

🎧 Diff-clf_00610_00800782811-clf_09697_0157366854.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.02696

 22%|██▏       | 111/500 [00:51<01:49,  3.55it/s]

🎧 Diff-clf_00610_01194622067-clf_01523_0024715228.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09724

 22%|██▏       | 112/500 [00:52<01:46,  3.66it/s]

🎧 Diff-clf_00610_01194622067-clf_05223_0168723603.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06191

 23%|██▎       | 113/500 [00:52<01:43,  3.72it/s]

🎧 Diff-clf_00610_01194622067-clf_07049_0177866312.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10629

 23%|██▎       | 114/500 [00:52<01:47,  3.60it/s]

🎧 Diff-clf_00610_01194622067-clf_09697_0205355989.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12964

 23%|██▎       | 115/500 [00:53<01:50,  3.47it/s]

🎧 Diff-clf_00610_01341150653-clf_01523_0105050848.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11815

 23%|██▎       | 116/500 [00:53<01:48,  3.55it/s]

🎧 Diff-clf_00610_01341150653-clf_05223_0089004159.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11978

 23%|██▎       | 117/500 [00:53<01:46,  3.60it/s]

🎧 Diff-clf_00610_01341150653-clf_07049_0059279001.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05145

 24%|██▎       | 118/500 [00:53<01:44,  3.67it/s]

🎧 Diff-clf_00610_01341150653-clf_09697_0010840718.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09076

 24%|██▍       | 119/500 [00:54<01:47,  3.55it/s]

🎧 Diff-clf_00610_01422471184-clf_01523_0115788745.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06133

 24%|██▍       | 120/500 [00:54<01:46,  3.56it/s]

🎧 Diff-clf_00610_01422471184-clf_05223_0005141554.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06071

 24%|██▍       | 121/500 [00:54<01:46,  3.55it/s]

🎧 Diff-clf_00610_01422471184-clf_07049_0004094925.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03981

 24%|██▍       | 122/500 [00:54<01:45,  3.57it/s]

🎧 Diff-clf_00610_01422471184-clf_09697_0061976278.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.16536

 25%|██▍       | 123/500 [00:55<01:48,  3.49it/s]

🎧 Diff-clf_00610_01624352669-clf_01523_0011609557.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07238

 25%|██▍       | 124/500 [00:55<01:46,  3.54it/s]

🎧 Diff-clf_00610_01624352669-clf_05223_0173010537.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09318

 25%|██▌       | 125/500 [00:55<01:43,  3.64it/s]

🎧 Diff-clf_00610_01624352669-clf_07049_0181142112.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10903

 25%|██▌       | 126/500 [00:56<01:41,  3.69it/s]

🎧 Diff-clf_00610_01624352669-clf_09697_0140997269.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04898

 25%|██▌       | 127/500 [00:56<01:44,  3.57it/s]

🎧 Diff-clf_00610_01980026766-clf_01523_0036067739.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.17313

 26%|██▌       | 128/500 [00:56<01:43,  3.60it/s]

🎧 Diff-clf_00610_01980026766-clf_05223_0110289558.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.07558

 26%|██▌       | 129/500 [00:56<01:42,  3.62it/s]

🎧 Diff-clf_00610_01980026766-clf_07049_0179551984.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.15439

 26%|██▌       | 130/500 [00:57<01:44,  3.54it/s]

🎧 Diff-clf_00610_01980026766-clf_09697_0178667393.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12446

 26%|██▌       | 131/500 [00:57<01:43,  3.57it/s]

🎧 Diff-clf_03397_00007216922-clf_01523_0128501192.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05588

 26%|██▋       | 132/500 [00:57<01:42,  3.60it/s]

🎧 Diff-clf_03397_00007216922-clf_05223_0075920893.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05582

 27%|██▋       | 133/500 [00:57<01:39,  3.68it/s]

🎧 Diff-clf_03397_00007216922-clf_07049_0203340025.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.15071

 27%|██▋       | 134/500 [00:58<01:45,  3.47it/s]

🎧 Diff-clf_03397_00007216922-clf_09697_0048123925.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.04399

 27%|██▋       | 135/500 [00:58<01:49,  3.35it/s]

🎧 Diff-clf_03397_00475591253-clf_01523_0158861966.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11359

 27%|██▋       | 136/500 [00:59<01:55,  3.14it/s]

🎧 Diff-clf_03397_00475591253-clf_05223_0089160532.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08147

 27%|██▋       | 137/500 [00:59<02:02,  2.97it/s]

🎧 Diff-clf_03397_00475591253-clf_07049_0006776033.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.17834

 28%|██▊       | 138/500 [00:59<02:03,  2.92it/s]

🎧 Diff-clf_03397_00475591253-clf_09697_0206713486.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.21302

 28%|██▊       | 139/500 [01:00<02:08,  2.82it/s]

🎧 Diff-clf_03397_00761403935-clf_01523_0021126251.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03421

 28%|██▊       | 140/500 [01:00<02:14,  2.68it/s]

🎧 Diff-clf_03397_00761403935-clf_05223_0168723603.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.03892

 28%|██▊       | 141/500 [01:00<02:16,  2.63it/s]

🎧 Diff-clf_03397_00761403935-clf_07049_0122075267.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09263

 28%|██▊       | 142/500 [01:01<02:17,  2.60it/s]

🎧 Diff-clf_03397_00761403935-clf_09697_0133830442.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.02817

 29%|██▊       | 143/500 [01:01<02:20,  2.55it/s]

🎧 Diff-clf_03397_00890001417-clf_01523_0102552215.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.17604

 29%|██▉       | 144/500 [01:02<02:24,  2.47it/s]

🎧 Diff-clf_03397_00890001417-clf_05223_0173010537.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05784

 29%|██▉       | 145/500 [01:02<02:21,  2.51it/s]

🎧 Diff-clf_03397_00890001417-clf_07049_0099428190.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07195

 29%|██▉       | 146/500 [01:02<02:17,  2.58it/s]

🎧 Diff-clf_03397_00890001417-clf_09697_0061114857.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08663

 29%|██▉       | 147/500 [01:03<02:13,  2.64it/s]

🎧 Diff-clf_03397_01124427937-clf_01523_0026728360.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.03474

 30%|██▉       | 148/500 [01:03<01:54,  3.07it/s]

🎧 Diff-clf_03397_01124427937-clf_05223_0173382939.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.15291

 30%|██▉       | 149/500 [01:03<01:43,  3.38it/s]

🎧 Diff-clf_03397_01124427937-clf_07049_0195496062.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08332

 30%|███       | 150/500 [01:03<01:35,  3.65it/s]

🎧 Diff-clf_03397_01124427937-clf_09697_0208877913.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08701

 30%|███       | 151/500 [01:04<01:29,  3.91it/s]

🎧 Diff-clf_03397_01329926118-clf_01523_0036976828.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.29129

 30%|███       | 152/500 [01:04<01:24,  4.12it/s]

🎧 Diff-clf_03397_01329926118-clf_05223_0015332209.wav
   - Features extraídas: 575
   - Tempo: 208.33
   - RMSE manual: 0.28445

 31%|███       | 153/500 [01:04<01:20,  4.29it/s]

🎧 Diff-clf_03397_01329926118-clf_07049_0004094925.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10464

 31%|███       | 154/500 [01:04<01:21,  4.25it/s]

🎧 Diff-clf_03397_01329926118-clf_09697_0151935015.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08802

 31%|███       | 155/500 [01:05<01:20,  4.28it/s]

🎧 Diff-clf_03397_01386651670-clf_01523_0077484245.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.15157

 31%|███       | 156/500 [01:05<01:17,  4.42it/s]

🎧 Diff-clf_03397_01386651670-clf_05223_0040092737.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.07507

 31%|███▏      | 157/500 [01:05<01:16,  4.48it/s]

🎧 Diff-clf_03397_01386651670-clf_07049_0082452816.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.06872

 32%|███▏      | 158/500 [01:05<01:16,  4.48it/s]

🎧 Diff-clf_03397_01386651670-clf_09697_0194106148.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09641

 32%|███▏      | 159/500 [01:05<01:17,  4.42it/s]

🎧 Diff-clf_03397_01558221291-clf_01523_0168659927.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.07058

 32%|███▏      | 160/500 [01:06<01:15,  4.48it/s]

🎧 Diff-clf_03397_01558221291-clf_05223_0029034304.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.14550

 32%|███▏      | 161/500 [01:06<01:14,  4.53it/s]

🎧 Diff-clf_03397_01558221291-clf_07049_0024940648.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07885

 32%|███▏      | 162/500 [01:06<01:13,  4.61it/s]

🎧 Diff-clf_03397_01558221291-clf_09697_0129685471.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15367

 33%|███▎      | 163/500 [01:06<01:18,  4.31it/s]

🎧 Diff-clf_03397_01936219933-clf_01523_0203367484.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09181

 33%|███▎      | 164/500 [01:07<01:19,  4.24it/s]

🎧 Diff-clf_03397_01936219933-clf_05223_0137654768.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.34864

 33%|███▎      | 165/500 [01:07<01:20,  4.14it/s]

🎧 Diff-clf_03397_01936219933-clf_07049_0122294255.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08606

 33%|███▎      | 166/500 [01:07<01:21,  4.11it/s]

🎧 Diff-clf_03397_01936219933-clf_09697_0057283493.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.19512

 33%|███▎      | 167/500 [01:07<01:24,  3.96it/s]

🎧 Diff-clf_03397_02084497079-clf_01523_0209620610.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.04210

 34%|███▎      | 168/500 [01:08<01:23,  3.96it/s]

🎧 Diff-clf_03397_02084497079-clf_05223_0184568426.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.13873

 34%|███▍      | 169/500 [01:08<01:22,  4.01it/s]

🎧 Diff-clf_03397_02084497079-clf_07049_0200087503.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.21029

 34%|███▍      | 170/500 [01:08<01:21,  4.07it/s]

🎧 Diff-clf_03397_02084497079-clf_09697_0114118106.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06251

 34%|███▍      | 171/500 [01:08<01:24,  3.90it/s]

🎧 Diff-clm_02121_00144740661-clm_00610_0060018021.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09512

 34%|███▍      | 172/500 [01:09<01:28,  3.71it/s]

🎧 Diff-clm_02121_00144740661-clm_01208_0133293225.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.14754

 35%|███▍      | 173/500 [01:09<01:28,  3.68it/s]

🎧 Diff-clm_02121_00144740661-clm_05223_0049826934.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.05839

 35%|███▍      | 174/500 [01:09<01:29,  3.64it/s]

🎧 Diff-clm_02121_00144740661-clm_06136_0138872060.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10850

 35%|███▌      | 175/500 [01:09<01:26,  3.74it/s]

🎧 Diff-clm_02121_00584464825-clm_00610_0102835083.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.12514

 35%|███▌      | 176/500 [01:10<01:24,  3.85it/s]

🎧 Diff-clm_02121_00584464825-clm_01208_0083969432.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.07591

 35%|███▌      | 177/500 [01:10<01:21,  3.98it/s]

🎧 Diff-clm_02121_00584464825-clm_05223_0059061317.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.15482

 36%|███▌      | 178/500 [01:10<01:19,  4.05it/s]

🎧 Diff-clm_02121_00584464825-clm_06136_0038286730.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.18595

 36%|███▌      | 179/500 [01:11<01:27,  3.66it/s]

🎧 Diff-clm_02121_00982290337-clm_00610_0001476160.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08230

 36%|███▌      | 180/500 [01:11<01:31,  3.49it/s]

🎧 Diff-clm_02121_00982290337-clm_01208_0201740975.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11322

 36%|███▌      | 181/500 [01:11<01:34,  3.39it/s]

🎧 Diff-clm_02121_00982290337-clm_05223_0197471922.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13760

 36%|███▋      | 182/500 [01:11<01:38,  3.24it/s]

🎧 Diff-clm_02121_00982290337-clm_06136_0145894666.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.15629

 37%|███▋      | 183/500 [01:12<01:39,  3.17it/s]

🎧 Diff-clm_02121_01149397551-clm_00610_0207996888.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.05436

 37%|███▋      | 184/500 [01:12<01:39,  3.19it/s]

🎧 Diff-clm_02121_01149397551-clm_01208_0200570787.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09123

 37%|███▋      | 185/500 [01:12<01:37,  3.22it/s]

🎧 Diff-clm_02121_01149397551-clm_05223_0209867529.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11385

 37%|███▋      | 186/500 [01:13<01:46,  2.96it/s]

🎧 Diff-clm_02121_01149397551-clm_06136_0096915804.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.14305

 37%|███▋      | 187/500 [01:13<01:55,  2.72it/s]

🎧 Diff-clm_02121_01317943059-clm_00610_0019778812.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.13093

 38%|███▊      | 188/500 [01:14<02:02,  2.55it/s]

🎧 Diff-clm_02121_01317943059-clm_01208_0182208027.wav
   - Features extraídas: 575
   - Tempo: 81.52
   - RMSE manual: 0.16426

 38%|███▊      | 189/500 [01:14<01:59,  2.60it/s]

🎧 Diff-clm_02121_01317943059-clm_05223_0014588025.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11280

 38%|███▊      | 190/500 [01:15<02:04,  2.48it/s]

🎧 Diff-clm_02121_01317943059-clm_06136_0158564555.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.19016

 38%|███▊      | 191/500 [01:15<02:09,  2.38it/s]

🎧 Diff-clm_02121_01328510599-clm_00610_0084726239.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.20565

 38%|███▊      | 192/500 [01:15<02:10,  2.35it/s]

🎧 Diff-clm_02121_01328510599-clm_01208_0078018650.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06763

 39%|███▊      | 193/500 [01:16<02:13,  2.31it/s]

🎧 Diff-clm_02121_01328510599-clm_05223_0030949096.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.06720

 39%|███▉      | 194/500 [01:16<02:11,  2.32it/s]

🎧 Diff-clm_02121_01328510599-clm_06136_0099875710.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.04303

 39%|███▉      | 195/500 [01:17<02:06,  2.40it/s]

🎧 Diff-clm_02121_01499208065-clm_00610_0005894809.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.05708

 39%|███▉      | 196/500 [01:17<02:05,  2.43it/s]

🎧 Diff-clm_02121_01499208065-clm_01208_0201631551.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09769

 39%|███▉      | 197/500 [01:17<02:02,  2.47it/s]

🎧 Diff-clm_02121_01499208065-clm_05223_0213561683.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.12563

 40%|███▉      | 198/500 [01:18<01:58,  2.55it/s]

🎧 Diff-clm_02121_01499208065-clm_06136_0010330382.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.04649

 40%|███▉      | 199/500 [01:18<01:48,  2.78it/s]

🎧 Diff-clm_02121_01878637699-clm_00610_0027626301.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11117

 40%|████      | 200/500 [01:18<01:41,  2.94it/s]

🎧 Diff-clm_02121_01878637699-clm_01208_0088530317.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06464

 40%|████      | 201/500 [01:19<01:35,  3.12it/s]

🎧 Diff-clm_02121_01878637699-clm_05223_0207165762.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07949

 40%|████      | 202/500 [01:19<01:30,  3.29it/s]

🎧 Diff-clm_02121_01878637699-clm_06136_0166512684.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06747

 41%|████      | 203/500 [01:19<01:28,  3.35it/s]

🎧 Diff-clm_02121_01923437403-clm_00610_0097400416.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.05667

 41%|████      | 204/500 [01:20<01:25,  3.48it/s]

🎧 Diff-clm_02121_01923437403-clm_01208_0090956492.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.04529

 41%|████      | 205/500 [01:20<01:23,  3.55it/s]

🎧 Diff-clm_02121_01923437403-clm_05223_0109856605.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.21052

 41%|████      | 206/500 [01:20<01:21,  3.62it/s]

🎧 Diff-clm_02121_01923437403-clm_06136_0026743692.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08113

 41%|████▏     | 207/500 [01:20<01:19,  3.69it/s]

🎧 Diff-clm_02121_01930296583-clm_00610_0034540814.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.19168

 42%|████▏     | 208/500 [01:21<01:17,  3.78it/s]

🎧 Diff-clm_02121_01930296583-clm_01208_0122113124.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.10374

 42%|████▏     | 209/500 [01:21<01:15,  3.83it/s]

🎧 Diff-clm_02121_01930296583-clm_05223_0097041920.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.06158

 42%|████▏     | 210/500 [01:21<01:14,  3.91it/s]

🎧 Diff-clm_02121_01930296583-clm_06136_0212466005.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08499

 42%|████▏     | 211/500 [01:21<01:17,  3.72it/s]

🎧 Diff-clm_03349_00138186603-clm_00610_0027868898.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.06461

 42%|████▏     | 212/500 [01:22<01:17,  3.70it/s]

🎧 Diff-clm_03349_00138186603-clm_01208_0088530317.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.11370

 43%|████▎     | 213/500 [01:22<01:17,  3.71it/s]

🎧 Diff-clm_03349_00138186603-clm_05223_0097041920.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.15620

 43%|████▎     | 214/500 [01:22<01:16,  3.72it/s]

🎧 Diff-clm_03349_00138186603-clm_06136_0107628126.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.22409

 43%|████▎     | 215/500 [01:22<01:14,  3.82it/s]

🎧 Diff-clm_03349_00303377873-clm_00610_0190657976.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.06401

 43%|████▎     | 216/500 [01:23<01:11,  4.00it/s]

🎧 Diff-clm_03349_00303377873-clm_01208_0137638611.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.16694

 43%|████▎     | 217/500 [01:23<01:08,  4.14it/s]

🎧 Diff-clm_03349_00303377873-clm_05223_0076016195.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08111

 44%|████▎     | 218/500 [01:23<01:06,  4.22it/s]

🎧 Diff-clm_03349_00303377873-clm_06136_0008344344.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.21000

 44%|████▍     | 219/500 [01:23<01:07,  4.17it/s]

🎧 Diff-clm_03349_00335831013-clm_00610_0157419130.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.18586

 44%|████▍     | 220/500 [01:24<01:08,  4.09it/s]

🎧 Diff-clm_03349_00335831013-clm_01208_0156410472.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.05130

 44%|████▍     | 221/500 [01:24<01:07,  4.12it/s]

🎧 Diff-clm_03349_00335831013-clm_05223_0139773380.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10712

 44%|████▍     | 222/500 [01:24<01:09,  4.01it/s]

🎧 Diff-clm_03349_00335831013-clm_06136_0015602334.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.14741

 45%|████▍     | 223/500 [01:24<01:09,  4.01it/s]

🎧 Diff-clm_03349_01134339224-clm_00610_0094173511.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.19855

 45%|████▍     | 224/500 [01:25<01:10,  3.93it/s]

🎧 Diff-clm_03349_01134339224-clm_01208_0155398879.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.23275

 45%|████▌     | 225/500 [01:25<01:08,  4.02it/s]

🎧 Diff-clm_03349_01134339224-clm_05223_0179288979.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.19024

 45%|████▌     | 226/500 [01:25<01:08,  4.01it/s]

🎧 Diff-clm_03349_01134339224-clm_06136_0119326798.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09408

 45%|████▌     | 227/500 [01:25<01:09,  3.91it/s]

🎧 Diff-clm_03349_01489548395-clm_00610_0117632016.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10874

 46%|████▌     | 228/500 [01:26<01:12,  3.73it/s]

🎧 Diff-clm_03349_01489548395-clm_01208_0135228894.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.19470

 46%|████▌     | 229/500 [01:26<01:11,  3.77it/s]

🎧 Diff-clm_03349_01489548395-clm_05223_0008995161.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.18543

 46%|████▌     | 230/500 [01:26<01:13,  3.69it/s]

🎧 Diff-clm_03349_01489548395-clm_06136_0054640934.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.18594

 46%|████▌     | 231/500 [01:26<01:14,  3.63it/s]

🎧 Diff-clm_03349_01504548446-clm_00610_0075385555.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.23539

 46%|████▋     | 232/500 [01:27<01:14,  3.60it/s]

🎧 Diff-clm_03349_01504548446-clm_01208_0038726715.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.24689

 47%|████▋     | 233/500 [01:27<01:12,  3.69it/s]

🎧 Diff-clm_03349_01504548446-clm_05223_0177814845.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07804

 47%|████▋     | 234/500 [01:27<01:10,  3.75it/s]

🎧 Diff-clm_03349_01504548446-clm_06136_0197878989.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09952

 47%|████▋     | 235/500 [01:28<01:12,  3.67it/s]

🎧 Diff-clm_03349_01619891787-clm_00610_0181173466.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13564

 47%|████▋     | 236/500 [01:28<01:14,  3.52it/s]

🎧 Diff-clm_03349_01619891787-clm_01208_0057856895.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07557

 47%|████▋     | 237/500 [01:28<01:21,  3.23it/s]

🎧 Diff-clm_03349_01619891787-clm_05223_0061066243.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13203

 48%|████▊     | 238/500 [01:29<01:28,  2.96it/s]

🎧 Diff-clm_03349_01619891787-clm_06136_0195089880.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.05198

 48%|████▊     | 239/500 [01:29<01:36,  2.71it/s]

🎧 Diff-clm_03349_01771978546-clm_00610_0060018021.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.23491

 48%|████▊     | 240/500 [01:29<01:33,  2.78it/s]

🎧 Diff-clm_03349_01771978546-clm_01208_0036331534.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.17044

 48%|████▊     | 241/500 [01:30<01:36,  2.70it/s]

🎧 Diff-clm_03349_01771978546-clm_05223_0213608196.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.15458

 48%|████▊     | 242/500 [01:30<01:42,  2.51it/s]

🎧 Diff-clm_03349_01771978546-clm_06136_0038286730.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.12757

 49%|████▊     | 243/500 [01:31<01:34,  2.73it/s]

🎧 Diff-clm_03349_01824880873-clm_00610_0040539953.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15417

 49%|████▉     | 244/500 [01:31<01:34,  2.70it/s]

🎧 Diff-clm_03349_01824880873-clm_01208_0075802629.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.23333

 49%|████▉     | 245/500 [01:31<01:33,  2.73it/s]

🎧 Diff-clm_03349_01824880873-clm_05223_0001330418.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09158

 49%|████▉     | 246/500 [01:32<01:33,  2.71it/s]

🎧 Diff-clm_03349_01824880873-clm_06136_0136782832.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.27021

 49%|████▉     | 247/500 [01:32<01:37,  2.59it/s]

🎧 Diff-clm_03349_02015822892-clm_00610_0001810768.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09168

 50%|████▉     | 248/500 [01:32<01:33,  2.70it/s]

🎧 Diff-clm_03349_02015822892-clm_01208_0201631551.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09309

 50%|████▉     | 249/500 [01:33<01:32,  2.70it/s]

🎧 Diff-clm_03349_02015822892-clm_05223_0159700406.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10074

 50%|█████     | 250/500 [01:33<01:32,  2.70it/s]

🎧 Diff-clm_03349_02015822892-clm_06136_0148544231.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.06369

 50%|█████     | 251/500 [01:33<01:24,  2.93it/s]

🎧 StarGAN-clf_03397_00131107356-clf_04310_0180900.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06085

 50%|█████     | 252/500 [01:34<01:17,  3.21it/s]

🎧 StarGAN-clf_03397_00131107356-clf_05223_0006229.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.06302

 51%|█████     | 253/500 [01:34<01:12,  3.40it/s]

🎧 StarGAN-clf_03397_00131107356-clf_08784_0171101.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06045

 51%|█████     | 254/500 [01:34<01:08,  3.58it/s]

🎧 StarGAN-clf_03397_00131107356-clf_09334_0167020.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.06865

 51%|█████     | 255/500 [01:34<01:07,  3.65it/s]

🎧 StarGAN-clf_03397_00372618834-clf_04310_0046099.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08578

 51%|█████     | 256/500 [01:35<01:06,  3.66it/s]

🎧 StarGAN-clf_03397_00372618834-clf_05223_0072186.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09246

 51%|█████▏    | 257/500 [01:35<01:05,  3.69it/s]

🎧 StarGAN-clf_03397_00372618834-clf_08784_0089440.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07987

 52%|█████▏    | 258/500 [01:35<01:06,  3.66it/s]

🎧 StarGAN-clf_03397_00372618834-clf_09334_0106985.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09960

 52%|█████▏    | 259/500 [01:36<01:02,  3.84it/s]

🎧 StarGAN-clf_03397_00783648238-clf_04310_0181728.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11342
🎧 StarGAN-clf_03397_00783648238-clf_05223_0085807.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10311

 52%|█████▏    | 262/500 [01:36<00:53,  4.46it/s]

🎧 StarGAN-clf_03397_00783648238-clf_08784_0154023.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10136
🎧 StarGAN-clf_03397_00783648238-clf_09334_0029897.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11502

 53%|█████▎    | 263/500 [01:36<00:55,  4.25it/s]

🎧 StarGAN-clf_03397_00905905971-clf_04310_0014395.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.07620

 53%|█████▎    | 264/500 [01:37<00:57,  4.07it/s]

🎧 StarGAN-clf_03397_00905905971-clf_05223_0208542.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07981

 53%|█████▎    | 265/500 [01:37<00:58,  4.05it/s]

🎧 StarGAN-clf_03397_00905905971-clf_08784_0083035.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07253

 53%|█████▎    | 266/500 [01:37<00:58,  4.01it/s]

🎧 StarGAN-clf_03397_00905905971-clf_09334_0149207.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.08773

 53%|█████▎    | 267/500 [01:37<01:00,  3.88it/s]

🎧 StarGAN-clf_03397_00907759458-clf_04310_0168442.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.09569

 54%|█████▎    | 268/500 [01:38<00:58,  3.96it/s]

🎧 StarGAN-clf_03397_00907759458-clf_05223_0200672.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09621

 54%|█████▍    | 269/500 [01:38<00:57,  4.00it/s]

🎧 StarGAN-clf_03397_00907759458-clf_08784_0131441.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08824

 54%|█████▍    | 270/500 [01:38<00:58,  3.95it/s]

🎧 StarGAN-clf_03397_00907759458-clf_09334_0033799.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10476

 54%|█████▍    | 271/500 [01:38<01:00,  3.80it/s]

🎧 StarGAN-clf_03397_01052451614-clf_04310_0131880.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09222

 54%|█████▍    | 272/500 [01:39<01:00,  3.79it/s]

🎧 StarGAN-clf_03397_01052451614-clf_05223_0075134.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09257

 55%|█████▍    | 273/500 [01:39<00:58,  3.88it/s]

🎧 StarGAN-clf_03397_01052451614-clf_08784_0107878.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08274

 55%|█████▍    | 274/500 [01:39<00:56,  3.97it/s]

🎧 StarGAN-clf_03397_01052451614-clf_09334_0144404.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10431

 55%|█████▌    | 275/500 [01:39<00:55,  4.02it/s]

🎧 StarGAN-clf_03397_01555803676-clf_04310_0013384.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11197

 55%|█████▌    | 276/500 [01:40<00:54,  4.14it/s]

🎧 StarGAN-clf_03397_01555803676-clf_05223_0170817.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11990

 55%|█████▌    | 277/500 [01:40<00:52,  4.28it/s]

🎧 StarGAN-clf_03397_01555803676-clf_08784_0156486.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10512

 56%|█████▌    | 278/500 [01:40<00:50,  4.38it/s]

🎧 StarGAN-clf_03397_01555803676-clf_09334_0143235.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12505

 56%|█████▌    | 279/500 [01:40<00:49,  4.50it/s]

🎧 StarGAN-clf_03397_01890389211-clf_04310_0167919.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08353

 56%|█████▌    | 280/500 [01:41<00:49,  4.41it/s]

🎧 StarGAN-clf_03397_01890389211-clf_05223_0200517.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09888

 56%|█████▌    | 281/500 [01:41<00:49,  4.45it/s]

🎧 StarGAN-clf_03397_01890389211-clf_08784_0061256.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08386

 56%|█████▋    | 282/500 [01:41<00:48,  4.49it/s]

🎧 StarGAN-clf_03397_01890389211-clf_09334_0197063.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.08621

 57%|█████▋    | 283/500 [01:41<00:49,  4.36it/s]

🎧 StarGAN-clf_03397_02084497079-clf_04310_0003743.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09430

 57%|█████▋    | 284/500 [01:41<00:50,  4.24it/s]

🎧 StarGAN-clf_03397_02084497079-clf_05223_0190642.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09096

 57%|█████▋    | 285/500 [01:42<00:53,  4.06it/s]

🎧 StarGAN-clf_03397_02084497079-clf_08784_0143114.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08848

 57%|█████▋    | 286/500 [01:42<00:52,  4.08it/s]

🎧 StarGAN-clf_03397_02084497079-clf_09334_0080847.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09707

 57%|█████▋    | 287/500 [01:42<00:49,  4.26it/s]

🎧 StarGAN-clf_03397_02127150623-clf_04310_0148227.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10376

 58%|█████▊    | 288/500 [01:42<00:47,  4.43it/s]

🎧 StarGAN-clf_03397_02127150623-clf_05223_0199883.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.09298

 58%|█████▊    | 289/500 [01:43<00:48,  4.31it/s]

🎧 StarGAN-clf_03397_02127150623-clf_08784_0007796.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09671

 58%|█████▊    | 290/500 [01:43<00:46,  4.47it/s]

🎧 StarGAN-clf_03397_02127150623-clf_09334_0064573.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10168

 58%|█████▊    | 291/500 [01:43<00:46,  4.45it/s]

🎧 StarGAN-clf_07508_00745078280-clf_04310_0105267.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08367

 58%|█████▊    | 292/500 [01:43<00:49,  4.22it/s]

🎧 StarGAN-clf_07508_01419065519-clf_04310_0167919.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10305

 59%|█████▊    | 293/500 [01:44<01:01,  3.35it/s]

🎧 StarGAN-clf_07508_01424986399-clf_04310_0161549.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08682

 59%|█████▉    | 294/500 [01:44<01:08,  3.01it/s]

🎧 StarGAN-clf_07508_01426842540-clf_04310_0038495.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.09323

 59%|█████▉    | 295/500 [01:45<01:14,  2.76it/s]

🎧 StarGAN-clf_07508_02143155917-clf_04310_0001279.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08880

 59%|█████▉    | 296/500 [01:45<01:17,  2.64it/s]

🎧 StarGAN-clm_05223_00023834565-clm_01208_0109537.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10421

 59%|█████▉    | 297/500 [01:46<01:21,  2.49it/s]

🎧 StarGAN-clm_05223_00023834565-clm_02484_0172000.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07847

 60%|█████▉    | 298/500 [01:46<01:18,  2.57it/s]

🎧 StarGAN-clm_05223_00023834565-clm_03034_0179290.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10665

 60%|█████▉    | 299/500 [01:46<01:16,  2.62it/s]

🎧 StarGAN-clm_05223_00023834565-clm_09334_0116708.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.08550

 60%|██████    | 300/500 [01:47<01:17,  2.58it/s]

🎧 StarGAN-clm_05223_00058555595-clm_01208_0202429.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.13383

 60%|██████    | 301/500 [01:47<01:18,  2.53it/s]

🎧 StarGAN-clm_05223_00058555595-clm_02484_0079005.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09388

 60%|██████    | 302/500 [01:47<01:19,  2.48it/s]

🎧 StarGAN-clm_05223_00058555595-clm_03034_0036027.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.12715

 61%|██████    | 303/500 [01:48<01:20,  2.43it/s]

🎧 StarGAN-clm_05223_00058555595-clm_09334_0147336.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10583

 61%|██████    | 304/500 [01:48<01:19,  2.48it/s]

🎧 StarGAN-clm_05223_00199172843-clm_01208_0000046.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14349

 61%|██████    | 305/500 [01:49<01:14,  2.62it/s]

🎧 StarGAN-clm_05223_00199172843-clm_02484_0103715.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10089

 61%|██████    | 306/500 [01:49<01:06,  2.94it/s]

🎧 StarGAN-clm_05223_00199172843-clm_03034_0188362.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.17587

 61%|██████▏   | 307/500 [01:49<01:00,  3.18it/s]

🎧 StarGAN-clm_05223_00199172843-clm_09334_0117838.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10953

 62%|██████▏   | 308/500 [01:49<00:57,  3.35it/s]

🎧 StarGAN-clm_05223_00351407225-clm_01208_0001441.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12236

 62%|██████▏   | 309/500 [01:50<00:53,  3.54it/s]

🎧 StarGAN-clm_05223_00351407225-clm_02484_0115757.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09040

 62%|██████▏   | 310/500 [01:50<00:51,  3.69it/s]

🎧 StarGAN-clm_05223_00351407225-clm_03034_0045076.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11355

 62%|██████▏   | 311/500 [01:50<00:50,  3.75it/s]

🎧 StarGAN-clm_05223_00351407225-clm_09334_0164917.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10018

 62%|██████▏   | 312/500 [01:50<00:49,  3.79it/s]

🎧 StarGAN-clm_05223_00470327477-clm_01208_0121646.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10404

 63%|██████▎   | 313/500 [01:51<00:48,  3.83it/s]

🎧 StarGAN-clm_05223_00470327477-clm_02484_0098046.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07080

 63%|██████▎   | 314/500 [01:51<00:47,  3.90it/s]

🎧 StarGAN-clm_05223_00470327477-clm_03034_0057487.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09845

 63%|██████▎   | 315/500 [01:51<00:46,  3.96it/s]

🎧 StarGAN-clm_05223_00470327477-clm_09334_0122051.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.07360

 63%|██████▎   | 316/500 [01:51<00:47,  3.88it/s]

🎧 StarGAN-clm_05223_01104724751-clm_01208_0053583.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.11807

 63%|██████▎   | 317/500 [01:52<00:47,  3.87it/s]

🎧 StarGAN-clm_05223_01104724751-clm_02484_0101726.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08732

 64%|██████▎   | 318/500 [01:52<00:46,  3.94it/s]

🎧 StarGAN-clm_05223_01104724751-clm_03034_0168997.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.11118

 64%|██████▍   | 319/500 [01:52<00:45,  3.99it/s]

🎧 StarGAN-clm_05223_01104724751-clm_09334_0063578.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.09319

 64%|██████▍   | 320/500 [01:52<00:44,  4.02it/s]

🎧 StarGAN-clm_05223_01157800278-clm_01208_0044659.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10782

 64%|██████▍   | 321/500 [01:53<00:44,  4.06it/s]

🎧 StarGAN-clm_05223_01157800278-clm_02484_0000880.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07801

 64%|██████▍   | 322/500 [01:53<00:43,  4.11it/s]

🎧 StarGAN-clm_05223_01157800278-clm_03034_0011703.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10367

 65%|██████▍   | 323/500 [01:53<00:42,  4.17it/s]

🎧 StarGAN-clm_05223_01157800278-clm_09334_0158521.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08295

 65%|██████▍   | 324/500 [01:54<01:07,  2.60it/s]

🎧 StarGAN-clm_05223_01556576140-clm_01208_0018922.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.13092

 65%|██████▌   | 325/500 [01:54<00:59,  2.93it/s]

🎧 StarGAN-clm_05223_01556576140-clm_02484_0018485.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.08784

 65%|██████▌   | 326/500 [01:54<00:54,  3.19it/s]

🎧 StarGAN-clm_05223_01556576140-clm_03034_0052632.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11695

 65%|██████▌   | 327/500 [01:55<01:12,  2.39it/s]

🎧 StarGAN-clm_05223_01556576140-clm_09334_0158787.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09261

 66%|██████▌   | 328/500 [01:55<01:03,  2.73it/s]

🎧 StarGAN-clm_05223_01792889791-clm_01208_0040746.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.13313

 66%|██████▌   | 329/500 [01:55<00:57,  2.96it/s]

🎧 StarGAN-clm_05223_01792889791-clm_02484_0148954.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09736

 66%|██████▌   | 330/500 [01:56<00:54,  3.13it/s]

🎧 StarGAN-clm_05223_01792889791-clm_03034_0048533.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12945

 66%|██████▌   | 331/500 [01:56<00:51,  3.31it/s]

🎧 StarGAN-clm_05223_01792889791-clm_09334_0036347.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10329

 66%|██████▋   | 332/500 [01:56<00:47,  3.54it/s]

🎧 StarGAN-clm_05223_02108435198-clm_01208_0120741.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.14636

 67%|██████▋   | 333/500 [01:57<00:45,  3.68it/s]

🎧 StarGAN-clm_05223_02108435198-clm_02484_0136115.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.09646

 67%|██████▋   | 334/500 [01:57<00:45,  3.66it/s]

🎧 StarGAN-clm_05223_02108435198-clm_03034_0190654.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.14220

 67%|██████▋   | 335/500 [01:57<00:44,  3.71it/s]

🎧 StarGAN-clm_05223_02108435198-clm_09334_0206591.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.10667

 67%|██████▋   | 336/500 [01:57<00:44,  3.68it/s]

🎧 StarGAN-clm_06136_00179543632-clm_01208_0132558.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.15315

 67%|██████▋   | 337/500 [01:58<00:44,  3.62it/s]

🎧 StarGAN-clm_06136_00267436923-clm_01208_0056276.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.14232

 68%|██████▊   | 338/500 [01:58<00:43,  3.70it/s]

🎧 StarGAN-clm_06136_00538138594-clm_01208_0109460.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15304

 68%|██████▊   | 339/500 [01:58<00:42,  3.81it/s]

🎧 StarGAN-clm_06136_00546409340-clm_01208_0074708.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.12220

 68%|██████▊   | 341/500 [01:59<00:37,  4.24it/s]

🎧 StarGAN-clm_06136_00786278703-clm_01208_0198310.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12784
🎧 TTS-Diff-clf_01523_00754595541_TTS-clm_08421_02.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.12328

 68%|██████▊   | 342/500 [01:59<00:40,  3.90it/s]

🎧 TTS-Diff-clf_01523_01114358572_TTS-clm_01523_02.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.24944

 69%|██████▊   | 343/500 [01:59<00:45,  3.49it/s]

🎧 TTS-Diff-clf_01523_01394538900_TTS-clf_00610_01.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.22963

 69%|██████▉   | 344/500 [01:59<00:45,  3.46it/s]

🎧 TTS-Diff-clf_01523_02123164297_TTS-clf_00610_00.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.21614

 69%|██████▉   | 345/500 [02:00<00:47,  3.25it/s]

🎧 TTS-Diff-clf_02484_01338641166_TTS-clf_03397_00.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10815

 69%|██████▉   | 346/500 [02:00<00:49,  3.14it/s]

🎧 TTS-Diff-clf_02484_01451477427_TTS-clf_07049_00.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.08485

 69%|██████▉   | 347/500 [02:01<00:52,  2.91it/s]

🎧 TTS-Diff-clf_02484_02101296107_TTS-clf_07508_00.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.12117

 70%|██████▉   | 348/500 [02:01<00:54,  2.79it/s]

🎧 TTS-Diff-clf_03397_00281035811_TTS-clf_00610_01.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.18214

 70%|██████▉   | 349/500 [02:01<00:52,  2.89it/s]

🎧 TTS-Diff-clf_03397_00676692977_TTS-clm_03397_01.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.24920

 70%|███████   | 350/500 [02:02<00:49,  3.05it/s]

🎧 TTS-Diff-clf_03397_01842599013_TTS-clm_00610_00.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.06032

 70%|███████   | 351/500 [02:02<00:49,  3.00it/s]

🎧 TTS-Diff-clf_04310_00382329081_TTS-clf_07049_01.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.11184

 70%|███████   | 352/500 [02:02<00:50,  2.92it/s]

🎧 TTS-Diff-clf_04310_00606019109_TTS-clf_03397_00.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.30593

 71%|███████   | 353/500 [02:03<00:52,  2.81it/s]

🎧 TTS-Diff-clf_04310_00660286119_TTS-clm_00610_02.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.08517

 71%|███████   | 354/500 [02:03<00:51,  2.86it/s]

🎧 TTS-Diff-clf_04310_00660286119_TTS-clm_01523_01.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.11235

 71%|███████   | 355/500 [02:03<00:49,  2.95it/s]

🎧 TTS-Diff-clf_05223_02005173439_TTS-clf_01523_01.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.03380

 71%|███████   | 356/500 [02:04<00:50,  2.82it/s]

🎧 TTS-Diff-clf_06136_00055797202_TTS-clf_07049_00.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.05448

 72%|███████▏  | 358/500 [02:04<00:42,  3.37it/s]

🎧 TTS-Diff-clf_06136_00489658200_TTS-clm_00610_00.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10284
🎧 TTS-Diff-clf_06136_01303561503_TTS-clf_07049_01.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.23755

 72%|███████▏  | 359/500 [02:04<00:39,  3.54it/s]

🎧 TTS-Diff-clf_07049_01913346472_TTS-clf_01523_00.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10404

 72%|███████▏  | 361/500 [02:05<00:34,  4.05it/s]

🎧 TTS-Diff-clf_07049_01913346472_TTS-clf_07508_00.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.14986
🎧 TTS-Diff-clm_00610_00521833890_TTS-clm_00610_01.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.24340

 73%|███████▎  | 363/500 [02:05<00:30,  4.53it/s]

🎧 TTS-Diff-clm_00610_01638577268_TTS-clm_08421_01.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.23376
🎧 TTS-Diff-clm_00610_01767011448_TTS-clf_03397_01.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.49549

 73%|███████▎  | 365/500 [02:06<00:28,  4.75it/s]

🎧 TTS-Diff-clm_00610_01818025700_TTS-clm_08421_00.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.35486
🎧 TTS-Diff-clm_01523_00766318347_TTS-clm_01523_00.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15263

 73%|███████▎  | 367/500 [02:06<00:27,  4.91it/s]

🎧 TTS-Diff-clm_01523_01321090718_TTS-clm_08421_01.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.27158
🎧 TTS-Diff-clm_02121_00134358971_TTS-clf_03397_00.wav
   - Features extraídas: 575
   - Tempo: 208.33
   - RMSE manual: 0.17361

 74%|███████▍  | 369/500 [02:07<00:26,  5.01it/s]

🎧 TTS-Diff-clm_02121_00134358971_TTS-clm_00610_00.wav
   - Features extraídas: 575
   - Tempo: 208.33
   - RMSE manual: 0.19044
🎧 TTS-Diff-clm_02121_01049213728_TTS-clm_06136_00.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.29448

 74%|███████▍  | 371/500 [02:07<00:25,  5.01it/s]

🎧 TTS-Diff-clm_02121_01539141834_TTS-clf_00610_01.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.13626
🎧 TTS-Diff-clm_02436_00067749404_TTS-clm_03397_02.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.29736

 74%|███████▍  | 372/500 [02:07<00:25,  4.96it/s]

🎧 TTS-Diff-clm_02436_00332512167_TTS-clf_01523_01.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.02938
🎧 TTS-Diff-clm_02436_00332512167_TTS-clf_07049_00.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.18823

 75%|███████▍  | 374/500 [02:08<00:27,  4.55it/s]

🎧 TTS-Diff-clm_02436_00805049692_TTS-clf_01523_01.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.12066

 75%|███████▌  | 375/500 [02:08<00:29,  4.25it/s]

🎧 TTS-Diff-clm_02436_00805049692_TTS-clf_03397_01.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.07810

 75%|███████▌  | 377/500 [02:08<00:27,  4.55it/s]

🎧 TTS-Diff-clm_02436_01458515831_TTS-clm_00610_00.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.16866
🎧 TTS-Diff-clm_02436_01687054434_TTS-clf_01523_01.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.23243

 76%|███████▌  | 378/500 [02:09<00:27,  4.42it/s]

🎧 TTS-Diff-clm_02436_01873332465_TTS-clf_00610_01.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.03262
🎧 TTS-Diff-clm_02484_00224411834_TTS-clm_03397_01.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09136

 76%|███████▌  | 381/500 [02:09<00:25,  4.69it/s]

🎧 TTS-Diff-clm_02484_00883203167_TTS-clf_07508_01.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.25441
🎧 TTS-StarGAN-clf_00610_01328563459_TTS-clm_03349.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15271

 76%|███████▋  | 382/500 [02:09<00:24,  4.84it/s]

🎧 TTS-StarGAN-clf_01523_00768857460_TTS-clm_03034.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15541

 77%|███████▋  | 383/500 [02:10<00:25,  4.55it/s]

🎧 TTS-StarGAN-clf_01523_01265284343_TTS-clf_07508.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12768

 77%|███████▋  | 384/500 [02:10<00:26,  4.32it/s]

🎧 TTS-StarGAN-clf_01523_01278206897_TTS-clf_04310.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14246

 77%|███████▋  | 386/500 [02:10<00:24,  4.56it/s]

🎧 TTS-StarGAN-clf_02484_00067369754_TTS-clf_08784.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11588
🎧 TTS-StarGAN-clf_03397_01415001018_TTS-clm_05223.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14976

 77%|███████▋  | 387/500 [02:10<00:24,  4.69it/s]

🎧 TTS-StarGAN-clf_03397_01971249779_TTS-clm_09697.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.15702

 78%|███████▊  | 388/500 [02:11<00:24,  4.57it/s]

🎧 TTS-StarGAN-clf_03397_02044829132_TTS-clf_08784.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10976

 78%|███████▊  | 389/500 [02:11<00:24,  4.52it/s]

🎧 TTS-StarGAN-clf_04310_00144516673_TTS-clf_09334.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.12032

 78%|███████▊  | 390/500 [02:11<00:24,  4.43it/s]

🎧 TTS-StarGAN-clf_04310_00621636203_TTS-clf_07508.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.13006

 78%|███████▊  | 391/500 [02:11<00:24,  4.44it/s]

🎧 TTS-StarGAN-clf_04310_01067757281_TTS-clm_09697.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11669

 78%|███████▊  | 392/500 [02:12<00:24,  4.40it/s]

🎧 TTS-StarGAN-clf_04310_01686723690_TTS-clf_04310.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.14431

 79%|███████▊  | 393/500 [02:12<00:23,  4.51it/s]

🎧 TTS-StarGAN-clf_04310_01798645660_TTS-clf_04310.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13648

 79%|███████▉  | 394/500 [02:12<00:23,  4.54it/s]

🎧 TTS-StarGAN-clf_05223_00051415547_TTS-clf_09334.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11396

 79%|███████▉  | 395/500 [02:12<00:22,  4.59it/s]

🎧 TTS-StarGAN-clf_05223_00086574876_TTS-clf_04310.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.13645

 79%|███████▉  | 396/500 [02:12<00:22,  4.57it/s]

🎧 TTS-StarGAN-clf_05223_01657291019_TTS-clf_07508.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.12465

 79%|███████▉  | 397/500 [02:13<00:23,  4.42it/s]

🎧 TTS-StarGAN-clf_06136_00488624148_TTS-clm_09697.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13982

 80%|███████▉  | 398/500 [02:13<00:23,  4.38it/s]

🎧 TTS-StarGAN-clf_06136_00489658200_TTS-clf_09334.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.14444

 80%|███████▉  | 399/500 [02:13<00:23,  4.35it/s]

🎧 TTS-StarGAN-clf_06136_00955408733_TTS-clm_03349.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.16277

 80%|████████  | 400/500 [02:13<00:23,  4.31it/s]

🎧 TTS-StarGAN-clf_06136_00994161715_TTS-clf_04310.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.13622

 80%|████████  | 401/500 [02:14<00:23,  4.17it/s]

🎧 TTS-StarGAN-clm_00610_00053988382_TTS-clf_07508.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.09816

 80%|████████  | 402/500 [02:14<00:23,  4.16it/s]

🎧 TTS-StarGAN-clm_00610_01281786267_TTS-clf_09334.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10253

 81%|████████  | 403/500 [02:14<00:24,  3.89it/s]

🎧 TTS-StarGAN-clm_00610_01767011448_TTS-clm_03034.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.09317

 81%|████████  | 404/500 [02:15<00:28,  3.42it/s]

🎧 TTS-StarGAN-clm_00610_02097558970_TTS-clf_09334.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.09105

 81%|████████  | 405/500 [02:15<00:32,  2.97it/s]

🎧 TTS-StarGAN-clm_01208_00405642503_TTS-clm_02484.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.07819

 81%|████████  | 406/500 [02:15<00:33,  2.82it/s]

🎧 TTS-StarGAN-clm_01208_00405642503_TTS-clm_05223.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.11580

 81%|████████▏ | 407/500 [02:16<00:31,  2.95it/s]

🎧 TTS-StarGAN-clm_01208_01229211467_TTS-clf_09334.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10116

 82%|████████▏ | 408/500 [02:16<00:29,  3.09it/s]

🎧 TTS-StarGAN-clm_01523_00531785006_TTS-clm_03349.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.09108

 82%|████████▏ | 409/500 [02:16<00:30,  2.96it/s]

🎧 TTS-StarGAN-clm_02121_00330085995_TTS-clm_09697.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10943

 82%|████████▏ | 410/500 [02:17<00:29,  3.02it/s]

🎧 TTS-StarGAN-clm_02121_00466521752_TTS-clm_02484.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.07903

 82%|████████▏ | 411/500 [02:17<00:30,  2.94it/s]

🎧 TTS-StarGAN-clm_02121_01049213728_TTS-clm_03034.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.10038

 82%|████████▏ | 412/500 [02:17<00:30,  2.89it/s]

🎧 TTS-StarGAN-clm_02121_01276315500_TTS-clf_05223.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.09226

 83%|████████▎ | 413/500 [02:18<00:31,  2.80it/s]

🎧 TTS-StarGAN-clm_02436_00067749404_TTS-clm_05223.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12163

 83%|████████▎ | 414/500 [02:18<00:30,  2.80it/s]

🎧 TTS-StarGAN-clm_02436_00389187647_TTS-clf_08784.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.08590

 83%|████████▎ | 415/500 [02:18<00:29,  2.91it/s]

🎧 TTS-StarGAN-clm_02436_01095878510_TTS-clm_09697.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.09886

 83%|████████▎ | 416/500 [02:19<00:30,  2.78it/s]

🎧 TTS-StarGAN-clm_02436_01319445700_TTS-clf_08784.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.08903

 83%|████████▎ | 417/500 [02:19<00:30,  2.69it/s]

🎧 TTS-StarGAN-clm_02436_01840247158_TTS-clf_05223.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.10029

 84%|████████▎ | 418/500 [02:20<00:27,  2.93it/s]

🎧 TTS-StarGAN-clm_02436_02010999053_TTS-clm_05223.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.12677

 84%|████████▍ | 419/500 [02:20<00:24,  3.29it/s]

🎧 TTS-StarGAN-clm_02484_00300484094_TTS-clf_08784.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.09502

 84%|████████▍ | 420/500 [02:20<00:22,  3.58it/s]

🎧 TTS-StarGAN-clm_02484_00843567635_TTS-clm_03349.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10442

 84%|████████▍ | 421/500 [02:20<00:20,  3.80it/s]

🎧 TTS-clf_00610_00226607880.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.14365

 84%|████████▍ | 422/500 [02:20<00:19,  3.95it/s]

🎧 TTS-clf_00610_00437708667.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.14456

 85%|████████▍ | 423/500 [02:21<00:19,  3.92it/s]

🎧 TTS-clf_00610_00531398189.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12451
🎧 TTS-clf_00610_00652927506.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.14277

 85%|████████▌ | 425/500 [02:21<00:17,  4.24it/s]

🎧 TTS-clf_00610_01066269150.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12293

 85%|████████▌ | 426/500 [02:21<00:17,  4.21it/s]

🎧 TTS-clf_00610_01106589800.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12418

 85%|████████▌ | 427/500 [02:22<00:17,  4.24it/s]

🎧 TTS-clf_00610_01114986956.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.12307

 86%|████████▌ | 428/500 [02:22<00:17,  4.22it/s]

🎧 TTS-clf_00610_01264386200.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12470

 86%|████████▌ | 430/500 [02:22<00:15,  4.48it/s]

🎧 TTS-clf_00610_01313263316.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.13145
🎧 TTS-clf_00610_01328563459.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12478

 86%|████████▌ | 431/500 [02:22<00:15,  4.47it/s]

🎧 TTS-clf_00610_01422471184.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12679

 86%|████████▋ | 432/500 [02:23<00:14,  4.59it/s]

🎧 TTS-clf_00610_01427307386.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.14114

 87%|████████▋ | 433/500 [02:23<00:14,  4.54it/s]

🎧 TTS-clf_00610_01762603748.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.12343

 87%|████████▋ | 434/500 [02:23<00:14,  4.53it/s]

🎧 TTS-clf_00610_01847416048.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14037

 87%|████████▋ | 435/500 [02:23<00:14,  4.48it/s]

🎧 TTS-clf_00610_02067016031.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.12631

 87%|████████▋ | 437/500 [02:24<00:13,  4.72it/s]

🎧 TTS-clf_01523_00073255913.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11442
🎧 TTS-clf_01523_00116095579.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.13554

 88%|████████▊ | 439/500 [02:24<00:12,  4.74it/s]

🎧 TTS-clf_01523_00117928877.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.12294
🎧 TTS-clf_01523_00118928658.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.15133

 88%|████████▊ | 440/500 [02:24<00:12,  4.76it/s]

🎧 TTS-clf_01523_00267283609.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.12284

 88%|████████▊ | 441/500 [02:25<00:12,  4.69it/s]

🎧 TTS-clf_01523_00271020354.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.13855

 89%|████████▊ | 443/500 [02:25<00:12,  4.72it/s]

🎧 TTS-clf_01523_00341727089.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11964
🎧 TTS-clf_01523_00406176244.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.13394

 89%|████████▉ | 444/500 [02:25<00:11,  4.75it/s]

🎧 TTS-clf_01523_00431279373.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13237

 89%|████████▉ | 445/500 [02:25<00:12,  4.56it/s]

🎧 TTS-clf_01523_00660985684.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.15481

 89%|████████▉ | 447/500 [02:26<00:11,  4.71it/s]

🎧 TTS-clf_01523_00730116429.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13937
🎧 TTS-clf_01523_00754595541.wav
   - Features extraídas: 575
   - Tempo: 78.12
   - RMSE manual: 0.14343

 90%|████████▉ | 448/500 [02:26<00:10,  4.88it/s]

🎧 TTS-clf_01523_00768857460.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.15037

 90%|████████▉ | 449/500 [02:26<00:10,  4.80it/s]

🎧 TTS-clf_01523_00774842459.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13239

 90%|█████████ | 450/500 [02:27<00:10,  4.76it/s]

🎧 TTS-clf_01523_00850465509.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.13146

 90%|█████████ | 451/500 [02:27<00:10,  4.59it/s]

🎧 TTS-clf_01523_00871925396.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11818

 90%|█████████ | 452/500 [02:27<00:10,  4.48it/s]

🎧 TTS-clf_01523_00891293959.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.13325
🎧 TTS-clf_01523_00907265446.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11835

 91%|█████████ | 454/500 [02:27<00:09,  4.63it/s]

🎧 TTS-clf_01523_00942518128.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.13767

 91%|█████████ | 455/500 [02:28<00:09,  4.58it/s]

🎧 TTS-clf_01523_00994111014.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.13764

 91%|█████████▏| 457/500 [02:28<00:09,  4.73it/s]

🎧 TTS-clf_01523_01056881786.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.13311
🎧 TTS-clf_01523_01105104569.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.13188

 92%|█████████▏| 459/500 [02:28<00:08,  4.89it/s]

🎧 TTS-clf_01523_01114358572.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.12901
🎧 TTS-clf_01523_01128139853.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12933

 92%|█████████▏| 461/500 [02:29<00:07,  4.93it/s]

🎧 TTS-clf_01523_01157887456.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.12179
🎧 TTS-clm_00610_00040639103.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11548

 92%|█████████▏| 462/500 [02:29<00:07,  4.86it/s]

🎧 TTS-clm_00610_00053988382.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.10861

 93%|█████████▎| 463/500 [02:29<00:08,  4.39it/s]

🎧 TTS-clm_00610_00128728624.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11567

 93%|█████████▎| 464/500 [02:30<00:08,  4.04it/s]

🎧 TTS-clm_00610_00345408148.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.13029

 93%|█████████▎| 465/500 [02:30<00:09,  3.63it/s]

🎧 TTS-clm_00610_00521833890.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.14105

 93%|█████████▎| 466/500 [02:30<00:10,  3.38it/s]

🎧 TTS-clm_00610_00847262395.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.12930

 93%|█████████▎| 467/500 [02:31<00:10,  3.27it/s]

🎧 TTS-clm_00610_00848750826.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.12105

 94%|█████████▎| 468/500 [02:31<00:09,  3.23it/s]

🎧 TTS-clm_00610_00947645104.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.11804

 94%|█████████▍| 469/500 [02:31<00:09,  3.29it/s]

🎧 TTS-clm_00610_01028350839.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.11949

 94%|█████████▍| 470/500 [02:32<00:09,  3.26it/s]

🎧 TTS-clm_00610_01117421937.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12802

 94%|█████████▍| 471/500 [02:32<00:09,  3.21it/s]

🎧 TTS-clm_00610_01281786267.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11995

 94%|█████████▍| 472/500 [02:32<00:08,  3.31it/s]

🎧 TTS-clm_00610_01401106310.wav
   - Features extraídas: 575
   - Tempo: 98.68
   - RMSE manual: 0.11299

 95%|█████████▍| 473/500 [02:33<00:08,  3.16it/s]

🎧 TTS-clm_00610_01484961628.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.11326

 95%|█████████▍| 474/500 [02:33<00:07,  3.45it/s]

🎧 TTS-clm_00610_01539898624.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12068

 95%|█████████▌| 475/500 [02:33<00:07,  3.22it/s]

🎧 TTS-clm_00610_01552462807.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.12712

 95%|█████████▌| 476/500 [02:33<00:07,  3.11it/s]

🎧 TTS-clm_00610_01638577268.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10907

 95%|█████████▌| 477/500 [02:34<00:07,  3.12it/s]

🎧 TTS-clm_00610_01767011448.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.12605

 96%|█████████▌| 478/500 [02:34<00:07,  3.11it/s]

🎧 TTS-clm_00610_01818025700.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.10909

 96%|█████████▌| 479/500 [02:34<00:06,  3.08it/s]

🎧 TTS-clm_00610_01916101835.wav
   - Features extraídas: 575
   - Tempo: 117.19
   - RMSE manual: 0.12087

 96%|█████████▌| 480/500 [02:35<00:06,  3.18it/s]

🎧 TTS-clm_00610_02008900710.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.10255

 96%|█████████▌| 481/500 [02:35<00:05,  3.48it/s]

🎧 TTS-clm_00610_02023737613.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.11020

 97%|█████████▋| 483/500 [02:35<00:04,  3.95it/s]

🎧 TTS-clm_00610_02097558970.wav
   - Features extraídas: 575
   - Tempo: 93.75
   - RMSE manual: 0.10485
🎧 TTS-clm_01208_00000465757.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11044

 97%|█████████▋| 484/500 [02:36<00:03,  4.23it/s]

🎧 TTS-clm_01208_00014411465.wav
   - Features extraídas: 575
   - Tempo: 133.93
   - RMSE manual: 0.11567
🎧 TTS-clm_01208_00020409831.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.11020

 97%|█████████▋| 486/500 [02:36<00:03,  4.60it/s]

🎧 TTS-clm_01208_00076404302.wav
   - Features extraídas: 575
   - Tempo: 89.29
   - RMSE manual: 0.13540

 98%|█████████▊| 488/500 [02:36<00:02,  4.78it/s]

🎧 TTS-clm_01208_00109693662.wav
   - Features extraídas: 575
   - Tempo: 85.23
   - RMSE manual: 0.12425
🎧 TTS-clm_01208_00125820526.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11014

 98%|█████████▊| 489/500 [02:37<00:02,  4.63it/s]

🎧 TTS-clm_01208_00221548154.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.11808

 98%|█████████▊| 490/500 [02:37<00:02,  4.47it/s]

🎧 TTS-clm_01208_00405642503.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.10938

 98%|█████████▊| 491/500 [02:37<00:02,  4.47it/s]

🎧 TTS-clm_01208_00407468590.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11215

 98%|█████████▊| 492/500 [02:37<00:01,  4.49it/s]

🎧 TTS-clm_01208_00502189299.wav
   - Features extraídas: 575
   - Tempo: 110.29
   - RMSE manual: 0.11861

 99%|█████████▉| 494/500 [02:38<00:01,  4.70it/s]

🎧 TTS-clm_01208_00727800961.wav
   - Features extraídas: 575
   - Tempo: 170.45
   - RMSE manual: 0.11946
🎧 TTS-clm_01208_00747089235.wav
   - Features extraídas: 575
   - Tempo: 156.25
   - RMSE manual: 0.12105

 99%|█████████▉| 495/500 [02:38<00:01,  4.73it/s]

🎧 TTS-clm_01208_00839694323.wav
   - Features extraídas: 575
   - Tempo: 144.23
   - RMSE manual: 0.11794

 99%|█████████▉| 496/500 [02:38<00:00,  4.72it/s]

🎧 TTS-clm_01208_01041660935.wav
   - Features extraídas: 575
   - Tempo: 187.50
   - RMSE manual: 0.11976

100%|█████████▉| 498/500 [02:39<00:00,  4.78it/s]

🎧 TTS-clm_01208_01096922678.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.12051
🎧 TTS-clm_01208_01207410495.wav
   - Features extraídas: 575
   - Tempo: 75.00
   - RMSE manual: 0.12103

100%|█████████▉| 499/500 [02:39<00:00,  4.74it/s]

🎧 TTS-clm_01208_01216467857.wav
   - Features extraídas: 575
   - Tempo: 125.00
   - RMSE manual: 0.10225

100%|██████████| 500/500 [02:39<00:00,  3.13it/s]

🎧 TTS-clm_01208_01229211467.wav
   - Features extraídas: 575
   - Tempo: 104.17
   - RMSE manual: 0.11146

In [ ]:
print("\n Creando DataFrame...")

df = pd.DataFrame(registros)

print(" DataFrame creado")
print(f"   - Filas: {df.shape[0]}")
print(f"   - Columnas: {df.shape[1]}")

df.head()

 Creando DataFrame...
 DataFrame creado
   - Filas: 500
   - Columnas: 589

,id_audio,archivo,label,genero_f,colombiano,chileno,argentino,peruano,modelo_cyclegan,modelo_diff,...,rolloff_std,rolloff_min,rolloff_max,rolloff_median,rolloff_q1,rolloff_q3,rolloff_skew,rolloff_kurtosis,rolloff_mode,rolloff_iqr
0,1,CycleGAN-clf_05223_00086574876-clf_03397_01336...,1,1,0,1,0,0,1,0,...,1737.794563,171.8750,7273.4375,3640.62500,1898.437500,4929.687500,-0.015848,-1.125790,2757.8125,3031.250000
1,2,CycleGAN-clf_05223_00086574876-clf_04310_01629...,1,1,0,1,0,0,1,0,...,1919.135148,187.5000,7343.7500,4339.84375,2068.359375,5525.390625,-0.192997,-1.358087,1187.5000,3457.031250
2,3,CycleGAN-clf_05223_00086574876-clf_07049_00147...,1,1,0,1,0,0,1,0,...,1952.102029,171.8750,7289.0625,4453.12500,2132.812500,5656.250000,-0.239998,-1.343159,2351.5625,3523.437500
3,4,CycleGAN-clf_05223_00086574876-clf_09697_00965...,1,1,0,1,0,0,1,0,...,1761.820821,187.5000,7312.5000,4066.40625,2281.250000,5138.671875,-0.160017,-1.171392,1398.4375,2857.421875
4,5,CycleGAN-clf_05223_00571992422-clf_03397_00831...,1,1,0,1,0,0,1,0,...,1921.594961,195.3125,7109.3750,3015.62500,1787.109375,5351.562500,0.170794,-1.353723,5351.5625,3564.453125

In [ ]:
#Revisar columnas
print("\n Información de columnas:")

print(f"Total columnas: {len(df.columns)}")

print("\nPrimeras 20 columnas:")
print(df.columns[:20])

print("\nÚltimas 20 columnas:")
print(df.columns[-20:])

 Información de columnas:
Total columnas: 589

Primeras 20 columnas:
Index(['id_audio', 'archivo', 'label', 'genero_f', 'colombiano', 'chileno',
       'argentino', 'peruano', 'modelo_cyclegan', 'modelo_diff',
       'modelo_stargan', 'modelo_tts_dif', 'modelo_tts_stargan', 'modelo_tts',
       'duracion_seg', 'zcr_mean', 'zcr_std', 'zcr_min', 'zcr_max',
       'zcr_median'],
      dtype='object')

Últimas 20 columnas:
Index(['flatness_min', 'flatness_max', 'flatness_median', 'flatness_q1',
       'flatness_q3', 'flatness_skew', 'flatness_kurtosis', 'flatness_mode',
       'flatness_iqr', 'rolloff_mean', 'rolloff_std', 'rolloff_min',
       'rolloff_max', 'rolloff_median', 'rolloff_q1', 'rolloff_q3',
       'rolloff_skew', 'rolloff_kurtosis', 'rolloff_mode', 'rolloff_iqr'],
      dtype='object')

In [ ]:
#Revisar información general
print("\n Información general del DataFrame:")
df.info()

 Información general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Columns: 589 entries, id_audio to rolloff_iqr
dtypes: float32(1), float64(574), int64(13), object(1)
memory usage: 2.2+ MB

In [ ]:
print("\n Estadísticas descriptivas:")
df.describe()

 Estadísticas descriptivas:

,id_audio,label,genero_f,colombiano,chileno,argentino,peruano,modelo_cyclegan,modelo_diff,modelo_stargan,...,rolloff_std,rolloff_min,rolloff_max,rolloff_median,rolloff_q1,rolloff_q3,rolloff_skew,rolloff_kurtosis,rolloff_mode,rolloff_iqr
count,500.000000,500.0,500.000000,500.0,500.0,500.0,500.0,500.000000,500.000000,500.000000,...,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,250.500000,1.0,0.472000,0.0,1.0,0.0,0.0,0.180000,0.320000,0.180000,...,1754.080831,429.046875,7099.250000,3611.132812,2125.988281,4886.449219,0.128658,-0.712670,3070.125000,2760.460938
std,144.481833,0.0,0.499715,0.0,0.0,0.0,0.0,0.384572,0.466943,0.384572,...,273.119124,321.899904,400.596396,919.802351,545.370701,827.208143,0.596289,0.760836,1819.720512,892.600991
min,1.000000,1.0,0.000000,0.0,1.0,0.0,0.0,0.000000,0.000000,0.000000,...,1135.049808,93.750000,4929.687500,1812.500000,1070.312500,2449.218750,-1.163694,-1.762974,109.375000,746.093750
25%,125.750000,1.0,0.000000,0.0,1.0,0.0,0.0,0.000000,0.000000,0.000000,...,1549.268871,187.500000,6873.046875,2768.554688,1732.421875,4458.496094,-0.332500,-1.300267,1505.859375,2156.250000
50%,250.500000,1.0,0.000000,0.0,1.0,0.0,0.0,0.000000,0.000000,0.000000,...,1697.935043,320.312500,7171.875000,3585.937500,2002.929688,4878.906250,0.025874,-0.844605,2625.000000,2743.164062
75%,375.250000,1.0,1.000000,0.0,1.0,0.0,0.0,0.000000,1.000000,0.000000,...,1956.876954,539.062500,7382.812500,4411.132812,2428.222656,5445.312500,0.543444,-0.337515,4634.765625,3312.988281
max,500.000000,1.0,1.000000,0.0,1.0,0.0,0.0,1.000000,1.000000,1.000000,...,2493.051114,1835.937500,7828.125000,5679.687500,4855.468750,7103.515625,1.666475,2.522596,7515.625000,5162.109375

In [ ]:
#Revisamos una fila
print("\n Inspección de una fila completa:")

fila = df.iloc[0]

print(fila)
print("\nTotal de valores en esta fila:", len(fila))

 Inspección de una fila completa:
id_audio                                                            1
archivo             CycleGAN-clf_05223_00086574876-clf_03397_01336...
label                                                               1
genero_f                                                            1
colombiano                                                          0
                                          ...
rolloff_q3                                                  4929.6875
rolloff_skew                                                -0.015848
rolloff_kurtosis                                             -1.12579
rolloff_mode                                                2757.8125
rolloff_iqr                                                   3031.25
Name: 0, Length: 589, dtype: object

Total de valores en esta fila: 589

#3.0 Guardado y descarga del dataset

In [ ]:
#Guardamos el dataset
print("\n Guardando dataset...")

nombre_csv = f"dataset_features_{TIPO_DATASET}.csv"
ruta_salida_csv = f"/content/drive/MyDrive/Reto_Telefonica/{nombre_csv}"

df.to_csv(ruta_salida_csv, index=False)

print(" Dataset guardado correctamente")
print(f" Ruta: {ruta_salida_csv}")
print(f" Shape final: {df.shape}")

 Guardando dataset...
 Dataset guardado correctamente
 Ruta: /content/drive/MyDrive/Reto_Telefonica/dataset_features_sintetico.csv
 Shape final: (500, 589)

In [ ]:
#Descargamos el dataset
print("\n Preparando descarga...")

from google.colab import files
files.download(ruta_salida_csv)

print(" Descarga iniciada")

 Preparando descarga...

 Descarga iniciada